### ISSUE TITLE
Weird sorting title in media

### ISSUE THREAD

**Issue by GameSpeck** [UnigramDev/Unigram#1500] opened 2020-05-02 13:07 UTC
Media tab of group: 
![image](https://user-images.githubusercontent.com/43648146/80864948-b6a44c00-8ca3-11ea-991a-fb51d3613506.png)
They look the same as any image's shape.

Files tab of group: 
![image](https://user-images.githubusercontent.com/43648146/80864976-de93af80-8ca3-11ea-9957-55ab885104ae.png)
Titles of months with files under them

**Comment by FrayxRulez** [comment] 2020-05-02 13:23
This is a workaround caused by a UWP limitation

**Comment by MarcAnt01** [comment] 2020-05-02 13:31
Duplicate of https://github.com/UnigramDev/Unigram/issues/1116

**Closed by MarcAnt01** 2020-05-02 13:31 UTC
Labels: blocked
