### ISSUE TITLE
Rotate a video within the video player

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#2189] opened 2020-12-18 18:17 UTC

**Comment by FrayxRulez** [comment] 2021-04-10 19:28
Duplicate of #1296

**Closed by FrayxRulez** 2021-04-10 19:28 UTC
Labels: video player

**Comment by MarcAnt01** [comment] 2021-04-10 19:47
@FrayxRulez the issue you've referenced is about photos, this one is about video. Should I open this issue again or refactor the other one to be more generic?

**Comment by FrayxRulez** [comment] 2021-04-10 19:48
I've already refactored the other one.

**Comment by MarcAnt01** [comment] 2021-04-10 19:49
Perfect, I updated the description, as well
