### ISSUE TITLE
Unable to enter in the emojis/gif/stickers search field on Windows Mobile

### ISSUE THREAD

**Issue by Aarklendoia** [UnigramDev/Unigram#1188] opened 2019-07-22 09:29 UTC
The search field for emojis/gif/stickers isn't available on Windows Mobile. When you touch it to enter a word, the cursor remains in the message entry field instead of being placed in the search field.

**Comment by MarcAnt01** [comment] 2019-07-22 11:53
Duplicate of https://github.com/UnigramDev/Unigram/issues/1129

**Closed by MarcAnt01** 2019-07-22 11:53 UTC
