### ISSUE TITLE
Change behaviour of "Adaptive layout for wide screens"

### ISSUE THREAD

**Issue by GameSpeck** [UnigramDev/Unigram#1483] opened 2020-05-01 12:40 UTC
Telegram: 
![image](https://user-images.githubusercontent.com/43648146/80805982-12ed6a00-8bd7-11ea-9c3a-7112f64a6796.png)

Unigram:
![image](https://user-images.githubusercontent.com/43648146/80805955-fea96d00-8bd6-11ea-8ec5-b649daf586be.png)
My message looks like it is in the center, it should be placed at the left

**Comment by MarcAnt01** [comment] 2020-05-01 12:56
I don't understand the purpose of this ticket

**Comment by beerisgood** [comment] 2020-05-01 13:07
Can't confirm this behaviour on 4K monitor/ with 4k resolution

**Comment by GameSpeck** [comment] 2020-05-01 13:12
> I don't understand the purpose of this ticket

It's really weird to see my messages at the centre of the screen, leaving so much space on the right

**Comment by MarcAnt01** [comment] 2020-05-01 13:20
You can disable adaptive layout. I still don't get if you are reporting a bug or suggesting an improvement

**Comment by GameSpeck** [comment] 2020-05-01 13:25
> You can disable adaptive layout. I still don't get if you are reporting a bug or suggesting an improvement

I am suggesting it to make the same as Telegram, all messages at left.

**Comment by FrayxRulez** [comment] 2020-05-15 13:06
My plan is to actually set a max width and align messages (including input field) to the center of the screen, as new Telegram web design suggests to do.
What do you think?

**Comment by cewbdex** [comment] 2020-06-01 18:15
Duplicate of #1179

**Closed by cewbdex** 2020-06-01 18:15 UTC
Labels: chat, feature request
