### ISSUE TITLE
Notifications all arrive a 2nd time when you open the app on mobile

### ISSUE THREAD

**Issue by slackerstacker** [UnigramDev/Unigram#1275] opened 2019-12-23 23:21 UTC
Hello,

Using a Lumia 950 with Windows 10 mobile, notifications show when messages arive. Upon opening the app all notifications show up again. One after the other. This is very annoying when you have about a dozen messages or more. I have 2 friends who also have a Lumia 950 and they have the same issue. Disabling in-app notifications does not solve the issue, not sure if that's a bug too?

Was wondering if this can be fixed?

**Comment by hooddy** [comment] 2019-12-23 23:31
Oh yeah it's annoying me.

**Comment by MarcAnt01** [comment] 2019-12-24 08:37
Duplicate of #1206

**Closed by MarcAnt01** 2019-12-24 08:37 UTC
