### ISSUE TITLE
No way to cancel forwarding a message on desktop

### ISSUE THREAD

**Issue by Yoshi2889** [UnigramDev/Unigram#310] opened 2017-06-22 18:44 UTC
When forwarding a message on desktop and changing your mind, there is no way to cancel out of the "Select a recipient to foward to" screen (not even via the back button or Escape).

**Comment by FrayxRulez** [comment] 2017-06-22 18:46
Considering this a duplicate of #239

**Comment by Yoshi2889** [comment] 2017-06-22 18:46
Oh it didn't show up when I searched, my apologies.

**Closed by FrayxRulez** 2017-06-22 18:46 UTC

**Comment by FrayxRulez** [comment] 2017-06-22 18:47
No problem! Any effort is appreciated
