### ISSUE TITLE
Unable to create discussion groups

### ISSUE THREAD

**Issue by ServicesRCL** [UnigramDev/Unigram#2691] opened 2022-03-27 13:42 UTC
**Describe the bug**
I am unable to create discussion groups

**To Reproduce**
1. Create a channel
2. Go to the parameters of the channel
3. Click Edit
4. Go to discussion
5. Click Create a new group
6. It doesn't do anything

**Expected behavior**
I expected it to create a group and add it to my list of chats
**Screenshots**
None

**Version Info**
 - Unigram: [8.6 7275  X64 Direct]
 - Windows: [Windows 11 21H2 22000.556] (From WinVer.exe)

**Comment by MarcAnt01** [comment] 2022-03-27 15:37
Hi, thanks for reporting, but there's already a ticket about this

**Comment by MarcAnt01** [comment] 2022-03-27 15:37
Duplicate of https://github.com/UnigramDev/Unigram/issues/2319

**Closed by MarcAnt01** 2022-03-27 15:37 UTC
Labels: bug
