### ISSUE TITLE
add options to recent action as same as tlgrm desktop

### ISSUE THREAD

**Issue by samij263** [UnigramDev/Unigram#672] opened 2018-09-12 17:08 UTC
And also it loads just few recent actions(as i always seen).

**Comment by MarcAnt01** [comment] 2018-09-12 17:10
@samij263 Try to explain yourself

**Comment by MarcAnt01** [comment] 2018-09-12 17:14
I think it's better adding this information to my issue https://github.com/UnigramDev/Unigram/issues/638 and closing this one, just to make Fela's work easier

**Comment by FrayxRulez** [comment] 2018-09-13 15:56
Duplicate of #638

**Closed by FrayxRulez** 2018-09-13 15:56 UTC
Labels: duplicate
