### ISSUE TITLE
Unigram does not show popup for group chat where user was banned

### ISSUE THREAD

**Issue by Kenya-West** [UnigramDev/Unigram#2973] opened 2023-02-18 07:48 UTC
**Describe the bug**
When user was banned in some group, the official Android client shows a popup that explains what is going on and why you cannot get access to the group.

**To Reproduce**
The easiest example of reproduction is to get banned in a discussion chat linked to some channel,:
1. Have sex with admin's mother in any group chat;
2. Get your account banned;
3. Try to get access to the chat you got banned in;
4. You see that no comments section is shown in any of the posts of the linked channel. So you cannot get in the chat to see popup.

**Expected behavior**
The comments should be shown, and user should see popup with text saying you got banned in the chat.

**Screenshots**
| Official client (Android) | Unigram |
|:-------------------------:|:-------:|
| ![Screenshot_2023-02-18-13-41-07-662_org telegram messenger-edit](https://user-images.githubusercontent.com/12271104/219848534-f5493f29-2a67-4fc6-84f8-fb580cad0b77.jpg) | ![image](https://user-images.githubusercontent.com/12271104/219848546-f5e2bd4a-967c-4265-908d-3779e0d2eae8.png) |

**Version Info**
 - Unigram: 9.3 (7970)
 - Windows: 11 latest stable

**Comment by 525226463** [comment] 2023-02-18 18:36
D mula as cafe alor setar kedah malaysia and crew...prank buskers

**Comment by MarcAnt01** [comment] 2023-02-18 21:16
Thanks for reporting, this is known

**Comment by MarcAnt01** [comment] 2023-02-18 21:16
Duplicate of https://github.com/UnigramDev/Unigram/issues/649

**Closed by MarcAnt01** 2023-02-18 21:16 UTC
Labels: bug, needs-triage
