### ISSUE TITLE
Local proxy not working

### ISSUE THREAD

**Issue by HamidRezaAshkiyan** [UnigramDev/Unigram#1894] opened 2020-07-06 06:51 UTC
I want to connect to TOR on localhost but its not working in unigram. I have to probelm in telegram desktop.
and psiphon also not working not in socks5 proxy mode.

**Comment by HamidRezaAshkiyan** [comment] 2020-07-06 12:26
I found a solution for this problem but its not built in so you should do it manually. 

there is two way: do it with cmd and with GUI way.
I prefer GUI way because its nicer and easier. you can find ENABLE LOOPBACK app in the link below.

https://stackoverflow.com/questions/34589522/cant-see-localhost-from-uwp-app

**Comment by MarcAnt01** [comment] 2020-07-06 12:50
Hello, thanks for reporting, but we have already a ticket for that

**Comment by MarcAnt01** [comment] 2020-07-06 12:51
Duplicate of https://github.com/UnigramDev/Unigram/issues/877

**Closed by MarcAnt01** 2020-07-06 12:51 UTC
