### ISSUE TITLE
Unhandle Exception when dragging contact list to avatar column

### ISSUE THREAD

**Issue by Geobert** [UnigramDev/Unigram#1131] opened 2019-05-28 20:07 UTC
![image](https://user-images.githubusercontent.com/72570/58508697-851a2b00-818c-11e9-94e0-a52b014860f2.png)

When dragging the contact list until it collapse to a single avatar column

**Comment by MarcAnt01** [comment] 2019-05-28 20:08
Duplicate of https://github.com/UnigramDev/Unigram/issues/1121

**Closed by MarcAnt01** 2019-05-28 20:08 UTC

**Comment by Geobert** [comment] 2019-05-28 20:09
Sorry, I've searched opened issue, forgot to search on closed one (the most important…)

**Comment by MarcAnt01** [comment] 2019-05-28 20:10
Don't worry, bug is already fixed in the source code, but the developer has no access to a PC for the moment, so cannot push the hotfix to the Store
