### ISSUE TITLE
 support Chinese translation

### ISSUE THREAD

**Issue by xin67** [UnigramDev/Unigram#2969] opened 2023-02-11 02:14 UTC
Friends， can support Chinese translation？
This feature is very important to us

**Comment by makisukurisu** [comment] 2023-02-11 05:43
@xin67 Unigram uses Telegram Android translations.

So you can ask for an official Chinese translation on https://translations.telegram.org/

Also - you can use an unofficial pack like that one:
https://t.me/setlanguage/zh-hans-beta

**Comment by MarcAnt01** [comment] 2023-02-11 14:00
Duplicate of https://github.com/UnigramDev/Unigram/issues/2836

**Closed by MarcAnt01** 2023-02-11 14:00 UTC
Labels: needs-triage
