### ISSUE TITLE
Messages are overlapping each other

### ISSUE THREAD

**Issue by lloydo3000** [UnigramDev/Unigram#2376] opened 2021-05-19 01:10 UTC
### Message padding is so large, it overlaps the margins of other messages (when message corner radius is set to 0)

This issue appeared in version 7.7.6247.0:

![image](https://user-images.githubusercontent.com/75959478/118741551-caf8be00-b891-11eb-949c-05c2d9e5b92d.png)

Compare to in previous versions:

![image](https://user-images.githubusercontent.com/75959478/118741824-8a4d7480-b892-11eb-9793-0b9c7cf9ff5f.png)

Message corners set to 0 is a valuable feature for people who don't like the "bubble" appearance or who like the compose bar to sit flush at the bottom of the UI (instead of offset, "floating" in the chat window).

**Comment by FrayxRulez** [comment] 2021-05-19 08:59
Hey, sorry but I'm not able to reproduce the issue. Can you provide some more details?
- Did you change font size in Unigram?
- Did you change font size in Windows?
- What's your screen resolution and system scaling?

**Comment by FrayxRulez** [comment] 2021-05-19 08:59
Also, are you sure that this only happens when messages corner radius is set to zero?

**Comment by lloydo3000** [comment] 2021-05-19 09:22
> * Did you change font size in Unigram?

I think font size is default, set to the third (3/7) notch from the left
> * Did you change font size in Windows?

Windows font size is default
> * What's your screen resolution and system scaling?

Resolution is 2736 × 1824 px, scaling is 200% (Recommended, Surface Pro 7)

> Also, are you sure that this only happens when messages corner radius is set to zero?

Compare these two screenshots taken just now:
![image](https://user-images.githubusercontent.com/75959478/118788601-47fa5680-b8d7-11eb-8250-b0333cf58371.png)
![image](https://user-images.githubusercontent.com/75959478/118788588-46309300-b8d7-11eb-9e11-9353c9a3e09b.png)

**Comment by FrayxRulez** [comment] 2021-05-20 15:10
So, the issue should be fixed already in the out-of-store version of the app, but this will take a while to reach the store.

**Comment by FrayxRulez** [comment] 2021-05-20 15:10
(you can download direct version of the app from t.me/unigramappx, this won't override your current installation)

**Closed by FrayxRulez** 2021-05-20 15:10 UTC
Labels: visual

**Comment by lloydo3000** [comment] 2021-05-20 20:48
Awesome, thank you for the hard work on this great app!
I will wait for the store version to come through, I can ignore it  for a little while. Cheers

**Comment by lloydo3000** [comment] 2021-07-13 13:00
@FrayxRulez was this fix merged and still not in Store version, or did it get forgotten?
