### ISSUE TITLE
Quick log in using QR code UI / layout glitching

### ISSUE THREAD

**Issue by XeZrunner** [UnigramDev/Unigram#1369] opened 2020-03-14 23:47 UTC
[Video demonstrating the issue](https://www.youtube.com/watch?v=uQfRJnasMm4)
[Screenshot demonstrating the issue](https://i.imgur.com/qaoEK4Q.png)

Upon clicking on the **Quick log in using QR code** link, the entire initial start UI reappears. 
Clicking on Start messaging again **shows both the phone number login & QR code login layouts.** After some time, the login page disappears and the start UI reappears again. The issue keeps continuing.

Unlike #1328, as can be seen on video, **I did not touch the proxy settings**.

Unigram version 3.14.2691 from the Microsoft Store
Windows 10 1904 _build 18363.3.720_

**Comment by FrayxRulez** [comment] 2020-04-29 17:28
Duplicate of #1358 and fixed in https://github.com/UnigramDev/Unigram/commit/5bc3f5a969627a33e53fd71eb507624766228ff3

**Closed by FrayxRulez** 2020-04-29 17:28 UTC
Labels: bug
