### ISSUE TITLE
Black screen with minimal options

### ISSUE THREAD

**Issue by JesterSpearmann** [UnigramDev/Unigram#1210] opened 2019-10-08 10:39 UTC
Whenever I install & then try to launch unigram I'm met with this as the interface
None of the options actually do anything and despite a clean install I'm utterly confused as to what is happening with it.

Win10 x64 v1903
![ApplicationFrameHost_obvBfk1t7C](https://user-images.githubusercontent.com/20283165/66389278-bb599800-ea13-11e9-8b76-c950665c93bc.png)

**Comment by AlperOZCAN** [comment] 2019-10-09 11:16
This is known issue. If you have lots of groups, messages or/and chats, at that time Unigram syncs all chat conversations meta data...
Please wait 2-5 minutes for first use. Or close and open again.

**Comment by MarcAnt01** [comment] 2019-10-09 12:08
@AlperOZCAN seems quite unrelated, in that scenario the UI doesn't disappear, at least from my experience

**Comment by AlperOZCAN** [comment] 2019-10-09 12:14
For completely uninstall & install scenarios, i have had this issue too. It solved for me, while i have wait a little for the first use / first opening.
Moreover, my Unigram installed at secondary disk of my laptop. First (main) one is SSD and never have enough space for it. So i moved Unigram to my secondary (Normal 7200 rpm HDD) disk.
Maybe problem occurs from here.

NOTE: These problems came for me when the Unigram supports Desktop Bridge & Win32 type updates.

**Comment by JesterSpearmann** [comment] 2019-10-12 14:18
> This is known issue. If you have lots of groups, messages or/and chats, at that time Unigram syncs all chat conversations meta data...
> Please wait 2-5 minutes for first use. Or close and open again.

I haven't even signed into an account yet
(I can't interact with any of the options, they don't do anything when clicked)
So unless it's pulling directly from my telegram desktop there's something else wrong

**Comment by DarthJahus** [comment] 2019-10-12 16:01
@JesterSpearmann Try to clear data for Unigram (Settings > Apps > Unigram > advanced options > Reset). Or try to uninstall then reinstall it.

**Comment by JesterSpearmann** [comment] 2019-10-14 15:12
> @JesterSpearmann Try to clear data for Unigram (Settings > Apps > Unigram > advanced options > Reset). Or try to uninstall then reinstall it.

I've already done a clean reinstall, none of the options in the menu do anything when clicked on so there's nothing to clear, it's almost as if the package got broken during the install from the MS store

**Comment by FrayxRulez** [comment] 2019-10-30 14:33
Sorry for the late reply on this, but I have no clue about what happens. Is this screen appearing before or after login?

Are you able to reach settings? If yes it would be nice if you could click 10 times on the app version there, set the logs level to Debug or more, close the app, launch it again and then send the logs to me at t.me/FrayxRulez.

**Comment by FrayxRulez** [comment] 2020-02-25 15:03
Well, closing this...

**Comment by JesterSpearmann** [comment] 2020-02-28 03:33
> Sorry for the late reply on this, but I have no clue about what happens. Is this screen appearing before or after login?
> 
> Are you able to reach settings? If yes it would be nice if you could click 10 times on the app version there, set the logs level to Debug or more, close the app, launch it again and then send the logs to me at t.me/FrayxRulez.

I am unable to log in at all, there are no options to add an account,
none of the options actually work when clicked on

**Comment by JesterSpearmann** [comment] 2020-02-28 03:35
> 
> 
> Well, closing this...

It's interesting, I never got a reply to this till today both the messages came through at once

**Comment by FrayxRulez** [comment] 2020-02-28 08:47
You can still write to me on Telegram! This would be really useful to fix the issue.

**Comment by FrayxRulez** [comment] 2020-06-06 21:05
@JesterSpearmann are you using Windows in safe mode or Windows N?

**Comment by JesterSpearmann** [comment] 2020-06-09 06:00
> 
> 
> @JesterSpearmann are you using Windows in safe mode or Windows N?

Nope!

**Comment by FrayxRulez** [comment] 2020-11-18 22:04
I'm pretty sure that the issue was caused by this: https://github.com/tdlib/td/commit/15359488bef5d7266a99b79596c626e051f2f065
Latest version in t.me/unigramappx channel has the fix.

**Closed by FrayxRulez** 2020-11-18 22:04 UTC
Labels: Needs investigation
