### ISSUE TITLE
Edit image option(?)

### ISSUE THREAD

**Issue by ze0ss** [UnigramDev/Unigram#2208] opened 2021-01-05 08:00 UTC
There's no edit and resend images option in the context menu.

![500059200780_179212](https://user-images.githubusercontent.com/56572179/103620793-22893380-4f5a-11eb-9577-029bdceeaec1.jpg)

**Comment by FrayxRulez** [comment] 2021-04-08 18:03
Hi @ze0ss, maybe you can provide a bit more context?

**Comment by ze0ss** [comment] 2021-04-09 04:52
the quick image edit is a new feature [added by telegram](https://telegram.org/blog/voice-chats)

basically you can quickly re-edit and re-send the photo you or anybody else just posted.

**Comment by MarcAnt01** [comment] 2021-04-09 08:44
Hi, it looks like it is a duplicate of #2271

**Closed** 2021-04-09 08:45 UTC

**Comment by ze0ss** [comment] 2021-04-09 13:16
@MarcAnt01 my issue was older smh

**Comment by FrayxRulez** [comment] 2021-04-09 13:17
That’s true, @ze0ss, but Filippo’s is more straight to the point!
