### ISSUE TITLE
Problems with links to bot personalized commands in private

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#737] opened 2018-09-23 10:40 UTC
To reproduce this issue, it's necessary to get in a group with Marie bot and type /rules, after clicking on the button in bot answer, it goes automatically to private chat, where there's a "start" button, after pressing it, it should disappear, but it doesn't

**Comment by FrayxRulez** [comment] 2018-09-23 12:05
Duplicate of #574

**Closed by FrayxRulez** 2018-09-23 12:05 UTC
Labels: enhancement

**Comment by MarcAnt01** [comment] 2018-09-23 12:14
Sorry, didn't think it was correlated with deep linking
