### ISSUE TITLE
Code blocks get wrapped when there's enough width on screen.

### ISSUE THREAD

**Issue by igoralebar** [UnigramDev/Unigram#2377] opened 2021-05-19 06:58 UTC
Official client seems to not have a max message bubble width limit for code blocks, can this be implemented in Unigram?

**Comment by MarcAnt01** [comment] 2021-05-19 08:50
Hello, thanks for your bug report. I'm afraid it's already been reported

**Comment by FrayxRulez** [comment] 2021-05-19 08:52
@MarcAnt01 you literally just linked the same issue...

**Comment by MarcAnt01** [comment] 2021-05-19 08:55
Duplicate of https://github.com/UnigramDev/Unigram/issues/2376

**Comment by FrayxRulez** [comment] 2021-05-19 08:56
It's absolutely unrelated

**Comment by MarcAnt01** [comment] 2021-05-19 08:57
I'm sorry, I have just realized this one is specific for code blocks

**Comment by MarcAnt01** [comment] 2021-06-11 16:05
I'm closing this one, since the other ticket, despite being newer, explains the request in a more straightforward way

**Closed** 2021-06-11 16:04 UTC
