### ISSUE TITLE
Please give out a complete guide on how to build this project

### ISSUE THREAD

**Issue by ReimuNotMoe** [UnigramDev/Unigram#950] opened 2019-01-05 18:48 UTC
I already spent a plenty of days figuring out how to build latest Unigram from sources. And, no luck.

**The most important question is: Where did you get the source code of TDLib 1.3.2?**

I tried every version of Win10 SDK, Template10, FluentEditor, etc. Finally I got a working combination. But still stuck here due to the lack of TDLib 1.3.2.

_**YOU ARE EFFECTIVELY DRIVING AWAY CONTRIBUTORS BY THIS WAY**_

So please **at least** let the community know these things **instead of just closing issues**:

- Correct targeted version and min version of Win10 SDK.
- Correct version of 3rdparty components, such as Template10, FluentEditor, etc.
- How to install 3rdparty components, e.g. from nuget or download&build manually.

Currently the highest buildable version is v1.6.1590. It also contains some misuses of Template10 that need to be fixed by hand.

**Comment by MarcAnt01** [comment] 2019-01-05 18:51
Duplicate of https://github.com/UnigramDev/Unigram/issues/641

**Comment by callummoffat** [comment] 2019-01-05 18:52
The developer collaborates with Telegram, which is how he gets the source for TDLib.

As for the rest, due to a number of crappy clones as well as some other issues, the developer has opted not to offer updated build information, etc.

**Closed by MarcAnt01** 2019-01-05 18:51 UTC

**Comment by ReimuNotMoe** [comment] 2019-01-05 18:58
This is very funny, **as an open source software with GPLv3 license**, why are you afraid of clones?

**Comment by FrayxRulez** [comment] 2019-01-05 19:00
As now Unigram is using a private fork of Template10, and I don’t really have plans to disclose it to the wide public. FluentEditor isn’t really used and you can just remove any reference to it. 

About build instructions: they used to be available in the readme file (check its history). 

If you want to contribute to the project, you can reach me on Telegram (same username as here)

**Comment by MarcAnt01** [comment] 2019-01-05 19:03
@ReimuNotMoe build instructions are available in the wiki, clones violeted licence conditions and Microsoft did nothing to remove them
![screenshot_chrome_20190105-200115](https://user-images.githubusercontent.com/43090263/50728089-e6c9f200-1124-11e9-809b-b0e7663db105.png)

**Comment by SilverBut** [comment] 2019-01-05 20:11
This might be the most interesting joke I will hear in 2019: A software based on **GPLv3** can not be compiled.

According to [GPLv3](https://github.com/UnigramDev/Unigram/blob/develop/LICENSE):

> Our General Public Licenses are designed to make sure that you
have the freedom to distribute copies of free software (and charge for
them if you wish), that you receive source code or can get it if you
want it, that you can change the software or use pieces of it in new
free programs, and that you know you can do these things.

But the close-sourced `TDLib` makes it impossible to distribute the 
original software again for other developers, which means the GPL is
actually violated. 

According to GPL, maybe you can considering:

* Make `TDLib` opensource.
* Remove FluentEditor to make the whole project meets GPL.
* Talk with every contributers and considering changing GPL to add an
extra item to list `TDLib` as an exception.
* Stop development of Unigram and write a new one in clean-room. 
Just make sure you will use some other license other than GPLv3.

**Comment by callummoffat** [comment] 2019-01-05 20:12
They can’t make TDLib open-source, because it’s Telegram’s code. Not Unigram’s.

**Comment by FrayxRulez** [comment] 2019-01-05 20:15
TDLib is open source: https://github.com/tdlib/td

**Comment by FrayxRulez** [comment] 2019-01-05 20:17
Same as FluentEditor: https://github.com/Microsoft/fluent-xaml-theme-editor

**Comment by FrayxRulez** [comment] 2019-01-05 20:18
The fork of Template10 we are using however isn’t, I simply distribute it per request. (To ne honest I’d like to change Unigram license to something more restrictive, but I’m not sure if this is actually possible)

**Comment by jp-weber** [comment] 2019-01-08 19:38
> The fork of Template10 we are using however isn’t, I simply distribute it per request. (To ne honest I’d like to change Unigram license to something more restrictive, but I’m not sure if this is actually possible)
Why is your Template10 fork not public?

**Comment by FrayxRulez** [comment] 2019-01-08 20:00
Because Template10 license doesn’t require publication of forks source code

**Comment by SilverBut** [comment] 2019-01-08 20:49
It's kind of off topic but still a meaningful discussion. Here is my opinion. 

The actual meaning of GPL is: if you distributed your software, you need to let other people able to redistribute the software, and you need to allow any modifications to the version that they redistributed. 

In this case, if no one except for Fela and his/her teammates is using their modification version of Template10, it's generally okay to keep the source closed, even if the Template 10 is GPL (though it isn't). That's because if it is only internally used, we usually do not consider it *being redistributed*. The same rules apply to the Unigram. This is the nature of GPL. 

However once it is distributed (just like Unigram), then you shall let everyone able to redistribute the software with their modified code. Then to make the whole software compilable, the related Template10 written by Fela shall be opensourced, even if it has not been distributed before. 

Of course there are some ways to avoid doing this. Considering how you can use kernel modules which are written in a license other than GPL (like some close source drivers from NVIDIA and Broadcom). By the way, I think one of the reasons of those patented code can not be used in kernel is due to the nature of GPL I mentioned above. 

**This is just my personal opinion.Not sure if 100% right but I believe FSF guys would like to give directions about GPL**. And again, spending time on questions like that is not so meaningful. We could have written another module to replace those private ones instead of researching GPL.
