### ISSUE TITLE
Pressing mouse Backward button while hovering a GIF in GIF panel opens the GIF in a modal layout

### ISSUE THREAD

**Issue by DarthJahus** [UnigramDev/Unigram#1900] opened 2020-07-08 19:32 UTC
If you enter a chat and hover the GIF button, put your mouse cursor on a GIF and press the Backward (mouse4?) button, you effectively come back to chat list, but the GIF you were hovering will open and play above your chat list. Clicking doesn't stop it and you need to restart the app.

Screenshot:
![image](https://user-images.githubusercontent.com/7353366/86961952-fb43dc00-c159-11ea-8b21-50bafe8572e2.png)

**Comment by MarcAnt01** [comment] 2020-07-10 08:18
Duplicate of https://github.com/UnigramDev/Unigram/issues/1864

**Closed by MarcAnt01** 2020-07-10 08:18 UTC
