### ISSUE TITLE
Media files in secret chats get corrupted

### ISSUE THREAD

**Issue by ghost** [UnigramDev/Unigram#2022] opened 2020-09-22 12:36 UTC
ALL media files in secret chats damaged. The application is almost unusable.

Part of pictures deleted. Parts of video filed damaged. If you send a media file then Unigram will damage it. If you receive media file then Unigram will damage it too, 

In simple chats all media files works normally.

After reinstall the app the bug still exists. IMHO, this is very critical bug.

![200108800133_60510](https://user-images.githubusercontent.com/71707728/93882304-b5be9600-fce8-11ea-99ff-2e65c8eea8fd.jpg)

**Comment by FrayxRulez** [comment] 2020-09-22 12:45
What's the client from the other side?

**Comment by delmoster** [comment] 2020-09-22 13:39
Standard Telegram clients for Android. Same bug with multiple Android devices and multiple use accounts. Only in secret chats.

I see damage of PDF files in secret chats in another bug report. IMHO, current version of Unigram destroy all files in secret chat for all users. The application is unsuable. Secret chat is main feature of Unigram. If developer will not fix it ASAP then Unigram can lost most of user base in several days. Everyone will switch to standard desktop application.

**Comment by MarcAnt01** [comment] 2020-09-22 13:47
I understand that the feature is important to you, but secret chats are just one of the features of Unigram and the users base doesn't depend only on that 😅

**Comment by delmoster** [comment] 2020-09-22 18:13
> I understand that the feature is important to you, but secret chats are just one of the features of Unigram and the users base doesn't depend only on that 😅

I disagree. Unigram have ONLY ONE important feature as secret chats for Windows. All another features are not critical or have analogs. Also Unigram is unstable in last builds. Only exclusive secret chat feature keep users. In past I'm Microsoft team leader of Microsoft Office testers. I know where critical bugs in reality. 

This bug can kill Unigram project easily. I see Unigram tester and developers don't understand it.

**Comment by MarcAnt01** [comment] 2020-09-22 18:17
You ≠ all users. Also if there are any bugs, how do you expect to have them fixed if you don't report them?

**Comment by delmoster** [comment] 2020-09-22 18:25
> You ≠ all users. Also if there are any bugs, how do you expect to have them fixed if you don't report them?

You is not expert in testing. It's real true. In Microsoft I have 20 millions users of my application. However more than 99% of posted by professional testers like me. Ordinal users don't understand where real problems of their use cases.

This bug block main critical feature of Unirgram. It's oblivious. You cannot understand it. I know that Unigram testers don't understand where critical use cases. Nightmare quality of Unigram in last builds is not problem of developer. This is bad job of testers. Bad escalation procedures are main problem of this projects. 

Ok. I will deinstall Unigram. Most of users too. Good buy!

**Comment by MarcAnt01** [comment] 2020-09-22 18:27
Sorry, but we try to be welcome to all our users and we don't have any special treatment for "professional testers"

**Comment by FrayxRulez** [comment] 2020-09-22 18:43
@delmoster as I stated in the other ticket, hours ago we were already been looking into a solution. Fixes require time for research, coding, compilation and distribution. 
Telegram engineers found where the problem is located, we should be able to pack and distribute a update soon.

**Comment by Jonathanarielarg** [comment] 2020-09-23 18:40
> @delmoster as I stated in the other ticket, hours ago we were already been looking into a solution. Fixes require time for research, coding, compilation and distribution.
> Telegram engineers found where the problem is located, we should be able to pack and distribute a update soon.


Hi FrayxRulez Can you tell me (estimated)  if the solution to this critical bug will be in "hours", "days", or "weeks" ? just to know if I can wait for the solution or I need to find another way to send files in secret chats. I was wondering if in the meantime I can uninstall unigram 7.0 and install unigram 4.2.

I apreaciate your work.
Thank you very much.


I apreaciate your work.
Thank you very much.

**Comment by FrayxRulez** [comment] 2020-09-23 18:40
The bug was fixed past night by Telegram team and today a update has been released in the Store. 
Please update the app to 7.0 (5346)

**Comment by delmoster** [comment] 2020-09-23 19:45
Thanks! I tested video and pictures files. Everything work perfectly!

**Closed** 2020-10-08 13:10 UTC
Labels: bug, critical
