### ISSUE TITLE
Add Export Chat History

### ISSUE THREAD

**Issue by Elshara** [UnigramDev/Unigram#2771] opened 2022-06-26 12:17 UTC
Telegram desktop has the ability to export things like group members, chat conversation history, and a whole host of other things. Unigram does not. I want to see more statistics for members like, available in the API. The kinds of things you'd see about the first 10 members before you join a private group.

**Comment by MarcAnt01** [comment] 2022-06-26 12:25
Hello, thanks for your feature request, but it is a duplicate

**Comment by MarcAnt01** [comment] 2022-06-26 12:26
Duplicate of https://github.com/UnigramDev/Unigram/issues/1010

**Closed by MarcAnt01** 2022-06-26 12:25 UTC
Labels: needs-triage

**Comment by Elshara** [comment] 2022-06-26 12:57
Oh ok, thanks. I didn't know.
