### ISSUE TITLE
Stickers not loading when ordering them via the @Stickers bot

### ISSUE THREAD

**Issue by RubeensVinicius** [UnigramDev/Unigram#820] opened 2018-10-12 19:20 UTC
If you send the command /ordersticker to the official stickers bot and select the pack, when you click the button to select the sticker, it only loads a list of gray squares.

![image](https://user-images.githubusercontent.com/15078228/46889475-35276780-ce3a-11e8-917b-ea1d79cf5d5e.png)

If you click on one of them, the sticker works, but you kinda have to guess what you are selecting. Using the right click to preview them in full size doesn't work either.

**Comment by FrayxRulez** [comment] 2018-10-21 17:40
I'm marking this as a duplicate of #690.

**Closed by FrayxRulez** 2018-10-21 17:40 UTC
Labels: bug
