### ISSUE TITLE
[Feature Request] Auto translate feature

### ISSUE THREAD

**Issue by kntjsprr** [UnigramDev/Unigram#2907] opened 2022-12-01 22:33 UTC
Now telegram added translate on context menu in [v 4.3.1](https://github.com/telegramdesktop/tdesktop/releases/tag/v4.3.1). It would be better if we don't have to translate each message one by one, or perhaps having the option to select which group chats or channels to have auto translate feature would save a lot of time.

**Comment by FrayxRulez** [comment] 2022-12-02 05:53
@kntjsprr Translations are really expensive, so this can’t be done, otherwise this would get to cost millions of USD per day.

**Comment by MarcAnt01** [comment] 2022-12-02 09:57
Duplicate of https://github.com/UnigramDev/Unigram/issues/2787

**Closed by MarcAnt01** 2022-12-02 09:57 UTC
Labels: needs-triage
