### ISSUE TITLE
Add preview for gifs and autoplay in gif section

### ISSUE THREAD

**Issue by larsschellhas** [UnigramDev/Unigram#669] opened 2018-09-11 13:42 UTC
It would be very nice to know what the content of a gif really is before you send it.
Therefore a preview, e.g. by long-tapping it would be very good.

**Comment by larsschellhas** [comment] 2018-09-11 13:43
Stickers have no preview, too, but that´s covered with #546

**Comment by snargledorf** [comment] 2018-11-06 15:47
I've seen it said before that the reason gif's don't autoplay in the preview is for performance reasons, especially on mobile. See https://github.com/UnigramDev/Unigram/issues/327#issuecomment-312842216

Would it be possible to reduce the framerate of previews to something like 15fps? This might help alleviate performance issues.

Also could limit previews to when the app is running on a PC, since a modern PC shouldn't have any issues playing the gif previews.

**Comment by larsschellhas** [comment] 2018-11-06 17:22
@snargledorf yes, that´s absolutely right, which is why I asked for gif previews as sticker previews are handled right now.

autoplay of gifs in the gif section might be nice, but only if phones could handle it, so I don´t think it will come / isn´t necessary. Though @MarcAnt01 changed my issue title to include that 🙄 

The reduction in fps isn´t that good though, I would say, since it just takes more time and you might not get the right feeling from a gif. Also it´s normally handled by the system now, so might not even be possible.

**Comment by snargledorf** [comment] 2018-11-06 17:41
Another thought.

Could make gifs a two tap/hover click operation. First tap/hover starts preview, second tap/click sends the gif.

Just throwing ideas out there.

**Comment by theswordsmahin** [comment] 2019-04-02 01:18
Just found unigram and was really blown away with the quality, but this is a glaring issue that makes me hesitant to uninstall telegram desktop.

**Comment by MarcAnt01** [comment] 2019-04-02 05:47
@theswordsmahin

**Comment by adrianghc** [comment] 2019-04-21 13:12
If performance on mobile devices is an issue, why not just add a toggle in settings so users can decide if they'd like previews to be enabled (and just leave them off by default on phones)?

**Comment by FrayxRulez** [comment] 2019-04-21 13:13
It isn't just about mobile: gifs playback on PC is going to eat ~20mb of ram for each GIF being played.

**Comment by adrianghc** [comment] 2019-04-21 13:16
I see. Maybe let them play only on hover then, so you could never play more than one at a time? Or add a toggle with a big warning, though I do understand why you may not want that.

**Comment by MarcAnt01** [comment] 2019-04-21 13:19
> I see. Maybe let them play only on hover then, so you could never play more than one at a time? Or add a toggle with a big warning, though I do understand why you may not want that.

That's probably more difficult than solving the problem itself😅

**Comment by adrianghc** [comment] 2019-04-21 13:21
Other suggestion then: Just show a preview of a GIF when clicking on it instead of sending it right away.

**Comment by MarcAnt01** [comment] 2020-05-25 20:23
Gif autoplay added in https://github.com/UnigramDev/Unigram/commit/fb62b7b2d0e5d4545e2b8e304d9add920f611e39

**Comment by adrianghc** [comment] 2020-05-25 20:57
> Gif autoplay added in [fb62b7b](https://github.com/UnigramDev/Unigram/commit/fb62b7b2d0e5d4545e2b8e304d9add920f611e39)

This single change has compelled me to try Unigram once again. It seems to have progressed nicely! When could we expect a new version with this change?

**Comment by FrayxRulez** [comment] 2020-05-25 21:03
@adrianghc you can download betas from https://t.me/unigramappx

**Comment by adrianghc** [comment] 2020-05-25 21:22
> @adrianghc you can download betas from https://t.me/unigramappx

Thank you. I assume I'll have to keep downloading new beta releases manually?

**Comment by FrayxRulez** [comment] 2020-05-25 21:25
> Thank you. I assume I'll have to keep downloading new beta releases manually?

Yes, and updates aren’t guaranteed, but I think that the current stage is pretty good so it makes sense to share it.

**Comment by adrianghc** [comment] 2020-05-25 21:26
> > Thank you. I assume I'll have to keep downloading new beta releases manually?
> 
> Yes, and updates aren’t guaranteed, but I think that the current stage is pretty good so it makes sense to share it.

So if a new release is published in the Store that has a higher version number than my currently installed beta release, I wouldn't get updated?

**Comment by FrayxRulez** [comment] 2020-05-25 21:27
> So if a new release is published in the Store that has a higher version number than my currently installed beta release, I wouldn't get updated?

Mmh I’m not sure about this... You might get it.

**Comment by FrayxRulez** [comment] 2020-05-25 21:28
But I actually meant that beta updates aren’t guaranteed. It isn’t mandatory that I will release any other.

**Comment by adrianghc** [comment] 2020-05-25 21:28
Okay, so this was more of a one-off instead of something you release regularly?

**Comment by FrayxRulez** [comment] 2020-05-25 21:30
> Okay, so this was more of a one-off instead of something you release regularly?

Let’s see 😉

**Comment by FrayxRulez** [comment] 2020-05-26 12:16
I'll close this ticket as autoplay has been added and I'd consider preview duplicate of #1611

**Closed by FrayxRulez** 2020-05-26 12:16 UTC
Labels: missing feature
