### ISSUE TITLE
Pressing ESC while searching issues

### ISSUE THREAD

**Issue by Vas0sky** [UnigramDev/Unigram#1030] opened 2019-03-26 11:34 UTC
While viewing a chat, if I press the search button and then press ESC, unigram exits the current chat without exiting the search mode until I press ESC again or I click anywhere (I can still type in the box and click a search result). The issue is with the hamburger menu (3 lines menu) that appears when I press ESC the first time.

**Comment by MarcAnt01** [comment] 2019-03-26 13:03
Are you talking about chat search or messages search?

**Comment by Vas0sky** [comment] 2019-03-26 15:27
Chat search

**Comment by FrayxRulez** [comment] 2019-03-26 16:34
I can't reproduce/understand this :/ any further info?

**Comment by MarcAnt01** [comment] 2019-03-26 16:35
I think it's a duplicate of the issue of right part going back before left one when going back in chat search, but I cannot find the other issue lmao

**Comment by Vas0sky** [comment] 2019-03-26 23:47
I'll get a short video of the issue tomorrow and send it over telegram channel.

**Comment by MattiaBLX** [comment] 2019-03-27 09:35
@Vas0sky Lol?

**Closed** 2019-03-30 12:38 UTC
Labels: bug
