### ISSUE TITLE
From september 21 - problems with PDF sent in Secret CHATS. unable to open. Error 

### ISSUE THREAD

**Issue by Jonathanarielarg** [UnigramDev/Unigram#2021] opened 2020-09-22 01:35 UTC
I always send pdf in a secret CHAT. Today I saw that the unigram updated. And now some pdfs coulnt open in the other side.

**Comment by delmoster** [comment] 2020-09-22 12:38
Unigram damage ALL files in secret chats.

**Comment by Jonathanarielarg** [comment] 2020-09-22 14:37
> Unigram damage ALL files in secret chats.

Do you know how to downgrade to 4.2 version? I dont know why I have 7.0 version with this bug and I cant send pdf files in secret chats anymore. I want to downgrade to 4.2 again and cancel auto update.

thanks.

**Comment by FrayxRulez** [comment] 2020-09-22 14:40
Closing this as a duplicate of #2022.
No, at the moment there is no way to downgrade to 4.2, but I'm personally investigating in this issue.

**Closed by FrayxRulez** 2020-09-22 14:40 UTC
Labels: bug
