### ISSUE TITLE
Differentiate between chats "Send to…"

### ISSUE THREAD

**Issue by jamoness** [UnigramDev/Unigram#967] opened 2019-01-29 18:17 UTC
Now writing this I'm thinking it may be a OS issue but when you share or forward a message the "Send to…" window (?) doesn't point out which chat is secret and which one is not.

**Comment by MarcAnt01** [comment] 2019-01-29 18:55
Duplicate of https://github.com/UnigramDev/Unigram/issues/889

**Closed by MarcAnt01** 2019-01-29 18:55 UTC
