### ISSUE TITLE
Often Unigram won't show toast push notification 

### ISSUE THREAD

**Issue by Marocco2** [UnigramDev/Unigram#2210] opened 2021-01-06 16:31 UTC
Unigram build 5952
Windows 10 20279

Like title. I notice that unread counter is updating but I don't receive alleged toast notification when I explicitly told so in Telegram and Unigram settings. This behavior is sporadic

**Comment by ultrasound1372** [comment] 2021-01-16 01:59
I've noticed something similar. I get the notifications on my phone but not my computer. I have Unigram on a second virtual desktop where I put social apps that won't minimize to tray. I've actually seen it showing as suspended in the task manager sometimes. This may be the cause. When the app gains focus again, I get the notification, but this isn't ideal.

**Comment by Miskoyu** [comment] 2021-01-21 14:39
I am also not getting toast notifications anymore. I can see with Unigram's live tile that there must be new messages, but no notifications are sent to the action center. 

I noticed some strange behaviour: When I receive another new message on my phone, it suddenly triggers the previous message to pop up as a toast notification on my laptop.

**Comment by joaomoreno** [comment] 2021-02-01 10:23
Same here.

**Comment by MarcAnt01** [comment] 2021-02-01 10:35
> Same here. I've reverted back to using Telegram Desktop for the time being. Too bad.

If you don't close Unigram, but just its window, you shouldn't have such problem tho

**Comment by sukiletxe** [comment] 2021-02-01 10:50
What does "close Unigram but not its window" mean? I often don't get notifications either. It fixes itself after a restart or mysteriously after some time.

**Comment by joaomoreno** [comment] 2021-02-02 08:22
One thing that's interesting: as soon as I open Telegram on my phone, the notification appears almost instantly on Windows via Unigram. 🤔

**Comment by agasoft** [comment] 2021-02-11 16:53
The same, but everything worked perfect a few weeks ago. I am using Unigram for years, aand notifications worked always perfectly until latest build.

**Comment by bassclefstudio** [comment] 2021-02-17 14:05
> One thing that's interesting: as soon as I open Telegram on my phone, the notification appears almost instantly on Windows via Unigram. 🤔

I'm trying to figure out an easy way to reproduce this so I can send screenshots, but I've also noticed that sometimes when I receive a message, the action center icon will light up white (indicating a notification arrived) and the Unigram badge will update itself. A second later, the action center icon disappears. Opening Telegram on my phone then makes the notification show up again, almost as if _reading_ the message causes the notification to show (instead of the other way around, where read messages dismiss themselves). This has been happening frequently enough that I'm pretty sure it's directly connected to when I'm receiving Unigram messages - I'm going to try and collect more concrete evidence of this happening to make sure.

(Windows 10 20H2, Unigram 7.3.5951 x64)

![image](https://user-images.githubusercontent.com/51424093/108214632-609f7880-70fe-11eb-9fd5-a3b5123e906c.png) (the action center icon I'm talking about)

**Comment by Marocco2** [comment] 2021-04-23 09:19
Unigram build 6148
Windows 10 21364

Background toast notifications started to working

**Comment by dpierangeli** [comment] 2021-05-18 08:49
Unigram 6212, windows 20H2. 

I don't use Telegram frequently (maybe 3 o 4 messages a week), so i don't have Unigram opened or set for startup launch.

Same on my Android phone, but when i receive a message on my phone i got the notification, on my pc not.
Background execution permission is enabled.

If i open unigram and close it for maybe an hour/two hours the push notifications are shown.

**Comment by kinopikopapa** [comment] 2021-05-20 12:16
Notifications can only be received if Unigram is on the taskbar.

**Comment by Marocco2** [comment] 2021-06-29 09:21
> 
> 
> Unigram build 6148
> Windows 10 21364
> 
> Background toast notifications started to working

Unigram build 6583
Windows 11 22000 on another PC

Background toast notifications don't work. I assume there is something that could block the OS from receiving push notifications

**Comment by thisisartman** [comment] 2021-06-29 09:23
@Marocco2 Has UG started being adapted to W11? If yes, then I'm excited to see the changes.

**Comment by Marocco2** [comment] 2021-06-29 09:27
> 
> 
> @Marocco2 Has UG started being adapted to W11? If yes, then I'm excited to see the changes.

Yeah, app controls got W11 style, some which blend really nice, others not so much

**Comment by thisisartman** [comment] 2021-06-29 09:28
@Marocco2 Noice... are screenshots available?

**Comment by MarcAnt01** [comment] 2021-06-29 11:19
@thisisartman please keep the discussion on topic

**Comment by thisisartman** [comment] 2021-06-29 11:56
@MarcAnt01 But... I'm asking for screenshots of UG on W11...🥺

**Comment by joaomoreno** [comment] 2021-06-29 11:59
@thisisartman What @MarcAnt01 means is that this issue is about: _Often Unigram won't show toast push notification_. Please stop talking about Windows 11 here, you're just creating noise. Create a new issue if you think seeing screenshots of UG on W11 is an issue.

**Comment by FrayxRulez** [comment] 2021-06-29 12:01
@thisisartman It’s the same as Unigram on win10

**Comment by thisisartman** [comment] 2021-06-29 12:02
@joaomoreno Ah okay. Apologies.

**Comment by thisisartman** [comment] 2021-06-29 12:02
@FrayxRulez Oh okay.

**Comment by FrayxRulez** [comment] 2021-06-30 09:07
> > @Marocco2 Has UG started being adapted to W11? If yes, then I'm excited to see the changes.
> 
> Yeah, app controls got W11 style, some which blend really nice, others not so much

You might want to open a ticket about this, so that we could look together into a solution.

**Comment by iHarryPotter178** [comment] 2021-07-10 17:40
The same for me too. I keep the app open but minimize it. then I don't get toast notifications, sometimes the message counter doesn't change either, when I maximise the app, it loads new messages. frustrating.

**Comment by joaomoreno** [comment] 2021-07-12 13:50
Sorry to say that I've ditched Unigram for the Telegram K web as a PWA. This issue was the main driver for dropping it.

**Comment by iHarryPotter178** [comment] 2021-07-12 13:56
I'll try the K Web..

**Comment by FrayxRulez** [comment] 2021-07-12 13:58
Good idea to use a different app, this issue won’t get fixed any time soon.

**Comment by iHarryPotter178** [comment] 2021-07-12 14:03
Web version doesn't have calling ability yet. gonna stick with Unigram.. Hope it gets fixed soon though.

**Comment by Miskoyu** [comment] 2021-07-31 14:02
Push notifications are working again for me! I uninstalled Unigram some weeks ago to try the new web apps for a while. Last week, I reinstalled Unigram and notifications are suddenly working fine! So maybe a reinstall of Unigram can help?

**Comment by Miskoyu** [comment] 2021-08-01 09:14
Okay, the irony! Immediately after posting that push notifications are working again after I reinstallled Unigram, I noticed that they are not entirely reliable. Some notifications still don't arrive on my notebook. It's progress nonetheless - before, I didn't get any push notifications at all...

**Comment by bond-id** [comment] 2021-08-16 10:47
I've got really interesting information for you folks. 
What I've noticed is that if the priority or alarms only modes in the action center enabled, toast push notifications don't pop up. If you however set focus assist mode to off or increase the priority level of Unigram in the Windows settings, you would probably see toast notifications popping up immediately. For Unigram it can be viewed in _Settings -> Notifications & actions -> [username] (via Unigram) -> Priority of notifications in action center_.

Official Telegram Desktop probably has its own notification toast (because it's written in C++) and so that it doesn't rely on UWP library on making them. Ultimately, that's why it shows up notification push toast regardless of any focus assist mode enabled.

By default Unigram has normal priority level, so understandably native toast notifications don't pop up in the case of enabled priority or alarms only modes.

**Comment by Marocco2** [comment] 2021-08-18 11:17
> 
> 
> I've got really interesting information for you folks.
> What I've noticed is that if the priority or alarms only modes in the action center enabled, toast push notifications don't pop up. If you however set focus assist mode to off or increase the priority level of Unigram in the Windows settings, you would probably see toast notifications popping up immediately. For Unigram it can be viewed in _Settings -> Notifications & actions -> [username] (via Unigram) -> Priority of notifications in action center_.
> 
> Official Telegram Desktop probably has its own toast notifications (because it's written in C++) and so that it doesn't rely on UWP library on making them. Ultimately, that's why it shows up toast push notification regardless of any focus assist mode enabled.
> 
> Unigram has normal priority level by default, so understandably native toast notifications don't pop up in the case of enabled priority or alarms only modes.

Nope, won't fix even if Unigram is set at highest level

**Comment by sceraser** [comment] 2021-11-16 16:39
still cant get any notification after unigram was closed in taskbar
windows11 22000.318
unigram 8.1 build 6643

**Comment by 7HE-W0R1D** [comment] 2021-11-17 18:07
Can't get any notification after unigram was closed
Windows11 22000.346
unigram 8.1 build 6643

**Comment by szymonos** [comment] 2021-11-21 19:32
> still cant get any notification after unigram was closed in taskbar windows11 22000.318 unigram 8.1 build 6643

Same for me. I need to minimize Unigram instead of closing, then I got notifications. I'm pretty sure it was working before.

**Comment by XFox111** [comment] 2021-12-07 08:44
Edition	Windows 11 Pro
Version	21H2
OS build	22000.348
Experience	Windows Feature Experience Pack 1000.22000.348.0

---
Unigram version	8.1 (6643) X64
Source	Microsoft Store

---
Same issue. Notifications only appear when window is minimized and do not appear when it's closed. Re-installation didn't help

Background app permissions are set to "Always" and notifications settings are default

<img width="513" alt="image" src="https://user-images.githubusercontent.com/28831743/144995504-16ca4c3e-e2c6-4ea0-a5d1-091fa58923f7.png">

**Comment by SOI7** [comment] 2022-01-29 13:31
Setting Unigram to show the System Tray icon seems to have fixed it to me

**Comment by MarcAnt01** [comment] 2022-01-29 14:43
Yeah, time to close this

**Closed by MarcAnt01** 2022-01-29 14:43 UTC
Labels: bug

**Comment by LoserFox** [comment] 2022-10-07 14:27
The problem remains
`Version Windows 10 Education Edition
Version 21H2
Installed on 12/2/2021
Operating system version 19044.2006
Experience Windows Feature Experience Pack 120.2212.4180.0
The problem remains`
