### ISSUE TITLE
Fluent Design Reveal effects are missing on controls

### ISSUE THREAD

**Issue by XeZrunner** [UnigramDev/Unigram#2177] opened 2020-12-13 17:52 UTC
There previously used to be Reveal effects on UI controls, such as the chat list or menu items.
In one of the newer versions, they seem to have disappeared. Unsure whether this is intentional.

Context menus retain their Reveal effects.

**Comment by FrayxRulez** [comment] 2021-04-10 14:32
This is actually a duplicate of #1092

**Closed by FrayxRulez** 2021-04-10 14:32 UTC
