### ISSUE TITLE
Emoji pack info in context menu is not displayed correctly

### ISSUE THREAD

**Issue by luccascomvoce** [UnigramDev/Unigram#2840] opened 2022-09-21 03:35 UTC
**Describe the bug**
In any chat, when opening the context menu in a message with custom emoji, the string will not appear in its entirety.

**To Reproduce**
1. Go to a message with custom emojis
2. With the right mouse button, open the context menu
3. At the bottom of the context menu, the string will be cut

**Expected behavior**
The string must be displayed correctly

**Screenshots**
![image_2022-09-21_00-21-52](https://user-images.githubusercontent.com/65538684/191408112-e81569b9-4004-40d5-9b5d-b48150ced34d.jpg)
![image_2022-09-21_00-23-09](https://user-images.githubusercontent.com/65538684/191408135-31c7fc9b-a830-4ee5-8aa5-d052edaed693.jpg)

**Version Info**
 - Unigram: [9.0 7762 x64]
 - Windows: [10 21H2]
 - Ryzen 7 4800H GTX 1650

**Comment by rei-zero246** [comment] 2022-10-09 13:01
Similarly, the reactions are not being displayed correctly occasionally.


![Screenshot 2022-10-09 085333](https://user-images.githubusercontent.com/66904012/194758229-14bf2d57-859d-4fda-9cb4-4ef42ed8b902.png)

![Screenshot 2022-10-09 085404](https://user-images.githubusercontent.com/66904012/194758231-4248f7ee-0e39-45c9-a82c-00539ecbe20f.png)

![Screenshot 2022-10-09 085441](https://user-images.githubusercontent.com/66904012/194758232-9944d59f-7975-49df-b2a9-736187fe9fb1.png)

Unigram 9.0 (7780)

**Comment by MarcAnt01** [comment] 2022-10-09 15:03
I cannot reproduce it any longer in 7780. Closing this, feel free to comment if it keeps happening.

**Closed by MarcAnt01** 2022-10-09 15:03 UTC
Labels: bug, needs-triage

**Comment by MarcAnt01** [comment] 2022-10-09 15:04
@rei-zero246 this is totally unrelated. Please create a new issue for it if there isn't any open issue about it

**Comment by luccascomvoce** [comment] 2022-10-13 09:08
![image](https://user-images.githubusercontent.com/65538684/195554217-b0dea76d-03fb-46f0-b106-60d7b4a954a3.png)
Version 9.0 7796 still breaks the string on Windows 10 21H2

**Comment by luccascomvoce** [comment] 2022-10-13 09:10
@MarcAnt01 Version 9.0 7796 x64 still breaks the string on Windows 10 21H2

![image](https://user-images.githubusercontent.com/65538684/195554863-dbcad4b2-5a7a-4581-a96a-72b036a9c7f3.png)

**Comment by MarcAnt01** [comment] 2022-10-13 14:52
Could you send a link to the given message?
