### ISSUE TITLE
Cannot open Unigram if a window of voice chat is already open

### ISSUE THREAD

**Issue by DanielRios549** [UnigramDev/Unigram#2299] opened 2021-03-29 13:44 UTC
I have experienced a bug, to reproduce it is simple, open Unigram, enter in a voice chat, close Unigram. After that, you'll only be able to open Unigram again if you leave the voice chat.

**Comment by MarcAnt01** [comment] 2021-03-29 14:06
For "Close Unigram" you mean close the main window, right?

**Comment by FrayxRulez** [comment] 2021-03-29 16:09
This can be probably counted as a duplicate of #843.

**Closed by FrayxRulez** 2021-03-29 16:09 UTC

**Comment by DanielRios549** [comment] 2021-03-29 17:07
@MarcAnt01 Right, like this one referenced by @FrayxRulez, I didn't see this issue, but is the same thing
