### ISSUE TITLE
Bot buttons use 90% of available space in landscape mode

### ISSUE THREAD

**Issue by bugada** [UnigramDev/Unigram#290] opened 2017-06-05 19:25 UTC
When there are a lot of bot buttons, using the mobile version in landscape mode, the buttons layer covers almost all the available space, so it's impossible to read messages

**Comment by bugada** [comment] 2017-06-05 19:27
![wp_ss_20170605_0001](https://cloud.githubusercontent.com/assets/4438193/26799382/b3acf924-4a35-11e7-997a-4deb037878ad.png)
Here an example

**Comment by mateiradu** [comment] 2017-06-09 08:17
The bot keyboard uses the same hight of the system keyboard. Also note that Telegram on Android has the same behaviour, see below:

![screenshot_20170609-100445](https://user-images.githubusercontent.com/1713151/26966951-8856f17a-4cfc-11e7-8ce9-dc5ebca6ed2d.png)

Since this is an expected behaviour, I'm closing this issue.

**Comment by bugada** [comment] 2017-06-09 09:27
![wp_ss_20170609_0002](https://user-images.githubusercontent.com/4438193/26969562-7c4b6226-4d06-11e7-8e39-3d9f1ad96362.png)
![wp_ss_20170609_0001](https://user-images.githubusercontent.com/4438193/26969563-7c4ed370-4d06-11e7-8778-94fadc39ea1b.png)

Actually i don't agree: the buttons use a bigger height the kb, but when you open the keyboard everything goes ok. See these pictures and compare to the previous one.

**Comment by mateiradu** [comment] 2017-06-13 15:27
I'm reopening this issue after collecting further data.

In a chat with a bot, the bot commands keyboard height is the same regardless of the device orientation. As a result, in some situations, the bot commands keyboard will occupy all the chat space in landscape. Here is an example, notice the red lines. 

![keyboard_bot](https://user-images.githubusercontent.com/1713151/27090291-1500235e-505d-11e7-88af-fa7dd93f1027.png)

If the typing keyboard is later opened, the bot one will adjust it's height to match the typing one (see below).

![keyboard_steps](https://user-images.githubusercontent.com/1713151/27090329-329b936c-505d-11e7-9027-72e308150eb6.png)

But even so, the height will remain unchanged even after device orientation changes.

The desired behaviour would be to have the bot commands keyboard adjust its size to match the typing keyboard in both orientations so to ensure some chat readability in landscape as well (see below).

![keyboard_qwerty](https://user-images.githubusercontent.com/1713151/27090381-57bec394-505d-11e7-82fa-b8ce1c6fbf66.png)

User configuration:
Unigram build: 0.2.317.0
Windows build: 10.0.15063.297
Device: Lumia 950 XL

Note:
This behaviour was confirmed also with the Mobile Emulator 10.0.15063.0 720p 5 inch.
The bot shown in the screenshot is @lootgamebot.

**Comment by FrayxRulez** [comment] 2017-07-27 18:31
There's no way to know programmatically the keyboard size if it is not currently open, so the app needs to use the last known value (that is a fixed size if the keyboard has never been opened).

**Closed by FrayxRulez** 2017-07-27 18:31 UTC
Labels: bug
