### ISSUE TITLE
Feature: Please add support for background startup without loading Unigram client.

### ISSUE THREAD

**Issue by Jimmy-Blue** [UnigramDev/Unigram#2789] opened 2022-07-17 17:22 UTC
It is quite annoyed for me, as a clean desktop user, to see a program loads up itself in front of my eyes, such as Unigram. Although it always minimizes, is there any option to startup on boot without loading the client foreground, just background and app icon in the system icon tray?

**Comment by MarcAnt01** [comment] 2022-07-17 17:51
Thanks for your feature request, this is already being tracked

**Comment by MarcAnt01** [comment] 2022-07-17 17:52
Duplicate of https://github.com/UnigramDev/Unigram/issues/2689

**Closed by MarcAnt01** 2022-07-17 17:52 UTC
Labels: needs-triage
