### ISSUE TITLE
Still get notifications about pinned messages when they was turned off

### ISSUE THREAD

**Issue by f242** [UnigramDev/Unigram#2172] opened 2020-12-06 11:45 UTC
Still get notifications about pinned messages in group chats when they was turned off in "Notifications and sounds"

7.3 5893 x64

**Comment by Alexminator99** [comment] 2021-07-09 17:47
Still get notifications about pinned messages in group chats when they was turned off in "Notifications and sounds"

7.8 6586 x64

PLS a little more priority on this, it most be very simple to fix. Thks

**Comment by FrayxRulez** [comment] 2022-02-12 17:34
Duplicate of #2622

**Comment by MarcAnt01** [comment] 2023-04-02 11:32
Still not working

**Closed** 2023-04-30 07:53 UTC
Labels: bug

**Comment by FrayxRulez** [comment] 2023-04-30 07:57
TDLib
