### ISSUE TITLE
Display chat name in the title for chats open in a new window

### ISSUE THREAD

**Issue by apopticon** [UnigramDev/Unigram#1943] opened 2020-08-10 17:56 UTC
The number one reason I use Unigram is the ability to open a window for each chat (Shift-Click the chat to open in it's own window). 

**This is a FANTASTIC feature!** Tabbed UI's are miserable on a desktop PC, especially with multiple active chats.

The one issue with this feature is the Window Titles are all the same - The main window has a title of "Unigram". All subsequent windows have a title of "Username - Unigram". When looking at the task bar, all the icons have the same name, and that's not great. Title should reflect the contact / group name.

(Username obfuscated in attached image)
![image](https://user-images.githubusercontent.com/60116359/89814144-b3292800-db10-11ea-9110-b1066093ea04.png)

**Comment by MarcAnt01** [comment] 2020-08-10 17:58
So you would like the chat name there instead of account name?

**Comment by apopticon** [comment] 2020-08-10 17:59
Yes - That would be excellent.

**Comment by FrayxRulez** [comment] 2021-04-10 18:18
Duplicate of #972

**Closed by FrayxRulez** 2021-04-10 18:18 UTC
Labels: enhancement
