### ISSUE TITLE
Change mouse behaviour when hovering on profile pictures

### ISSUE THREAD

**Issue by GameSpeck** [UnigramDev/Unigram#1604] opened 2020-05-15 16:54 UTC
The mouse shouldn't have the click icon (I don't know what it's called) on hovering over the profile picture of any chat because there is nothing to click on it.
Edit: In official app, the mouse does not have that icon, it's normal.

**Comment by MarcAnt01** [comment] 2020-05-15 17:04
Duplicate of https://github.com/UnigramDev/Unigram/issues/1295

**Closed by MarcAnt01** 2020-05-15 17:04 UTC

**Comment by FrayxRulez** [comment] 2020-05-15 17:08
If you click on the profile picture the profile picture will open. Did you even try?
