### ISSUE TITLE
Uploading file in group chat cause an exception

### ISSUE THREAD

**Issue by tng2903** [UnigramDev/Unigram#1228] opened 2019-11-03 14:39 UTC
Frequently: often
Reproduce difficulty: easy
Reproduce step:
 - Open Unigram version 3.12.2605
 - Join a group chat with 2 (or more) participants
 - Share a file (80MB in this case) with a description of 50+ characters long
 - Press OK

Observed result: the file is uploaded, but with an Exception dialog 
![image](https://user-images.githubusercontent.com/1988874/68086825-53fffe00-fe82-11e9-9a9f-2a9274f05df7.png)

**Comment by FrayxRulez** [comment] 2020-02-25 15:05
Duplicate of #1194

**Closed by FrayxRulez** 2020-02-25 15:05 UTC
Labels: bug
