### ISSUE TITLE
Multiple dates in some groups

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#1891] opened 2020-07-03 13:49 UTC
![image](https://user-images.githubusercontent.com/43090263/86475299-b2002080-bd44-11ea-8ab3-a5329beffcf1.png)

**Comment by FrayxRulez** [comment] 2020-09-06 09:48
Duplicate of #lazytofind

**Closed by FrayxRulez** 2020-09-06 09:48 UTC
Labels: bug
