### ISSUE TITLE
Stickers doesn't load (W10 Desktop 18363.657, Unigram 3.14.2691)

### ISSUE THREAD

**Issue by schwarzschun** [UnigramDev/Unigram#1360] opened 2020-03-06 20:02 UTC
Hi, I was trying to fix this by:
1. Using VPN
2. Updating system from 1803 to 1909
3. Using proxy
But it doesn't helped me.
![Безымянный](https://user-images.githubusercontent.com/29358657/76118147-174e3a00-600f-11ea-9c17-a0a822bc3f05.png)

**Comment by MarcAnt01** [comment] 2020-03-06 20:17
Duplicate of https://github.com/UnigramDev/Unigram/issues/1105

**Closed by MarcAnt01** 2020-03-06 20:17 UTC
