### ISSUE TITLE
Can't subscribe to some channels: "Seems this chat doesn't exist".

### ISSUE THREAD

**Issue by Cleversn** [UnigramDev/Unigram#2349] opened 2021-04-26 16:05 UTC
I clicked a link on the Telegram web page, which toke me to https://t.me/jobs_bot. then Windows prompted me to choose an app to open the channel's link. I chose Unigram, but when I opened the link, Unigram presented a dialog box saying "It seems this chat doesn't exist".

Note: I'm not sure of the exact wording in English, as my native language is Portuguese.

This isn't the first time it happens. I was unable to view other channels as well in the past.

**Comment by MarcAnt01** [comment] 2021-04-26 16:09
Hello, this was fixed in https://github.com/UnigramDev/Unigram/commit/eb551a261bffa9ff1aa05bfeb15fa381e0d18f4d

Try to update your Unigram version

**Comment by FrayxRulez** [comment] 2021-04-26 16:10
@MarcAnt01 before closing the issue make sure that the user is not up to date.

**Comment by Cleversn** [comment] 2021-04-26 16:56
OK, it appears that my Unigram had not yet updated automatically. I updated it manually now at Microsoft Store, and I'm able to view the channel now.

Sorry for bothering.

**Comment by Cleversn** [comment] 2021-05-12 01:47
I'm trying to enter the channel below. It displays the channel's name, i.e. "Globasa - multilingual", but on clicking the enter button, that popup appear saying the chat appears not to exist. My Unigram is updated as per the last version on MS Store.
https://t.me/joinchat/NSjHjA-B42X1XjEvdbyzEg

**Comment by FrayxRulez** [comment] 2021-05-21 15:47
Hey, not sure if the fix already reached the store, but it is definitely available in the direct version, so I'm closing this.
(You can download direct from t.me/unigramappx, it won't override your current installation)

**Closed by FrayxRulez** 2021-05-21 15:47 UTC

**Comment by MarcAnt01** [comment] 2021-05-21 16:56
> I'm trying to enter the channel below. It displays the channel's name, i.e. "Globasa - multilingual", but on clicking the enter button, that popup appear saying the chat appears not to exist. My Unigram is updated as per the last version on MS Store.
> https://t.me/joinchat/redacted-not-to-make-it-too-obvious

Not a problem of Unigram, from my iPhone it says "expired link"

**Comment by Aquathing** [comment] 2021-05-21 19:14
It doesn't work because "redacted not to make it too obvious" is not a valid hash :smile:

**Comment by forenta** [comment] 2021-08-29 17:13
Can you say in which version this should be fixed? The issue is closed for months now, the problem still appears in the 7.8 (6586) X64 on my device. Links working if I open them on the Telegram Desktop app.

**Comment by FrayxRulez** [comment] 2021-08-29 17:20
> Can you say in which version this should be fixed? The issue is closed for months now, the problem still appears in the 7.8 (6586) X64 on my device. Links working if I open them on the Telegram Desktop app.

Any example?

**Comment by forenta** [comment] 2021-08-29 17:22
http://t.me/joinchat/AAAAAEPWRCG0Lpb3K1f3Sg

**Comment by MarcAnt01** [comment] 2021-08-29 20:19
I can open this in Unigram 7.9 with no issue

**Comment by forenta** [comment] 2021-08-30 10:09
Ok, thx - so I just have to wait until 7.9 will be released at the Microsoft Store.
