### ISSUE TITLE
Drag & Drop doesn't work

### ISSUE THREAD

**Issue by romanad** [UnigramDev/Unigram#2746] opened 2022-06-07 10:43 UTC
Dear friends,
I've noticed that "Drag & Drop" feature doesn't work. This is crucial for comfortable usage.

**Comment by ggoraa** [comment] 2022-06-07 10:44
@romanad Please specify from where were you drag&dropping, the issue can be on the side of the app, from which items are dragged

**Comment by Aquathing** [comment] 2022-06-07 10:46
Duplicate of #2681.

**Comment by romanad** [comment] 2022-06-07 10:46
> @romanad Please specify from where were you drag&dropping, the issue can be on the side of the app, from which items are dragged

I do drag & drop from windows desktop. It works fine with Telegram web.

**Comment by FrayxRulez** [comment] 2022-06-07 10:47
@romanad Drag and drop depends on Windows UAC and it doesn’t work if you disable it

**Comment by romanad** [comment] 2022-06-07 12:18
> d

Yes, you are absolutely right. Of course, I turned off UAC immediately after installing Windows, because it is unbearable when notifications pop up after each action. 
In all other apps it works without UAC. Is it possible to do the same as everywhere else?

**Comment by Aquathing** [comment] 2022-06-07 12:18
@romanad No

**Closed** 2022-06-07 12:20 UTC

**Comment by FrayxRulez** [comment] 2022-06-07 13:48
@romanad Unfortunately no, Unigram runs in a sandbox environment and this is why it has this requirement, there’s no way for us to change this behavior as it is fully dependent on Microsoft

**Comment by MarcAnt01** [comment] 2022-06-07 16:28
For "annoying notifications" do you mean toast notifications? Because they can be simply disabled from settings

**Comment by romanad** [comment] 2022-06-08 15:10
> @MarcAnt01 No, he means UAC admin notifications
![2022-06-08 18_08_13-User Account Control Settings](https://user-images.githubusercontent.com/26842711/172651958-1bd04ccc-a194-43f4-a1b8-3bb7d990850b.jpg)
I have that configuration set. Does this mean drag&drop blocking?

**Comment by FrayxRulez** [comment] 2022-06-08 15:38
@romanad Exactly

**Comment by romanad** [comment] 2022-06-09 14:19
Thanks for the clarification, I double-checked it and yes indeed, with UAC enabled, drag & drop is also activated. But if you consider that with UAC it is necessary to confirm each action even if you are an Administrator and the fact that drag&drop works fine with the Web version without UAC, then all this does not make sense. I had to uninstall Unigram with tears in my eyes. I hope someday Unigram will have a version or a new program compatible with real life.

You must understand that the current version of Unigram does not support drag & drop, which means it cannot compete with analogues.

P.S. yes, we do understand that individual notifications can be disabled through Winaero, but these efforts are not worth it.

**Comment by electroficator** [comment] 2025-03-04 03:48
Drag n drop is really very important feature. I need to run  original Tg client at the same time instant  only for drag n drop operations!!!

**Comment by makisukurisu** [comment] 2025-03-04 05:17
@electroficator Hi, did you disable UAC? If you did, you need to enable it back, if you didn't, can you give us more details on your issue?
