### ISSUE TITLE
Archived chats messages counter not working when there are a lot of unread chats in the archive

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#1243] opened 2019-11-26 19:42 UTC

**Comment by DarthJahus** [comment] 2019-11-26 19:47
@MarcAnt01 No, please. Having the archive on top of the chat list is already disturbing. Having a counter there would just add more annoyance. The same as the counter on top of filtered chats.

**Comment by MarcAnt01** [comment] 2019-11-26 19:48
> @MarcAnt01 No, please. Having the archive on top of the chat list is already disturbing. Having a counter there would just add more annoyance. The same as the counter on top of filtered chats.

That makes no sense at all, if you are annoyed by it, just hide it

**Comment by FrayxRulez** [comment] 2019-11-26 19:52
Expanded style for Archived chats has the counter already.

**Comment by MarcAnt01** [comment] 2019-11-26 19:55
![image](https://user-images.githubusercontent.com/43090263/69667798-f4ff6480-108e-11ea-89d8-d22bd49624df.png)
@FrayxRulez do you see any counter here?

**Comment by FrayxRulez** [comment] 2019-11-26 19:58
Yes I do?
![image](https://user-images.githubusercontent.com/8152849/69667969-47408580-108f-11ea-8a63-385a66c9d033.jpg)

**Comment by MarcAnt01** [comment] 2019-11-26 20:02
@FrayxRulez I tried changing the theme, but nothing; I cannot see it from the latest version from Microsoft Store

**Comment by FrayxRulez** [comment] 2019-12-27 11:28
I'm still not able to reproduce the issue

**Comment by MarcAnt01** [comment] 2019-12-27 11:29
I think it depends on the Windows version, some other users with my same Windows version can reproduce that

**Comment by FrayxRulez** [comment] 2019-12-27 11:34
I'm quite sure it's just a race condition

**Comment by MarcAnt01** [comment] 2020-02-28 16:39
That has been been fixed somehow

**Comment by MarcAnt01** [comment] 2020-02-28 19:58
It looks like it happens when a lot of chats are unread, will try to provide more information

**Comment by FrayxRulez** [comment] 2020-12-06 11:27
Fixed in https://github.com/UnigramDev/Unigram/commit/e4c02ef8c81b07df882f614c3c975b6b83384554

**Closed by FrayxRulez** 2020-12-06 11:27 UTC
Labels: bug
