### ISSUE TITLE
DO NOT use desktop bridge

### ISSUE THREAD

**Issue by CodeForCSharp** [UnigramDev/Unigram#1354] opened 2020-02-29 16:21 UTC
It will break the container and access all of the files and apps in our computer.
It is not safe!We want a pure UWP app to protect our privacy.

**Comment by MarcAnt01** [comment] 2020-02-29 17:15
Duplicate of https://github.com/UnigramDev/Unigram/issues/1139

**Closed by MarcAnt01** 2020-02-29 17:15 UTC
