### ISSUE TITLE
Integration with people Bar is not working

### ISSUE THREAD

**Issue by sjcostaneto** [UnigramDev/Unigram#429] opened 2017-10-25 00:04 UTC

**Comment by callummoffat** [comment] 2017-10-25 01:29
MyPeople integration was disabled temporarily by @FrayxRulez. The current implementation of MyPeople is buggy as hell, and was causing too many issues. Most significantly, it was filling the Unigram crash logs with errors that cannot be fixed by our community.

Until either we or Microsoft devise a solution and/or workaround for this issue, MyPeople integration for Unigram has been disabled. The trade-off is simply too great.

**Comment by FrayxRulez** [comment] 2017-10-25 14:30
Duplicate of #375

**Closed by FrayxRulez** 2017-10-25 14:30 UTC
