### ISSUE TITLE
No Notification when the app is minimised and closed.

### ISSUE THREAD

**Issue by iHarryPotter178** [UnigramDev/Unigram#2231] opened 2021-02-02 09:00 UTC
I'm using windows 10 20H2 and the latest unigram version 7.3. I don't get notifications when someone sends me a message and the app is minimized or closed. I've turned on background running and the app is set to launch when windows start. sometimes it sents notifications but mostly no notification. 
Best Regards.

**Comment by MarcAnt01** [comment] 2021-02-02 11:03
Hi, thanks for reporting that, we are aware of this issue and we have already a ticket to keep track of this issue. Feel free to comment and add details there

**Comment by MarcAnt01** [comment] 2021-02-02 11:03
Duplicate of https://github.com/UnigramDev/Unigram/issues/2210#issuecomment-771457781

**Closed by MarcAnt01** 2021-02-02 11:03 UTC
