### ISSUE TITLE
Mac support

### ISSUE THREAD

**Issue by TheQuinbox** [UnigramDev/Unigram#2603] opened 2021-12-31 13:31 UTC
As it stands, there are only really two Telegram apps for macOS, both of which are inaccessible with VoiceOver. Is it possible to port Unigram over to macOS?

**Comment by MarcAnt01** [comment] 2021-12-31 14:19
Duplicate of https://github.com/UnigramDev/Unigram/issues/2248

**Closed by MarcAnt01** 2021-12-31 14:19 UTC
