### ISSUE TITLE
Handwriting with pen crashes the app

### ISSUE THREAD

**Issue by cewbdex** [UnigramDev/Unigram#1523] opened 2020-05-06 22:05 UTC
Tap the chat with pen, handwriting panel appears, write a text, click _enter_ on the handwriting panel, the app crashes.
![image](https://user-images.githubusercontent.com/9021297/81233089-5e987d00-8ff6-11ea-8f52-d99b498cdee3.png)
Figure 1: Handwriting panel

**Comment by MarcAnt01** [comment] 2020-05-07 06:25
You should report it to Microsoft, since it happens in very app when you use handwriting. I can confirm this bug, tho

**Comment by MarcAnt01** [comment] 2020-05-07 07:24
@cewbdex looks like Microsoft has fixed the major issue I was reporting in all the apps recently

**Comment by MarcAnt01** [comment] 2020-05-07 07:25
Anyway, I am marking as "needs investigation" since some times the hand writing panel auto-closes and some other times it crashes the whole app

**Comment by FrayxRulez** [comment] 2020-05-07 09:50
The crash seems to happen on UWP side, not sure about how I'm supposed to fix this.

**Comment by ADeltaX** [comment] 2020-05-07 09:53
@FrayxRulez I agree, I have the same issue with other UWP apps as well.

**Comment by MarcAnt01** [comment] 2020-05-07 10:06
@ADeltaX can you tell me which apps?

**Comment by ADeltaX** [comment] 2020-05-07 10:09
MS Store, Search

**Comment by MarcAnt01** [comment] 2020-05-07 10:12
> MS Store, Search

They don't crash for me, but they used to a week ago. Maybe it's a problem related to Surface devices

**Comment by cewbdex** [comment] 2020-05-07 12:36
I own a Lenovo Yoga 730-15ikb with partly working ink screen and I can tell only Unigram crashes for me at the moment, working apps: Maps, Calendar, Store, Search, Alarms and Clock, not sure what else should I test.

**Closed** 2020-10-09 20:43 UTC
Labels: Needs investigation
