### ISSUE TITLE
OK Button

### ISSUE THREAD

**Issue by sebahabu** [UnigramDev/Unigram#2257] opened 2021-02-25 09:25 UTC
if you want to plan a message in a bright them there is a OK Button down on the left side below hours and an abort button on the right side below minutes. The Problem, There is no Text on that button so Users will only find it by luck or instinct...

https://www.evernote.com/shard/s265/sh/7780e69c-fadb-8b51-36d8-e6bd6d1d0896/dfa13cac073bc909d578c1f11639c5ca

**Comment by MarcAnt01** [comment] 2021-02-25 09:34
Hello @sebahabu thanks for your bug report, we already have a ticket to keep track of this

**Comment by MarcAnt01** [comment] 2021-02-25 09:34
Duplicate of https://github.com/UnigramDev/Unigram/issues/2195

**Closed by MarcAnt01** 2021-02-25 09:34 UTC
