### ISSUE TITLE
Unneeded padding for some pages in settings

### ISSUE THREAD

**Issue by makisukurisu** [UnigramDev/Unigram#2591] opened 2021-12-22 19:42 UTC
**Describe the bug**
https://t.me/unigraminsiders/383311?single
As shown in message ⬆️ and in section "Screenshots" two pages in settings have padding on top, which may make it hard to find needed elements.

Besides one shown in message there is also Privacy->Two-Step Authentication. (When not set)

**To Reproduce**
1. Enter one of two screens
2. See error

**Expected behavior**
Don't (show padding on those pages)

**Screenshots**
![image](https://user-images.githubusercontent.com/49622129/147146237-e4175e53-ae83-4a41-99ef-c68d579a6ed7.png)

**Version Info**
 - Unigram: v8.3 6814 x64 Direct
 - Windows: 11 21H2

**Additional context**
Seems strange, but only these two do this. (I checked most or all of screens in settings)

**Comment by FrayxRulez** [comment] 2022-09-04 14:27
Duplicate of #2418

**Closed by FrayxRulez** 2022-09-04 14:27 UTC
Labels: visual
