### ISSUE TITLE
Add icon of secret chat when fordwarding message

### ISSUE THREAD

**Issue by Aokromes** [UnigramDev/Unigram#2909] opened 2022-12-02 16:07 UTC
when fwarding i have one contact with secret chat on 2 devices and a non secret chat, idk witch of the 3 is a secret chat, can you add lock icon there? :)

**Comment by MarcAnt01** [comment] 2022-12-05 15:15
Thanks for opening this ticket, but there's already a similar ticket

**Comment by MarcAnt01** [comment] 2022-12-05 15:16
Duplicate of https://github.com/UnigramDev/Unigram/issues/889

**Comment by Aokromes** [comment] 2022-12-05 17:46
oh i opened because fela told me xd

**Closed** 2022-12-05 17:46 UTC
Labels: enhancement, visual
