### ISSUE TITLE
Labels in Clear Cache list are too close to the check boxes

### ISSUE THREAD

**Issue by DarthJahus** [UnigramDev/Unigram#1590] opened 2020-05-13 11:49 UTC
Version: 3.15.4756

Screenshot:

![image](https://user-images.githubusercontent.com/7353366/81808770-1c040280-9518-11ea-832d-fa42a961e1d3.png)

**Comment by FrayxRulez** [comment] 2020-05-14 05:54
Hello, sorry I asked you to open this ticket but it’s actually a duplicate of #1434

**Closed by FrayxRulez** 2020-05-14 05:54 UTC
Labels: bug

**Comment by MarcAnt01** [comment] 2020-05-14 07:35
![image](https://user-images.githubusercontent.com/43090263/81906235-3bf1ff80-95c6-11ea-85e7-8bf80dd10285.png)
