### ISSUE TITLE
[UI] Doesn't display current language correctly

### ISSUE THREAD

**Issue by Sominemo** [UnigramDev/Unigram#1862] opened 2020-06-23 07:36 UTC
The selection in language menu always points to first item
![image](https://user-images.githubusercontent.com/19842935/85374373-5b713600-b53d-11ea-9c98-bcab481ce851.png)

**Comment by MarcAnt01** [comment] 2020-06-23 08:00
Hi, thanks for the report, but this bug is known

**Comment by MarcAnt01** [comment] 2020-06-23 08:00
Duplicate of https://github.com/UnigramDev/Unigram/issues/1249

**Closed by MarcAnt01** 2020-06-23 08:00 UTC
