### ISSUE TITLE
individual chats are updated, while others are not

### ISSUE THREAD

**Issue by larsschellhas** [UnigramDev/Unigram#183] opened 2017-02-26 14:13 UTC
When I open a Chat it becomes updated with the new Messages.
When I go back to the chatslist the previously opened Shows the newest message received until this Point. 
But other Chats are not updated, are not showing the newest message or even that there is a new message until they are opened (could be related to #175 ). The notifications for the new Messages arrived normally.

**Comment by FrayxRulez** [comment] 2017-06-25 10:25
Can I consider this a duplicate of #71?

**Closed by FrayxRulez** 2017-06-25 10:25 UTC
Labels: bug
