### ISSUE TITLE
Manually typed slash (/) commands send the first command in the list instead

### ISSUE THREAD

**Issue by kurmachu** [UnigramDev/Unigram#2488] opened 2021-08-02 01:38 UTC
**Describe the bug**
Typing a slash (/) command manually results in the first command in the list reported by the bot being sent, not the command actually typed. This does not happen if you press space or type anything else after, essentially this only happens when the slash command list is open.

**To Reproduce**
1. Go to any bot that reports slash commands
2. Type / followed by any text (without a space or separation)
3. Press send

**Expected behavior**
The message actually typed into the message box should be sent

**Screenshots**
https://user-images.githubusercontent.com/31492625/127793047-80da5376-c0a7-4e33-aaa2-743b1f141feb.mp4

**Version Info**
 - Unigram: 7.8 (6586) X64
 - Windows: 21H2 (build 22000.100) (11)

**Comment by sukiletxe** [comment] 2021-08-02 06:54
Duplicate of #2486. It's been fixed according to the commit log.

**Closed** 2021-12-01 13:08 UTC
Labels: bug, needs-triage
