### ISSUE TITLE
bug in qrcode login

### ISSUE THREAD

**Issue by behroozbc** [UnigramDev/Unigram#1453] opened 2020-04-28 12:29 UTC
hi 
i want to login with qr code but i get this page 

![image](https://user-images.githubusercontent.com/20381616/80487164-9c9bfe00-8971-11ea-865f-b4d3c3e4d859.png)

**Comment by MarcAnt01** [comment] 2020-04-28 12:32
Duplicate of https://github.com/UnigramDev/Unigram/issues/1358

**Closed by MarcAnt01** 2020-04-28 12:32 UTC
