### ISSUE TITLE
While pasting or editing, the message is often hidden

### ISSUE THREAD

**Issue by bugada** [UnigramDev/Unigram#359] opened 2017-08-08 16:23 UTC
Paste or edit a long message: often the message you're editing is hidden (see picture). If you press the backspace one line appears, if you scroll a bit the whole message appears.

![wp_ss_20170808_0001](https://user-images.githubusercontent.com/4438193/29082678-858ace96-7c66-11e7-8e67-598fc1a2cc1b.png)

Using Unigram 0.5.575
Windows mobile: 10.0.15063.483

**Comment by FrayxRulez** [comment] 2017-12-24 22:24
I'm closing this because the issue is more likely on the system rather than on the app.

Still, if you send me a way to reproduce this I might try to check what's going on.

**Closed by FrayxRulez** 2017-12-24 22:24 UTC
Labels: bug
