### ISSUE TITLE
Some GIFs are displayed incorrectly on Windows on ARM

### ISSUE THREAD

**Issue by TheCheshireMan** [UnigramDev/Unigram#2822] opened 2022-08-31 10:55 UTC
**Describe the bug**
Some GIFS are displayed incorrectly on my device (Xiaomi Book S).

**To Reproduce**
1. Open Unigram
2. Open the GIF panel
3. Search for a GIF. Some of them look corrupted.

**Expected behavior**
GIFs are displayed correctly.

**Screenshots**
![immagine](https://user-images.githubusercontent.com/13486396/187661434-55c432fc-b864-4b0e-add1-0bf9d2e15aa1.png)

**Version Info**
 - Unigram: 8.9 (7616) arm64
 - Windows: 11 Home 21H2 build 22000.918, all updates installed.

**Additional context**
I am using Unigram on a Windows on ARM tablet running Snapdragon 8cx gen 2, which has an Adreno 685 GPU.
HEVC extension is installed from Microsoft Store, as well as the AV1 extension.
I tried using  Windows 11's "graphics settings" to set Unigram to either "energy saving" or "performance" mode, didn't work.

**Comment by FrayxRulez** [comment] 2022-08-31 10:59
I believe that this is a duplicate, but I can't find the "original" ticket now.
Unigram doesn't use Media Foundation for GIFs playback, as it would be too slow and heavy to initialize every time, instead the app uses FFmpeg.
This said, I'm not really sure about how to work on this ticket, as I have no way to test on a ARM64 device.

**Comment by TheCheshireMan** [comment] 2022-08-31 12:37
> 

Sorry if it is a duplicate. I could not find anything similar by searching for "gif" in issues.

@FrayxRulez Would I be able to help with testing? Say, by installing experimental builds to see if the problem gets solved?

**Comment by gus33000** [comment] 2022-08-31 14:49
What version of the Qualcomm Adreno 685 GPU Driver are you currently using? This issue should be fixed in at least version 1.0.1780.0 (or higher). If it's already this one or higher, might be an entirely different problem.

**Comment by TheCheshireMan** [comment] 2022-08-31 14:59
> What version of the Qualcomm Adreno 685 GPU Driver are you currently using? This issue should be fixed in at least version 1.0.1780.0 (or higher). If it's already this one or higher, might be an entirely different problem.
> 
> You may have to ask your OEM for driver updates in that regard

Driver version 27.20.1720.0 published 13/02/2022. I could not find a more updated driver in Windows Update, in Device Manager or the internet.

**Comment by FrayxRulez** [comment] 2022-09-09 21:28
Anyhow this is a duplicate of #2805

**Closed by FrayxRulez** 2022-09-09 21:28 UTC
Labels: bug
