### ISSUE TITLE
Improve scaling for small photos with attached captions

### ISSUE THREAD

**Issue by tissole** [UnigramDev/Unigram#2877] opened 2022-10-21 08:43 UTC
Captions attached to small photos had a weird aspect ratio, this was till recently the default aspect in the official client too. But recently they improved it, and now it looks much better. This is how it looks now in Unigram:

![Unigram](https://user-images.githubusercontent.com/78413495/197151943-8d6bd5d7-a16d-45c1-91a8-bd43a441465f.png)

And this is how it looks on official client:

![Telegram](https://user-images.githubusercontent.com/78413495/197152789-11c57ee4-9959-4972-946e-d4acb6df4164.png)

**Comment by tissole** [comment] 2022-10-21 08:58
I don't think this is a bug, they didn't treat it like a bug in the official client, it was a [feature request ](https://github.com/telegramdesktop/tdesktop/issues/25061)

**Comment by FrayxRulez** [comment] 2022-12-05 12:35
Quite sure that there's another ticket about this but I can't find it now...

**Comment by MarcAnt01** [comment] 2022-12-05 12:37
Duplicate of https://github.com/UnigramDev/Unigram/issues/1784

**Closed by MarcAnt01** 2022-12-05 12:37 UTC
Labels: visual, prio:low
