### ISSUE TITLE
Person's profile doesn't open when clicked in recent actions

### ISSUE THREAD

**Issue by GameSpeck** [UnigramDev/Unigram#1506] opened 2020-05-03 14:44 UTC
![image](https://user-images.githubusercontent.com/43648146/80917126-9b584000-8d7a-11ea-8fa8-5c15a28c6f67.png)
Clicking someone's name should open his profile but it doesn't

**Comment by MarcAnt01** [comment] 2020-05-03 17:07
Duplicate of https://github.com/UnigramDev/Unigram/issues/638

**Comment by MarcAnt01** [comment] 2020-05-03 17:08
Please check all the issues before creating one, it’s not the first time

**Closed by MarcAnt01** 2020-05-03 17:07 UTC
