### ISSUE TITLE
Quiz answers explanation takes too much space

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#1427] opened 2020-04-24 17:56 UTC
![image](https://user-images.githubusercontent.com/43090263/80242331-80444c80-8665-11ea-896c-e16c48d36e8f.png)

**Comment by FrayxRulez** [comment] 2020-04-24 17:57
This is a bug of Microsoft.UI.Xaml 2.3. Not sure if the issue is fixed in 2.4, as it is still in beta.

**Closed by FrayxRulez** 2020-04-24 17:57 UTC
Labels: bug

**Comment by MarcAnt01** [comment] 2020-04-24 18:02
![image](https://user-images.githubusercontent.com/43090263/80242933-8129ae00-8666-11ea-9c46-21294ce6c19f.png)

**Comment by MarcAnt01** [comment] 2020-04-24 18:02
@FrayxRulez why is this one all right?

**Comment by FrayxRulez** [comment] 2020-04-24 18:08
Why users always act as if developers lie to them to not fix bugs?

**Comment by MarcAnt01** [comment] 2020-04-24 18:15
> Why users always act as if developers lie to them to not fix bugs?

I haven't blamed you, just asked why it affects just some elements
