### ISSUE TITLE
Finished audio message cannot be replay back

### ISSUE THREAD

**Issue by SeanTolstoyevski** [UnigramDev/Unigram#2288] opened 2021-03-20 20:04 UTC
1. Play a audio message  in any chat.
2. Play it again when the message is finished.

Nothing happens.

version: Unigram 7.5 (5972) X64

**Comment by SeanTolstoyevski** [comment] 2021-03-20 20:06
And the automatic audio message switching doesn't work either.

**Comment by sukiletxe** [comment] 2021-03-20 20:29
Partially duplicate of #2279

**Comment by MarcAnt01** [comment] 2021-03-20 21:07
Thanks for your report, but we already have two tickets to keep track of that

**Comment by MarcAnt01** [comment] 2021-03-20 21:07
Duplicate of https://github.com/UnigramDev/Unigram/issues/2279

**Comment by MarcAnt01** [comment] 2021-03-20 21:07
Duplicate of https://github.com/UnigramDev/Unigram/issues/2278

**Closed by MarcAnt01** 2021-03-20 21:07 UTC
