### ISSUE TITLE
Sometimes photo in message can't load

### ISSUE THREAD

**Issue by Luminarcy** [UnigramDev/Unigram#1269] opened 2019-12-17 08:44 UTC
Reopening app helps, but its kinda annoying

Download button on second photo does nothing
![image](https://user-images.githubusercontent.com/42573485/70979268-6ba5e580-20c2-11ea-9f8e-8663a94b3880.png)

**Comment by MarcAnt01** [comment] 2019-12-17 09:24
Duplicate of #1156

**Closed by MarcAnt01** 2019-12-17 09:24 UTC
