### ISSUE TITLE
Make "Open stickers panel on pointer hover" optional

### ISSUE THREAD

**Issue by JensMertelmeyer** [UnigramDev/Unigram#918] opened 2018-12-01 20:35 UTC
I hope this does come across in the wrong way. 

I'm sure the change introduced with https://github.com/UnigramDev/Unigram/commit/4a86e628a3d0db6a94961cf9c77584acfe0b1dbd had good reasons and many people are happy with it. However, I personally find it very distracting as I accidently open the sticker panel all the time without actually clicking anything. The sticker panel is huge and covers almost the entire window (when not full screen). Moreover, you can not manually close it - You will have to move the mouse away and wait for it to disappear again.

While I personally would like to see this change reverted, the best option is probably making this behaviour optional to keep the best of both worlds.

Many thanks for your time.

**Comment by MarcAnt01** [comment] 2018-12-01 20:36
Duplicate of https://github.com/UnigramDev/Unigram/issues/916

**Comment by MarcAnt01** [comment] 2018-12-01 20:37
Duplicate of https://github.com/UnigramDev/Unigram/issues/916

**Comment by MarcAnt01** [comment] 2018-12-01 20:38
Sorry for marking, but I hadn't read well, at the moment the implementation is the same as Telegram Desktop

**Comment by MarcAnt01** [comment] 2020-01-18 13:00
I'd suggest to automatically disable this behaviour when the window is resized

**Comment by MarcAnt01** [comment] 2020-05-12 09:31
That won't happen any longer (might take a bit to reach the version in the store)
![image](https://user-images.githubusercontent.com/43090263/81667766-fad1e200-9443-11ea-80ae-0115ca879cce.png)

**Closed** 2022-08-29 14:54 UTC
Labels: feature request
