### ISSUE TITLE
Auto-scrolling using mouse wheel 

### ISSUE THREAD

**Issue by deadwalker10s** [UnigramDev/Unigram#2128] opened 2020-11-09 20:43 UTC
Steps to reproduce

    1.open window with long conversation history
    2.middle click on chat area
    3.cursor icon doesn't register middle button to change into auto-scroll mode
    4.move mouse up or down to scroll
    5.nothing happens

Expected behaviour

Simulate similar behaviour as web browsers (Firefox, Opera, Chrome, etc.)

    1.open long chat history
    2.middle click on conversation history area to change into auto-scroll mode
    3.change standard mouse cursor/pointer icon to auto-scroll icon
    (e.g.https://www.iconfinder.com/icons/115013/down_scroll_up_icon))
    4.move mouse up or down to scroll through chat history
    5.middle click to exit auto-scroll mode
    6.change auto-scroll icon back to standard mouse cursor/pointer icon

Actual behaviour

No response to middle click. Need to use up/down key, page up/down, or use vertical scroll bar to go through chat history.
Configuration

Operating system:
Windows 10 home 64

Used theme:
Dark

**Comment by MarcAnt01** [comment] 2020-11-24 18:27
I actual found this old ticket keeping track of the same request, marking as duplicate

**Comment by MarcAnt01** [comment] 2020-11-24 18:27
Duplicate of https://github.com/UnigramDev/Unigram/issues/876

**Closed by MarcAnt01** 2020-11-24 18:27 UTC
Labels: feature request
