### ISSUE TITLE
Issue with SECRET CHATS using unigram. (SECRET CHAT CANCELED)

### ISSUE THREAD

**Issue by Jonathanarielarg** [UnigramDev/Unigram#2451] opened 2021-07-01 15:38 UTC
when I start a secret chat and unigram is open, the secret chat show as canceled. 
Few seconds after I start the secret chat that happend. No time even to write something.
When I close unigram (log off) the secret chat works properly in the android device. The problem stat again when I sing in to the account from unigram.

**Comment by FrayxRulez** [comment] 2021-07-01 15:40
This is by design: secret chats are automatically accepted by the last active client

**Comment by Jonathanarielarg** [comment] 2021-07-01 16:24
> This is by design: secret chats are automatically accepted by the last active client

Sorry FrayxRulez, I dont understand. I cannot use secrets chats. If I have telegram in my android and unigram in my w10, how can I open a secret chat with my contact? Now with this 2 clients opened when I start a secret chat the secret chat is canceled inmediatly without time to start de conversation. With is the way to use the secret chat in unigram?

**Comment by Jonathanarielarg** [comment] 2021-07-01 20:43
more details, the problem with secret chats that are canceled inmediatly is happend in versión unigram 7.8 6567
In previous version worked ok. This issue is new for me. Since 2 years sending secret chats from unigram.

**Comment by kolomenkin** [comment] 2021-07-01 21:08
I have the same problem:

## Reproduction

- Start secret chat. I'm using windows desktop version 7.8 (6567) x64
- Confirm you are sure to create secret chat
- After few seconds waiting for remote client chat is created and immediately marked as "Secret chart cancelled"

**Note1:** If other person is opening secret chat with me it behaves similar - chat is created and immediately marked as cancelled for both sides of the chat.

**Note2:** Pre-existing secret chats are still working fine. The problem is only with creating new secret chats.

Few days ago it was working fine (i'm not sure when it was updated for me).
And today (12 hours ago I found it totally broken).

**Comment by FrayxRulez** [comment] 2021-07-01 21:09
Is it canceled on both android and Unigram? Only a single device can accept a secret chats at a time

**Comment by FrayxRulez** [comment] 2021-07-01 21:12
What happens if Android client is out of network, for example, in flight mode? Is the secret chat successfully created or is canceled on both clients? If the chat is still canceled, what is exact version of another client, creating the secret chat?

**Comment by kolomenkin** [comment] 2021-07-01 21:16
1. I'm moving Android to flight mode.
2. Ask desktop Unigram to create secret chat
3. It is created as cancelled
4. After I add internet to Android it does not appear on adroid. And secret chat never appeared on both primary telegram clients before, Only one of them knows about the chat. It was before and it did not change.

**Comment by FrayxRulez** [comment] 2021-07-01 21:20
I need the version on the other side

**Comment by kolomenkin** [comment] 2021-07-01 21:25
Ok. The following version are incompatible:

- Telegram Android 7.8.0 (2360) arm64-v8a
- Unigram 7.8 (6567) x64 (Windows desktop)

No matter who is initiating the secret chat. The result is the same,

**Comment by FrayxRulez** [comment] 2021-07-02 09:55
Thanks, this was fixed in https://github.com/tdlib/td/commit/bed2650b4c52b54a009a2df5d40be16497467f59

**Closed by FrayxRulez** 2021-07-02 09:55 UTC

**Comment by kolomenkin** [comment] 2021-07-02 10:11
@FrayxRulez , could you tell approx. the date when this fix will get released?
(in an hours? days? weeks?)

As for me it looks like a blocking issue in one of the corner features of the product.
And it is worth releasing a hotfix for this case.

**Comment by Jonathanarielarg** [comment] 2021-07-02 13:38
thank you @FrayxRulez and @kolomenkin We are wainting the update with the fix. Could you estimate when it will be avaible to donwload and how we can update the unigram app?
Best regards

**Comment by sgtredrock** [comment] 2021-07-06 15:14
The same '"Secret Chat Cancelled" message occurs for me trying to start a secret chat with a Telegram Client user on Iphone 12 IOS. I've had to switch to Signal...which I do not like but at least the Secret Chat works between Signal PC Desktop client and Signal Iphone 12 IOS. When can a HOTFIX be delivered through the MS App Store ASAP?

Thank you.

**Comment by sgtredrock** [comment] 2021-07-08 13:00
The issue is fixed. Just installed the latest version from the Windows Store and I was able to create a secret chat. Thank you to the developers!
