### ISSUE TITLE
passlock dont work when come form share ui

### ISSUE THREAD

**Issue by behroozbc** [UnigramDev/Unigram#1362] opened 2020-03-09 12:40 UTC
![2020-03-09-160159](https://user-images.githubusercontent.com/20381616/76213715-8189f900-6220-11ea-9615-9b4208b7127b.gif)

**Comment by MarcAnt01** [comment] 2020-03-10 13:44
Duplicate of https://github.com/UnigramDev/Unigram/issues/440

**Closed by MarcAnt01** 2020-03-10 13:44 UTC
