### ISSUE TITLE
Export chats

### ISSUE THREAD

**Issue by fclorenzo** [UnigramDev/Unigram#2920] opened 2022-12-19 07:03 UTC
Hello. I would like to know if it is possible to add the function to export chats in unigram, because it seems that only telegram desktop can do that. As unigram is the only accessible telegram client on windows (at least as far as I know), I can't export chats. If its not possible to do that, why?

**Comment by MarcAnt01** [comment] 2022-12-19 11:20
Unfortunately this is not possible and is not going to be added any time soon

**Comment by MarcAnt01** [comment] 2022-12-19 11:20
Duplicate of https://github.com/UnigramDev/Unigram/issues/1010

**Closed by MarcAnt01** 2022-12-19 11:20 UTC
