### ISSUE TITLE
Video messages (circles) aren't synchronized with audio

### ISSUE THREAD

**Issue by wdoborschuk** [UnigramDev/Unigram#2815] opened 2022-08-28 16:00 UTC
**Describe the bug**
When start someones circle video message audio start from the beginning, but video doesn't and continues from last frame of autoplay.

**To Reproduce**
1. Go to any group, channel or personal chat
2. Click on video message (circle)
4. See error (circle-message goes from last frame of autostart, audio starts from the beginning)

**Expected behavior**
Video messages (circles) are synchronized with audio stream.

**Version Info**
 - Unigram: 8.9 (7574) X64
 - Windows: 11 ver. 22H2, build 22621.382

**Comment by MarcAnt01** [comment] 2022-08-28 17:39
Thanks for reporting, I've noticed we already have a ticket to keep track of this

**Comment by MarcAnt01** [comment] 2022-08-28 17:39
Duplicate of https://github.com/UnigramDev/Unigram/issues/2247

**Closed by MarcAnt01** 2022-08-28 17:39 UTC
Labels: bug
