### ISSUE TITLE
Adding to group without rights does not tell anything

### ISSUE THREAD

**Issue by xperiandri** [UnigramDev/Unigram#756] opened 2018-09-27 15:43 UTC
If I try to add a user to the group that I don't have rights to add to, then confirmation dialog appears, but nothing happens after it

**Comment by FrayxRulez** [comment] 2018-09-27 17:19
Duplicate of #649 (if this specific case is missing in the ticket, please add it)

**Closed by FrayxRulez** 2018-09-27 17:19 UTC
Labels: duplicate
