### ISSUE TITLE
Edit group picture: Preview does not update before saving

### ISSUE THREAD

**Issue by hihain** [UnigramDev/Unigram#1949] opened 2020-08-15 10:09 UTC
* Open a group
* Click on edit
* Change the group picture
=> No visible change to the UI, so users are unsure if the change of group picture will be saved in the next step
* Save group settings (Check-Button on the right)
=> updated picture (saved and shown everywhere)

Same for deleting the group picture.

![image](https://user-images.githubusercontent.com/1473059/90310240-2d322600-def0-11ea-89bc-f1e97a82fa1d.png)

**Comment by MarcAnt01** [comment] 2020-08-15 11:37
Duplicate of https://github.com/UnigramDev/Unigram/issues/1062

**Closed by MarcAnt01** 2020-08-15 11:37 UTC
