### ISSUE TITLE
Problem with Profile pictures swiping

### ISSUE THREAD

**Issue by morenj96** [UnigramDev/Unigram#862] opened 2018-10-31 03:05 UTC
I can swipe left or right on users profile pictures, when they have one picture only on their profile.
I'll see the first picture as second or third picture.
But number of picture is 1/1 in all pictures.

**Comment by morenj96** [comment] 2018-10-31 03:09
@morenj96 Same problem exists Also with latest shared picture in a group. (I can swipe left when i see the latest picture, after swipe I see same picture.)

**Comment by FrayxRulez** [comment] 2018-10-31 14:47
Duplicate of #863

**Closed by FrayxRulez** 2018-10-31 14:47 UTC
Labels: bug
