### ISSUE TITLE
New sticker panel is always opened in channels

### ISSUE THREAD

**Issue by Dum4G** [UnigramDev/Unigram#1657] opened 2020-05-26 14:28 UTC
It remains opened even in public channels where the user doesn't have admin rights

Unigram_4.0.4915.0_x64
![image](https://user-images.githubusercontent.com/5430116/82912929-550b9080-9f76-11ea-98cf-ebc469f06191.png)

**Comment by MarcAnt01** [comment] 2020-05-26 14:33
Hi, that's a duplicate of https://github.com/UnigramDev/Unigram/issues/1632

**Closed by MarcAnt01** 2020-05-26 14:33 UTC
