### ISSUE TITLE
Show the number of votes for each option

### ISSUE THREAD

**Issue by GameSpeck** [UnigramDev/Unigram#1482] opened 2020-05-01 12:37 UTC
Just like this:
![image](https://user-images.githubusercontent.com/43648146/80805835-aa05f200-8bd6-11ea-89d4-4528b9843af5.png)

**Comment by MarcAnt01** [comment] 2020-05-01 12:39
Duplicate of https://github.com/UnigramDev/Unigram/issues/1327

**Closed by MarcAnt01** 2020-05-01 12:39 UTC
