### ISSUE TITLE
Same notifications are shown mutiple times

### ISSUE THREAD

**Issue by CornyjK** [UnigramDev/Unigram#1439] opened 2020-04-27 08:28 UTC
Does not happen to me right now, but sometimes multiple notifications are shown for a single message, unable to reproduce.

**Comment by MarcAnt01** [comment] 2020-04-27 09:11
Duplicate of https://github.com/UnigramDev/Unigram/issues/1206

**Closed** 2020-04-27 09:40 UTC

**Comment by CornyjK** [comment] 2020-04-27 11:15
Sorry, was unaware that was the cause.
