### ISSUE TITLE
Windows MyPeople doesn't appear

### ISSUE THREAD

**Issue by HammyHavoc** [UnigramDev/Unigram#513] opened 2018-01-14 17:10 UTC
Hi all,

I saw https://twitter.com/vitorgrs/status/878191273219248128 and was thrilled by the idea, but I can't seem to get My People to appear as an option in Apps, so it doesn't seem to work. Any help would be massively appreciated. Using the latest release from the Windows Store.

**Comment by FrayxRulez** [comment] 2018-01-15 16:58
Duplicate of #375

**Closed by FrayxRulez** 2018-01-15 16:58 UTC

**Comment by HammyHavoc** [comment] 2018-01-15 17:01
Are you sure this is a duplicate of #375 ? I don't get Unigram in any capacity in My People.

**Comment by FrayxRulez** [comment] 2018-01-15 17:02
If you check #429 there's an explanation about why My People has been disabled.
It will come back with Unigram 1.0, I hope in a month or so
