### ISSUE TITLE
Do not move pinned chats outside of chats list

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#1096] opened 2019-05-02 19:47 UTC
![image](https://user-images.githubusercontent.com/43090263/57102463-d406a900-6d23-11e9-8225-6b94551ce463.png)

**Comment by FrayxRulez** [comment] 2019-05-02 20:29
Duplicate of #1056

**Closed by FrayxRulez** 2019-05-02 20:29 UTC
Labels: bug, chats list

**Comment by MarcAnt01** [comment] 2019-05-02 20:31
That issue doesn't talk about moving to the left part🤔
