### ISSUE TITLE
Cant send pdf in secret chats. version 7.2 5840 x64

### ISSUE THREAD

**Issue by Jonathanarielarg** [UnigramDev/Unigram#2155] opened 2020-11-25 23:08 UTC
when I drop the pdf and click on send, nothing happend. I cant send files!!!

**Comment by FrayxRulez** [comment] 2020-11-26 08:18
Are you able to send files in normal chats?

**Comment by FrayxRulez** [comment] 2020-11-26 09:14
I can't reproduce the issue.

**Comment by FrayxRulez** [comment] 2020-11-26 12:29
@Jonathanarielarg might have found out. Are you trying to send a file from OneDrive?

**Comment by FrayxRulez** [comment] 2020-11-27 10:45
I would consider this fixed in https://github.com/UnigramDev/Unigram/commit/7eb4abe7a640d64ab1bf7674ae4caecdbf223e73

**Closed by FrayxRulez** 2020-11-27 10:45 UTC

**Comment by Jonathanarielarg** [comment] 2020-11-27 20:58
Hi, sorry for de delay in my response. There is a problem in one computer. When I want to send pdf that I have un a file sharing (\\server\file.pdf) nothing happend, and sometimes the unigram close. In another computer (same version) same problem. But when I copy the file from the sharing to the local computer I can send the file.

**Comment by FrayxRulez** [comment] 2020-11-27 20:58
Yes, then I fixed it 😎 you can wait for a update in the store or download the fixed version from t.me/unigramappx
