### ISSUE TITLE
Multi account share

### ISSUE THREAD

**Issue by abh-oss01** [UnigramDev/Unigram#1411] opened 2020-04-23 10:01 UTC
Multi account sharing is not available in, it doesn't give an option to share using other logged in accounts, it only gives options for the account currently we are switched into right now.

Just like it is in Telegram X, shown below:

![image](https://user-images.githubusercontent.com/56572179/80086491-6d534e80-8577-11ea-9dcf-37c7998090f6.png)

**Comment by MarcAnt01** [comment] 2020-04-23 10:02
Duplicate of https://github.com/UnigramDev/Unigram/issues/1115

**Closed by MarcAnt01** 2020-04-23 10:02 UTC
