### ISSUE TITLE
Names of messengers are no longer read by screen readers.

### ISSUE THREAD

**Issue by TheQuinbox** [UnigramDev/Unigram#2466] opened 2021-07-09 22:17 UTC
**Describe the bug**
When arrowing through a private conversation with a screen reader, the person's name is no longer announced before the message. You simply hear the message, then the timestamp. This requires the user to have to listen for sent and received at the end of the message, which can take time.
**To Reproduce**
1. Grab the free, NVDA screen reader from www.nvaccess.org.
2. Run NVDA, and open Unigram.
3. Open a private conversation
4. Arrow through the list. You'll notice names aren't read. This also happens with groups, but only with your name. It reads the names of other people that sent messages, just not you in that case.

**Expected behavior**
If this was on purpose, I really am not a fan of it. I prefered when the messages read as
You.
<message>

**Version Info**
Unigram: Latest from Microsoft Store.
Windows: Windows 10 (64-bit), 2004.

**Comment by beqabeqa473** [comment] 2022-03-14 21:00
What do you think about that?

**Comment by FrayxRulez** [comment] 2022-04-01 12:34
I believe this is a duplicate of #2450

**Closed by FrayxRulez** 2022-04-01 12:34 UTC
Labels: bug, needs-triage
