### ISSUE TITLE
CJK font fallback is messed up

### ISSUE THREAD

**Issue by tianblr** [UnigramDev/Unigram#1841] opened 2020-06-19 10:44 UTC
Recently updated to Unigram 4.1 and I noticed that Chinese and Japanese texts are not displayed in proper fonts. 

![image](https://user-images.githubusercontent.com/35773840/85124028-d4317300-b25b-11ea-9ef7-1b52d45f5582.png)

Simplified Chinese text should be displayed in Microsoft Yahei, Traditional Chinese in Microsoft JhengHei, and Japanese in Yu Gothic. None should be displayed in Malgun Gothic.

This problem was not present in past versions (because that was the reason I chose Unigram over the official Telegram app). I think it might have been introduced in the 4.0 update. 

Unfortunately I don't have a good example of how it worked in the past versions, but here is a old screenshot from 2019 of me chatting with Unigram in which the Chinese word "中山装“ is properly displayed with Microsoft Yahei.

![image](https://user-images.githubusercontent.com/35773840/85123988-c11ea300-b25b-11ea-8ca6-501d03aaf71e.png)

I am not a professional so forgive me if I'm not clear.

**Comment by FrayxRulez** [comment] 2020-06-19 10:46
Hi, Unigram is using your system font to render text, are you sure this has been introduced by a Unigram update and not by a system one?
Could you try to change your emoji set to Microsoft one in Settings > Chat Settings > Emoji Sets and see if the problem still persists?

**Comment by MarcAnt01** [comment] 2020-07-04 13:00
@tianblr I am closing this ticket in some days if you don't provide an answer

**Comment by tianblr** [comment] 2020-07-05 05:18
I have changed the emoji set to Microsoft one and the problem is still there. 

I don't think it's introduced by a system update because all other UWP apps that I've been using are working well. Here is a screenshot of the same Chinese paragraph in Microsoft Todo and you can see that the content is correctly displayed in Microsoft YaHei. 

![image](https://user-images.githubusercontent.com/35773840/86526090-f49b3780-bec1-11ea-9355-997756254921.png)

**Comment by tianblr** [comment] 2020-07-05 05:25
I just noticed something. Now I think it's related to the system language setting.

I used to have Korean in my system's preferred languages list after English, Chinese (Simplified), and Japanese. Once I removed Korean from the preferred languages list, the text is correctly displayed with Microsoft YaHei (which follows my system's language preference). But when I add Korean back to the list, no matter where it appears in the list, the text is displayed in the Korean font.

**Comment by FrayxRulez** [comment] 2020-12-01 12:33
What's the app language?

**Comment by FrayxRulez** [comment] 2020-12-01 12:33
Because Korean is in the list of supported font families, so the XAML engine might consider that while choosing the font.

**Comment by AkazaRenn** [comment] 2023-06-17 15:55
I'm experiencing the same issue, here's how it looks like in Unigram vs in Feedback Hub:

Unigram:
![image](https://github.com/UnigramDev/Unigram/assets/8340896/db673bf6-af10-4009-a351-0efddd8d34ec)

In Feedback Hub:
![image](https://github.com/UnigramDev/Unigram/assets/8340896/a08ab655-8cd1-4d76-ac40-96d635369994)

Here's the list & fallback order of my installed languages:
![image](https://github.com/UnigramDev/Unigram/assets/8340896/699f5dea-1696-411c-8f66-cebbf2f33d94)

It is obvious by comparing the punctuations, where commas and periods are supposed to be centered by fallbacking to `Chinese (Traditional, Taiwan)`.

App itself is in English.

**Comment by FrayxRulez** [comment] 2023-08-17 08:57
I may have figured out the cause for this issue, I'll release a beta tonight that should fix it.

**Comment by FrayxRulez** [comment] 2023-12-22 15:10
By looking at XAML source code and documentation, the framework uses alternative fonts only for Korean and Japanese since at least 2015 ([here](https://github.com/microsoft/microsoft-ui-xaml/blob/winui3/release/1.4-stable/dxaml/xcp/core/text/RichTextServices/xcp/PALFontAndScriptServices.cpp#L176) the reference to TH2).
[Here](https://learn.microsoft.com/en-us/uwp/api/windows.ui.xaml.media.fontfamily.xamlautofontfamily) you can find the list of fonts used by the framework:
<table>
   <tr><th>Language</th><th>Default FontFamily</th></tr>
   <tr><td>Japanese</td><td>Yu Gothic UI</td></tr>
   <tr><td>Korean</td><td>Malgun Gothic</td></tr>
   <tr><td>All others</td><td>Segoe UI</td></tr>
</table>

The only thing that I can say is that, by reading the source code, it seems that `Yu Gothic UI`/`Malgun Gothic` is reported as the default font only if the app language is set to either Korean or Japanese.
It isn't enough to change the app language in settings, this is two different concepts.

**Comment by FrayxRulez** [comment] 2023-12-22 15:12
And again, looking at the source code, there's no "fallback" system really.
The framework only checks for the current very first app language (that's it, the system UI language)

**Comment by Dustin-Jiang** [comment] 2023-12-23 06:05
Experiencing the same issue after upgrading the app to 10.3.1 (9583). 

It is interesting that only some components is messed up while fonts in the other parts of the app are correct, for example, setting pages and sidebar. 

![图片](https://github.com/UnigramDev/Unigram/assets/56217843/4c9afe6e-fa22-4076-9a46-da7145ace34d)
In the pic you can see that the setting page gets the correct font (Microsoft YaHei UI in Chinese Simplifed), but **the example message bubbles at right up corner** get fonts messed up (you can easily see the characters in different sizes and weights). 

So I guess that some changes recently might broke the font settings in the most customized components (if exists) while the app still gets the correct font settings.

**Closed** 2024-01-05 13:18 UTC
Labels: bug

**Comment by AkazaRenn** [comment] 2025-12-12 20:26
@FrayxRulez I think there's still some problem on it. The punctuation is showing incorrectly. What I used are "。。。。".

Unigram:
<img width="213" height="79" alt="Image" src="https://github.com/user-attachments/assets/b126a077-194e-4cf7-8a1d-c5e30377139a" />
Feedback Hub:
<img width="174" height="79" alt="Image" src="https://github.com/user-attachments/assets/49067501-7e6a-44da-a4b6-2d49958caba0" />

As you can see that they are centered in the Feedback Hub, which aligns with the standard of Traditional Chinese, but in Unigram they are placed to the bottom-left corner. That's more of a Simplified Chinese or Japanese standard.

My language order doesn't change from [my previous comment](https://github.com/UnigramDev/Unigram/issues/1841#issuecomment-1595793250).

**Comment by AkazaRenn** [comment] 2025-12-12 20:34
I'll create another issue for it.
