### ISSUE TITLE
Pinned message view is overlapping sticker panel

### ISSUE THREAD

**Issue by sabbyX** [UnigramDev/Unigram#2213] opened 2021-01-10 07:27 UTC
### Version
Unigram: 7.3 (5952)

### Info
![image](https://user-images.githubusercontent.com/61574665/104116835-2cd47480-5342-11eb-95c1-28475bf8b50d.png)

kinda annoying :( You can't even dismiss pinned message if you're admin or multiple messages are pinned!

**Comment by MarcAnt01** [comment] 2021-01-10 09:26
Hello @sabbyX , thanks for reporting, but I have already make a ticket to keep track of that

**Comment by MarcAnt01** [comment] 2021-01-10 09:26
Duplicate of https://github.com/UnigramDev/Unigram/issues/2204

**Closed by MarcAnt01** 2021-01-10 09:26 UTC
