### ISSUE TITLE
Thank you for awesome work, and rotten tomatoes to Microsoft for their sluggish and extremely awful and slow UI.

### ISSUE THREAD

**Issue by anacondaq** [UnigramDev/Unigram#3077] opened 2024-02-21 23:33 UTC
I am using Unigram 10.8.1 (9945) x64 Direct. I decided to give it a try because the original Telegram app limits the download speed of files even for premium users. Yours, however, does not impose such restrictions and works perfectly.

I really like your interface; everything is designed very nicely and thoughtfully. It's evident that you've maximized what Microsoft Windows and their framework offer you to develop the interface.

Unfortunately, after a few days of testing, I have to leave this amazing and cool application due to the hanging caused by the transparency of the interface. I assume (since I don't have logs for debugging and profiling) that it's because of the transparency of the interface, due to blurriness, and because of poorly written code by Microsoft themselves (because all other applications on WinUI3 have the same issues). All of this has provoked and forced me to abandon your amazing project.

Thank you very much for developing this product and the efforts you put into it. It's magnificent. It's a pity that you're being dragged down by such problems, which affect both you and your users, stemming from the Microsoft corporation and their flawed, glitchy framework.

If you have the opportunity or time, could you perhaps start refactoring and exploring other alternatives for your project's UI display?

Unfortunately, Intel UHD Graphics (UHD 610, 620, 630) are completely incapable of rendering the interface quickly, and the OS itself responds slowly. This leads to micro-freezes in the application that are really annoying. Moreover, these micro-freezes, caused by the responsiveness of the interface when calling an element, are not related to your application.

There is a huge audience of people like me who want to try an alternative to Telegram due to its limitations, but unfortunately, similar implementations do not allow for a full switch.

I wish you success in your challenging work, and I hope that someday you will detach your Telegram from this worthless, repulsive, dead technology from Microsoft.

**Comment by NimaQu** [comment] 2024-03-24 17:33
same problem

**Comment by makisukurisu** [comment] 2024-03-25 19:06
You can disable transparency from system settings, but since your iGPU is pretty old (2018, or so), even this may not be enough.

Disabling animations is possible in app's settings, which may also improve the performance.

It's truly a pitty that you have bad experience with the app, though 😢

Also, just as a note, Unigram is not WinUI 3, it's actually UWP and WinUI 2, but they are similar in some places, so it's only natural to confuse them.

**Comment by MarcAnt01** [comment] 2024-04-16 09:08
Duplicate of https://github.com/UnigramDev/Unigram/issues/1272

**Closed as completed by MarcAnt01** 2024-04-16 09:08 UTC
