### ISSUE TITLE
My People integration without syncing all contacts to Telegram

### ISSUE THREAD

**Issue by ivucica** [UnigramDev/Unigram#1202] opened 2019-09-08 19:16 UTC
Hi,

I'd like to use My People integration only with the contacts that are already present in Telegram.

As it is, if I give Unigram access to system contacts database, it'll add my contacts to Telegram. Yet, access to contacts is required for My People to work.

**Comment by MarcAnt01** [comment] 2019-09-08 20:19
Duplicate of https://github.com/UnigramDev/Unigram/issues/1104

**Closed by MarcAnt01** 2019-09-08 20:19 UTC

**Comment by ivucica** [comment] 2019-09-08 22:53
@MarcAnt01 Interesting. Though that discussion has diverged to "you can't add people by nickname".
