### ISSUE TITLE
Compile for Windows 10 Arm

### ISSUE THREAD

**Issue by Charmandrigo** [UnigramDev/Unigram#1969] opened 2020-08-31 18:36 UTC
I make this suggestion as something kinda optional since Windows 10 on arm can run the x86 version of Unigram via emulation, I run on a Galaxy Book2 which has a snapdragon processor.
I'd like to suggest the app to be recompiled as Arm64, so it can run more natively in this system without the need of emulating the x86 architecture which consumes additional memory and battery resources.

**Comment by MarcAnt01** [comment] 2020-09-01 06:51
Hello, there's already another ticket to keep track of that, consider that it's not easy since some dependencies such as TDLib don't support Arm64 currently.

**Comment by MarcAnt01** [comment] 2020-09-01 06:51
Duplicate of https://github.com/UnigramDev/Unigram/issues/1914

**Closed by MarcAnt01** 2020-09-01 06:51 UTC
