### ISSUE TITLE
Make left padding on chat header

### ISSUE THREAD

**Issue by WeFenFinit** [UnigramDev/Unigram#1829] opened 2020-06-17 13:27 UTC
![image](https://user-images.githubusercontent.com/22540805/84903910-80dee980-b0d0-11ea-9735-1e0c6a90e6c3.png)

**Comment by MarcAnt01** [comment] 2020-06-17 13:46
Maybe a duplicate of https://github.com/UnigramDev/Unigram/issues/1295 ?

**Comment by WeFenFinit** [comment] 2020-06-17 13:59
@MarcAnt01 no, it needs to be like this:
![image](https://user-images.githubusercontent.com/22540805/84907448-05cc0200-b0d5-11ea-8698-dcbb04fc9cb3.png)

**Comment by MarcAnt01** [comment] 2020-06-17 17:45
Why? I think they should be hovered separately, since they do different things

**Comment by WeFenFinit** [comment] 2020-06-17 17:53
@MarcAnt01 make padding for INNER CONTENT, that hover shouldn't work like that

**Comment by MarcAnt01** [comment] 2020-06-17 18:17
Why?

**Comment by FrayxRulez** [comment] 2020-06-17 18:19
> Why?

Because this way it looks super ugly, Filippo

**Comment by Huntzor** [comment] 2020-06-17 19:41
фенька работай

**Closed** 2020-06-21 16:23 UTC
Labels: visual
