### ISSUE TITLE
shuffle function does not work

### ISSUE THREAD

**Issue by John32145** [UnigramDev/Unigram#2467] opened 2021-07-10 01:25 UTC
hello, would like to report a issue, it seems like theres a shuffle button for the media player, thing is... it, does not work! could you fix it? thank you.

**Comment by makisukurisu** [comment] 2021-07-10 04:30
It's missnamed. The correct name is reverse order button. Probably there should be both.

**Comment by FrayxRulez** [comment] 2022-02-12 17:30
Duplicate of https://github.com/UnigramDev/Unigram/issues/2219

**Closed by FrayxRulez** 2022-02-12 17:30 UTC
Labels: bug, needs-triage
