### ISSUE TITLE
how it builds?

### ISSUE THREAD

**Issue by atrdev-rgb** [UnigramDev/Unigram#3034] opened 2023-06-06 20:49 UTC
Hello. I use VS 17 2022 
Please explain step by step what needs to be done when building this project to make it work?

after git clone and building Telegram.Td.UWP.1.8.14 I put Telegram.Td.UWP.1.8.14 in Libraries folder.
I collect without call support.
```
./vcpkg.exe install ffmpeg[opus,vpx]:x64-uwp lz4:x64-uwp openssl:x64-uwp zlib:x64-uwp libwebp:x64-uwp libogg:x64-uwp opus:x64-uwp
./vcpkg.exe integrate install
```
but on the first assembly it swears

pls update your /Build-instructions.md

**Comment by atrdev-rgb** [comment] 2023-06-06 21:19
and here are the other build errors
```
Error C2672 "flatbuffers::table::VerifyField": the corresponding overloaded function was not found (the source file is being compiled..\Libraries\libtextclassifier\lang_id\common\flatbuffers\model-utils.cc ) Telegram.Native E:\Unigram\Libraries\libtextclassifier\lang_id\common\flatbuffers\model_generated.h 241
Error (active) E0304 missing instances of the function template "libtextclassifier3::saft_fbs::model::VerifyField" corresponding to the telegram argument list.Native E:\Unigram\Libraries\libtextclassifier\lang_id\common\flatbuffers\model_generated.h 241
OSHIBKA cannot resolve build or Windows metadata file 'E:\Unigram\x64\Debug\Telegram .Native .Calls\Telegram.Native.Calls.winmd telegram' E:\Unigram\Telegram\Telegram.csproj
Oibka with the sign "<", the statistical value 0x3C, cannot be in the initial state., line 356, position 5. Telegram E:\Unigram\Telegram\Themes\Accent.xaml
Oibka NU1101 Could not find the Telegram.Td.UWP package. Packages with such an identifier are missing in a series of additional packages: nuget.org , Telegram@Local Telegram.Msix E:\Unigram\Telegram.Msix\Telegram.Msix.wapproj 1
This project contains links to NuGet packages that are missing on this computer. Use NuGet Package Restore to download them. For more information, see http://go.microsoft.com/fwlink /?LinkID=322105 . There is a missing file ..\packages\Telegram.Td.UWP.1.8.14\build\native\Telegram.Td.UWP.targets. Telegram.Native.Calls E:\Unigram\Telegram .Native .Calls\Telegram.Native.Challenges.vcxproj 551
Error C2672 "flatbuffers::table::VerifyField": the corresponding overloaded function was not found (the source file is being compiled..\Libraries\libtextclassifier\lang_id\common\flatbuffers\embedding-network-params-from-flatbuffer.cc ) Telegram.Native E:\Unigram\Libraries\libtextclassifier\lang_id\common\flatbuffers\embedding-network_generated.h 105
Error C2672 "flatbuffers::table::VerifyField": the corresponding overloaded function was not found (the source file is being compiled..\Libraries\libtextclassifier\lang_id\common\flatbuffers\embedding-network-params-from-flatbuffer.cc ) Telegram.Native E:\Unigram\Libraries\libtextclassifier\lang_id\common\flatbuffers\embedding-network_generated.h 106
Error C2672 "flatbuffers::table::VerifyField": the corresponding overloaded function was not found (the source file is being compiled..\Libraries\libtextclassifier\lang_id\common\flatbuffers\embedding-network-params-from-flatbuffer.cc ) Telegram.Native E:\Unigram\Libraries\libtextclassifier\lang_id\common\flatbuffers\embedding-network_generated.h 107
Error C2672 "flatbuffers::table::VerifyField": the corresponding overloaded function was not found (the source file is being compiled..\Libraries\libtextclassifier\lang_id\common\flatbuffers\embedding-network-params-from-flatbuffer.cc ) Telegram.Native E:\Unigram\Libraries\libtextclassifier\lang_id\common\flatbuffers\embedding-network_generated.h 218
Digitization C1083 does not open when you turn on: zlib.h: There is no such file or directory, Telegram.Native E:\Unigram\Libraries\libtextclassifier\lang_id\common\math\checksum.cc 22
Error C2672 "flatbuffers::table::VerifyField": the corresponding overloaded function was not found (the source file is being compiled..\Libraries\libtextclassifier\lang_id\fb_model\lang-id-from-fb.cc ) Telegram.Native E:\Unigram\Libraries\libtextclassifier\lang_id\common\flatbuffers\model_generated.h 241
Error C2672 "flatbuffers::table::VerifyField": the corresponding overloaded function was not found (the source file is being compiled..\Libraries\libtextclassifier\lang_id\fb_model\model-provider-from-fb.cc ) Telegram.Native E:\Unigram\Libraries\libtextclassifier\lang_id\common\flatbuffers\model_generated.h 241
Error C2672 "flatbuffers::table::VerifyField": the corresponding overloaded function was not found (the source file is being compiled..\Libraries\libtextclassifier\lang_id\fb_model\model-provider-from-fb.cc ) Telegram.Native E:\Unigram\Libraries\libtextclassifier\lang_id\common\flatbuffers\embedding-network_generated.h 105
Error C2672 "flatbuffers::table::VerifyField": the corresponding overloaded function was not found (the source file is being compiled..\Libraries\libtextclassifier\lang_id\fb_model\model-provider-from-fb.cc ) Telegram.Native E:\Unigram\Libraries\libtextclassifier\lang_id\common\flatbuffers\embedding-network_generated.h 106
Error C2672 "flatbuffers::table::VerifyField": the corresponding overloaded function was not found (the source file is being compiled..\Libraries\libtextclassifier\lang_id\fb_model\model-provider-from-fb.cc ) Telegram.Native E:\Unigram\Libraries\libtextclassifier\lang_id\common\flatbuffers\embedding-network_generated.h 107
Error C2672 "flatbuffers::table::VerifyField": the corresponding overloaded function was not found (the source file is being compiled..\Libraries\libtextclassifier\lang_id\fb_model\model-provider-from-fb.cc ) Telegram.Native E:\Unigram\Libraries\libtextclassifier\lang_id\common\flatbuffers\embedding-network_generated.h 218
```

**Comment by FrayxRulez** [comment] 2023-06-08 09:20
Duplicate of #2982. You can try to help each other!

**Closed as not planned by FrayxRulez** 2023-06-08 09:20 UTC

**Comment by atrdev-rgb** [comment] 2023-06-08 17:21
Your instructions are old, not up-to-date. 

Views/VoIPPage.xaml This file is no longer there at all.
