### ISSUE TITLE
Scheduled messages crash

### ISSUE THREAD

**Issue by scriptfx** [UnigramDev/Unigram#1264] opened 2019-12-11 14:12 UTC
Unigram 3.13.2635 crashes when pressing the "scheduled messages" button in "saved messages".

**Comment by FrayxRulez** [comment] 2019-12-12 09:04
I'm not able to reproduce this issue, maybe this depends on the message you scheduled?

**Comment by scriptfx** [comment] 2019-12-12 17:04
Ok. Steps to reproduce are:
1. Go to "Saved Messages"
2. Write a generic message ("test" for example)
3. Schedule the message 1h after now
4. Press the button that shows all the scheduled messages and it crashes.

![Scheduled messages button](https://user-images.githubusercontent.com/35109437/70733043-cc6f9f80-1d09-11ea-8618-f51c250751a3.png)

**Comment by scriptfx** [comment] 2019-12-12 17:06
I have a Surface Pro 5th edition with Windows 10 Pro 1909 build 18363.476

**Comment by MarcAnt01** [comment] 2019-12-22 11:35
I reproduced the bug and despite the app crash, I got the notification

**Comment by entdark** [comment] 2019-12-22 20:57
Trying to open Scheduled saved messages makes the app crash on my end as well.
If it helps: I have 2 saved messages now: for 31.12.2019 and for 29.07.2020.

**Comment by FrayxRulez** [comment] 2019-12-27 11:19
This is fixed in 3.13.2638

**Closed by FrayxRulez** 2019-12-27 11:19 UTC
Labels: bug
