### ISSUE TITLE
Cannot forward messages silently / on a schedule

### ISSUE THREAD

**Issue by KeronCyst** [UnigramDev/Unigram#2263] opened 2021-03-05 23:07 UTC
Running:
Windows 10 20H2 (build 19042.844)
Unigram 7.5 (5961) X64

I don't actually know if this is possible even in the base Telegram desktop platform, but it'd be awesome to be able to forward messages silently or set them for forwarding at a future time/when the recipient comes online!

If this is already possible to do, I'd greatly appreciate a step-by-step tutorial, because I can't seem to figure out how to do it. Thanks in advance!

**Comment by MarcAnt01** [comment] 2021-03-07 20:40
Hi, thanks for reporting, we already have an old ticket to keep track of that

**Comment by MarcAnt01** [comment] 2021-03-07 20:40
Duplicate of https://github.com/UnigramDev/Unigram/issues/1858

**Closed by MarcAnt01** 2021-03-07 20:40 UTC

**Comment by KeronCyst** [comment] 2021-03-08 00:36
Sorry, I tried searching but couldn't find that one! Glad to know it's in the works.
