### ISSUE TITLE
Support for linux

### ISSUE THREAD

**Issue by yadavgulshan** [UnigramDev/Unigram#2076] opened 2020-10-09 10:30 UTC
Hey, can you please add a support for linux environment. If not possible then please use exe extension so that I and other linux users can also use your application by using wine. I don't know how to use it with that appxbundle extension .

**Comment by MarcAnt01** [comment] 2020-10-09 10:32
I am sorry, but this isn't possible

**Comment by MarcAnt01** [comment] 2020-10-09 10:32
Duplicate of https://github.com/UnigramDev/Unigram/issues/1937

**Closed by MarcAnt01** 2020-10-09 10:32 UTC
