### ISSUE TITLE
Error thrown when sent a file with newline in caption

### ISSUE THREAD

**Issue by cewbdex** [UnigramDev/Unigram#1476] opened 2020-05-01 08:47 UTC
When the text contains any newline (aka text is not only one line), it always throws me this error:

![image](https://user-images.githubusercontent.com/9021297/80793762-4c52b500-8b98-11ea-9ea5-49a5c9c2015b.png)
Figure 2: Thrown error

**Comment by CornyjK** [comment] 2020-05-01 08:48
Oh sorry, the first half of issue is a duplicate of #1050, but the second part remains.

**Comment by MarcAnt01** [comment] 2020-05-07 13:12
That's "fixed" now

**Comment by cewbdex** [comment] 2020-05-07 13:16
I can't agree, just throws a different exception, using latest commit.

![image](https://user-images.githubusercontent.com/9021297/81298800-98f52f00-9075-11ea-9519-b1dd9109cf27.png)
Figure 1: Exception

**Comment by MarcAnt01** [comment] 2020-05-07 13:17
As you can see it's been fixed with another exception

**Comment by MarcAnt01** [comment] 2020-05-07 13:27
@cewbdex apart from jokes, is the first line empty? Because I get no exception

**Comment by cewbdex** [comment] 2020-05-07 13:39
No.

**Comment by MarcAnt01** [comment] 2020-05-07 13:40
Then, I cannot understand since I get no exception

**Comment by FrayxRulez** [comment] 2020-06-01 09:43
Done in https://github.com/UnigramDev/Unigram/commit/567514783847a03b473eca27424c3f8d91e7f1d5

**Closed by FrayxRulez** 2020-06-01 09:43 UTC
Labels: bug
