### ISSUE TITLE
Stuggering on startup

### ISSUE THREAD

**Issue by PublicNME** [UnigramDev/Unigram#2885] opened 2022-10-30 16:40 UTC
When windows is starting, client is still "connecting..." status and dont download any messages and dont push any notification. For start working i need expand app, some wait for update and only after that i can collapse on tray and receive notitfiaction on new messages

1. clear install uwp app
2. check in advanced settings "run telegram on startup"
3. reboot windows

I would like the messages to be loaded immediately, without explicitly expand the unigram window

**Screenshots**
![screenshot 2022-10-30 001.jpg](https://img001.prntscr.com/file/img001/43vOb6t0Q2qCVaBHptSoqA.jpg)

**Version Info**
 - Unigram: 8.9 (7687) x64
 - Windows: 21h2 19044.2130

Can u fix that bug?

**Comment by FrayxRulez** [comment] 2022-11-01 00:33
I can take a look, but quite hard to do something as it requires a reboot to be tested.
In between, you're ~15 versions behind (not that the issue was fixed already, but it's a good practice to stay up to date)

**Comment by FrayxRulez** [comment] 2023-03-18 11:47
I'm not able to reproduce this: I just tried to reboot my computer and after it started Unigram automatically synchronized the chats in the background.

**Comment by FrayxRulez** [comment] 2023-05-01 18:12
As there was no updates on this since October, I'm closing the issue (might be Windows 10 only, IDK)

**Closed by FrayxRulez** 2023-05-01 18:13 UTC
Labels: bug, can't reproduce
