### ISSUE TITLE
Can't rename folder

### ISSUE THREAD

**Issue by Muaath5** [UnigramDev/Unigram#2430] opened 2021-06-21 11:12 UTC
**Describe the bug**
Can't rename folder after adding some chats to it

**To Reproduce**
1. Right click on some folder.
2. Edit folder.
3. Rename folder.
4. Add some chats **(that exists in your contacts, But you didn't have any message with them)** in that folder.
5. Add Apply changes to folder, Via ✅ In the top left.
6. **[[[BUG]]]**, Folder isn't renamed

**Expected behavior**
Folder should be renamed

**Version Info**
 - Unigram:7.8 (6540) X64 (latest)
 - Windows: Pro 21H1

**Comment by FrayxRulez** [comment] 2021-06-22 14:12
Hi, I can't reproduce the issue.
Can you turn on logs and send them to me?

**Comment by Muaath5** [comment] 2021-06-22 14:23
I sent logs to you in secret chat.

**Comment by FrayxRulez** [comment] 2021-06-22 14:24
I can't find any secret chat with you

**Comment by FrayxRulez** [comment] 2022-12-02 16:25
I think that most of these issues have been fixed over time, closing this

**Closed by FrayxRulez** 2022-12-02 16:25 UTC
Labels: can't reproduce
