### ISSUE TITLE
Support for robots (if it's possible)

### ISSUE THREAD

**Issue by samij263** [UnigramDev/Unigram#666] opened 2018-09-11 08:35 UTC
Apparently the app doesn't support robots.

**Comment by larsschellhas** [comment] 2018-09-11 13:47
Unigram does of course support Telegram bots. 
What problems do you run into?

**Comment by samij263** [comment] 2018-09-11 15:27
@larsschellhas 1- viewing bot's profile
2- start option won't appear unless i write manually.

**Comment by MarcAnt01** [comment] 2018-09-11 15:43
@samij263 Duplicate of that https://github.com/UnigramDev/Unigram/issues/663

**Comment by MarcAnt01** [comment] 2018-09-11 15:48
Anyway, when creating issues you have to be more clear

**Closed** 2018-09-12 16:36 UTC
Labels: duplicate
