### ISSUE TITLE
Open the search page when Unigram is used as share target

### ISSUE THREAD

**Issue by larsschellhas** [UnigramDev/Unigram#594] opened 2018-06-25 13:12 UTC
When you want to share something from another app via the system tools on mobile you come to the last chat you were in or to the chat list and on PC Unigram is opened with the chat list, too.

I think it is very confusing when you want to share something and you have to press the back button first to get to the chat list and then select someone.
In my opinion it would be much better if Unigram would switch to the new search page, where you then could search for and select the contact you want to send whatever you want to send.

**Comment by FrayxRulez** [comment] 2018-09-13 16:31
Marking this as duplicate of #440

**Closed by FrayxRulez** 2018-09-13 16:31 UTC
Labels: duplicate, enhancement
