### ISSUE TITLE
Persian Number does not show while writing

### ISSUE THREAD

**Issue by HamidRezaAshkiyan** [UnigramDev/Unigram#1906] opened 2020-07-12 06:47 UTC
![image](https://user-images.githubusercontent.com/38791873/87240699-274caf00-c431-11ea-85e1-43996b7c5913.png)

as you can see english number has no problem but persian number doesnt show.

**Comment by FrayxRulez** [comment] 2022-09-04 17:34
Duplicate of #2346

**Closed by FrayxRulez** 2022-09-04 17:34 UTC
Labels: bug
