### ISSUE TITLE
I can't reply to a message if I open Unigram through notifications

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#714] opened 2018-09-19 11:50 UTC

**Comment by FrayxRulez** [comment] 2018-09-19 19:09
Duplicate of #579?

**Comment by MarcAnt01** [comment] 2018-09-19 19:10
Nope, already checked that issue and it's about a behavior of message someones reply to not the message reply

**Comment by FrayxRulez** [comment] 2018-09-19 19:14
Then I can't understand this one

**Comment by MarcAnt01** [comment] 2018-09-19 19:15
When I open Unigram from a notification, replies don't work

**Comment by FrayxRulez** [comment] 2018-09-19 19:16
Then it's a duplicate :D

**Comment by MarcAnt01** [comment] 2018-09-19 19:18
Idk, in that bug said that the replied is sent and just not displayed in the preview as usual

**Comment by larsschellhas** [comment] 2018-09-19 19:19
@MarcAnt01 Yes and this is really how it it. If you click answer but nothing shows up, you still reply to the correct message, if you send your message

**Comment by MarcAnt01** [comment] 2018-09-19 19:20
But If I can't select the message I reply to, how can the reply be sent?

**Comment by MarcAnt01** [comment] 2018-09-19 19:55
Guys, they are different things, trust me

**Comment by larsschellhas** [comment] 2018-09-23 08:03
What message was it then?
I see no difference, because I never encountered a behaviour where I could not reply, but sometimes the "reply banner" is not visible.

**Comment by MarcAnt01** [comment] 2018-09-23 08:15
How can you reply to a message, if the banner doesn't appear?

**Comment by larsschellhas** [comment] 2018-09-24 16:20
You simply write the message and send it. It is still processed as a reply to that message.
It is exactly what #579 is about.

**Closed** 2018-09-24 17:00 UTC
Labels: bug
