### ISSUE TITLE
Changing download location to a network drive make the app stop working

### ISSUE THREAD

**Issue by aalberrty** [UnigramDev/Unigram#2853] opened 2022-10-08 10:35 UTC
**Describe the bug**
I have a NAS at home and it is mapped as a network drive F:, changing the download location to it stops the app from working even after restarting, it gives a blank dark blue screen where there isn't any button to press, need to reset app in settings to make it work again.

**To Reproduce**
1. Press profile picture
2. Press 'Settings'
3. Go in to 'Data and Storage'
4. Change 'Storage Path' to a network drive F: (\\\192.168.50.150)
5. The app presents a dark blue screen where a reset is required to fix it.

**Expected behavior**
The download location is changed and working properlly like the official version.

**Screenshots**
![image](https://user-images.githubusercontent.com/59857887/194703134-d1bde42a-bda5-4b46-9e87-dbfce282dae0.png)

**Version Info**
 - Unigram: 9.0 (7780)
 - Windows: Windows 11 Pro 22H2 22621.521

**Comment by Elsayed-A** [comment] 2022-10-14 20:56
how to get unigram to ask download path for each file

**Comment by FrayxRulez** [comment] 2022-10-17 15:03
Unfortunately storage works in kind of a "special" way for UWP apps, and I'm not sure that this issue can be fixed.
I guess that the best solution in this case would be to prevent you from setting a network drive as the download folder of the app.

**Comment by FrayxRulez** [comment] 2023-05-01 18:14
Duplicate of #2164

**Closed by FrayxRulez** 2023-05-01 18:14 UTC
Labels: bug, blocked
