### ISSUE TITLE
Background synchronization doesn't work

### ISSUE THREAD

**Issue by MrFredber** [UnigramDev/Unigram#2900] opened 2022-11-17 09:19 UTC
**Describe the bug**
When adding new Photo Background, app don't adding it in background gallery and you can't use it on different devices.

**To Reproduce**
1. Change Background photo for chats
2. Go to this section on official mobile version of telegram and see, that this background is not added in background gallery

**Expected behavior**
In previous builds it worked fine.

**Screenshots**
![image](https://user-images.githubusercontent.com/33953266/202405575-b3ce3d8a-9d84-48f4-a3d2-b912fb4e6bb2.png)
![Screenshot_2022-11-17-16-10-56-47](https://user-images.githubusercontent.com/33953266/202405722-ba267371-fc2f-4b89-a3a4-d572e94b8d62.png)

**Version Info**
 - Unigram: 9.1 (7880) X64 Direct
 - Windows: Windows 10 Pro 22H2 (19045.2251)

**Additional context**

**Comment by MrFredber** [comment] 2022-11-17 09:33
Upd: after adding this background through the mobile version happened this:
![image](https://user-images.githubusercontent.com/33953266/202409421-f7dd6a6d-c13c-4c67-888e-428c29b6514b.png)

**Comment by FrayxRulez** [comment] 2022-11-17 09:34
@MrFredber So it's probably a bug in the mobile app not pulling the backgrounds from the cloud?

**Comment by MrFredber** [comment] 2022-11-17 09:38
I don't think so. When i added a "blue cat", this pic immediately showed in mobile version. 
And before typing this issue, i rebooted mobile version 2 times, but it didn't help.

**Comment by FrayxRulez** [comment] 2022-11-17 11:29
If the background shows up in Unigram it means that the server confirmed that the picture was successfully uploaded and stored into your cloud, otherwise it won't show up at all. It could be that the background was added at the end of the list of the backgrounds, I would check there.
In any case, I'm 100% sure that the issue is on the mobile app, and not in Unigram.

**Comment by FrayxRulez** [comment] 2022-11-17 11:40
@MrFredber The same way I could have broken it, Android app could have broken it as well. How many accounts do you have logged in on mobile? Android app tries to merge together the backgrounds of all the logged in accounts and this might break as well.

**Comment by MrFredber** [comment] 2022-11-17 11:42
I have only one account across all devices.

**Comment by MrFredber** [comment] 2022-11-17 12:06
Oh, i get it now. Unigram doesn't upload image on cloud and Telegram mobile does. JPEG artifacts confirm this.
![image](https://user-images.githubusercontent.com/33953266/202441537-c0e7f894-f2d6-4981-85f6-50af49c277bd.png)

**Comment by FrayxRulez** [comment] 2022-12-01 12:49
This was fixed in a recent version of TDLib (not sure if we deployed an update tho)

**Closed by FrayxRulez** 2022-12-01 12:49 UTC
Labels: bug, needs-triage
