### ISSUE TITLE
When you change the group image it is not displayed in the conversation list

### ISSUE THREAD

**Issue by mautheus** [UnigramDev/Unigram#683] opened 2018-09-14 05:05 UTC
![wp_ss_20180913_0006](https://user-images.githubusercontent.com/40085049/45530763-a8e63e00-b7c2-11e8-9508-c59cc0d146d1.png)

**Comment by larsschellhas** [comment] 2018-09-14 07:07
Thanks for the report! But duplicate of #589

**Closed by larsschellhas** 2018-09-14 07:07 UTC
