### ISSUE TITLE
group members info suggestion 

### ISSUE THREAD

**Issue by alighamari** [UnigramDev/Unigram#1644] opened 2020-05-24 23:06 UTC
in group info and members pane unigram shows who gave members admin rights and not last seen 
in my opinion it should show last seen with an star or like android last seen and admin nickname on left
 
screen shot taken on unigram version 4893.0 and telegram android 6.1.1(1974)

![image](https://user-images.githubusercontent.com/24440862/82766949-90a04080-9e38-11ea-9879-5cde09348f9b.png)
![image](https://user-images.githubusercontent.com/24440862/82766952-9b5ad580-9e38-11ea-9f7c-be8174271348.png)

**Comment by MarcAnt01** [comment] 2020-05-25 07:32
Agree, but that’s a duplicate

**Comment by MarcAnt01** [comment] 2020-05-25 07:33
Duplicate of #1343

**Closed** 2020-05-25 07:33 UTC
