### ISSUE TITLE
Problems in hiding caption in photo viewer on Windows 10 Mobile

### ISSUE THREAD

**Issue by morenj96** [UnigramDev/Unigram#805] opened 2018-10-10 11:59 UTC
- Open a picture in Unigram. (you'll see picture comment is visible)
- touch the screen to hide comment.
- touch again to reshow picture comment. (here, you'll see comment become visible for a moment and it will been hidden immediately)

Unigram 2.1.1818 (happens only on Mobile)

**Comment by MarcAnt01** [comment] 2018-10-10 13:28
Unable to reproduce

**Comment by morenj96** [comment] 2018-10-10 13:37
@MarcAnt01 Why?
It isn't exist in previous versions

**Comment by dmnmsc** [comment] 2018-10-10 13:41
@MarcAnt01 I can reproduce on mobile. And it's a pain on videos because you can't go forward or rewind

**Comment by MarcAnt01** [comment] 2018-10-10 13:42
@dmnmsc @morenj96 OK, so happens in mobile only, because on PC I cannot reproduce

**Comment by MarcAnt01** [comment] 2018-10-17 17:06
There are no APIs to fix it on Mobile so far

**Comment by morenj96** [comment] 2018-10-17 17:09
@MarcAnt01 It doesn't need to fix, when in previous versions all thing were good.
So it's able to return viewer codes to previous versions

**Comment by MarcAnt01** [comment] 2018-10-17 18:16
What was the latest version with it functional?

**Comment by morenj96** [comment] 2018-10-17 18:19
@MarcAnt01 I think it was version 2.1.1778

**Comment by FrayxRulez** [comment] 2018-10-22 19:59
Fixed in https://github.com/UnigramDev/Unigram/commit/f42e3306b1e8c78d02ea9ab43bc823a47a59726c

**Comment by MarcAnt01** [comment] 2018-10-31 06:48
Reopened as mobile users reported that bug continues also with the fix

**Comment by MarcAnt01** [comment] 2019-12-10 18:40
Closing, since mobile support has been dropped

**Closed by MarcAnt01** 2019-12-10 18:40 UTC
Labels: blocked, bug
