### ISSUE TITLE
Read status for nested groups:

### ISSUE THREAD

**Issue by vladkasianenko** [UnigramDev/Unigram#3083] opened 2024-04-11 18:40 UTC
Please do not report bugs or make suggestions/feature requests through issues on GitHub. We have moved to https://bugs.telegram.org/ , please refer to the README for further information.
I created bugs there, but no one ever replied to me.

See the nested group:
![image](https://github.com/UnigramDev/Unigram/assets/14053728/b3378cd7-2538-456d-8a91-b3fae7d12e0e)

But when you open it, no unread messages:
![image](https://github.com/UnigramDev/Unigram/assets/14053728/e1bb3978-6e66-44e5-9fe5-98b60edc5ac7)

**Comment by makisukurisu** [comment] 2024-04-11 18:55
Hello!
This is a known problem, and was reported as far as #2953, with no fix for (at least some) Forum related issues. (I believe, either it was, or it was confirmed to be a TDLib problem somewhere else)

Previously it was a technical limitation of TDLib, but right now - I'm not sure. (Hopefully Fela can clear this up)

Thanks for bringing awareness to the issue, but, unless you have more to add to the issue, I will close this one as won't fix, since it's a duplicate.

**Closed as not planned** 2024-04-11 18:56 UTC
