### ISSUE TITLE
ContactNotRegistered is not formatted

### ISSUE THREAD

**Issue by makisukurisu** [UnigramDev/Unigram#2590] opened 2021-12-22 18:10 UTC
**Describe the bug**
When adding a contact you may stumble upon people not using Telegram. To which Unigram will propose you to invite {0} to Telegram. Oh, that's a bug.

**To Reproduce**
1. Go to contacts
2. Add someone not using Telegram to contacts
3. See error

**Expected behavior**
To show typed Name in place of {0}.

**Screenshots**
![image](https://user-images.githubusercontent.com/49622129/147136467-a1e3fda9-cb67-4148-87b7-884bc933e7da.png)

**Version Info**
 - Unigram: v8.3 8614 x64 direct
 - Windows: 11 21H2

**Additional context**
ContactNotRegistered is not formatted as I can see. Probably something to do in UserCreateViewModel.SendExecute

**Comment by MarcAnt01** [comment] 2021-12-22 19:22
Duplicate of https://github.com/UnigramDev/Unigram/issues/1803

**Closed by MarcAnt01** 2021-12-22 19:22 UTC
Labels: bug, needs-triage
