### ISSUE TITLE
BackButton in Proxy Settings page

### ISSUE THREAD

**Issue by EliasTaghavi** [UnigramDev/Unigram#626] opened 2018-09-02 05:02 UTC
in first use, in phone number page tap on proxy then opens proxy settings page ,
in this page when you tap on back button it exits from app instead of go back phone number page.
all of this happen in windows 10 mobile.

**Comment by FrayxRulez** [comment] 2018-10-22 17:18
Does this still happens?

**Comment by brullsker** [comment] 2018-10-22 17:43
Nope, doesn't happen - at least for me

**Comment by FrayxRulez** [comment] 2018-10-22 19:50
Well, as I can't reproduce the issue neither I'm going to close this. @EliasTaghavi feel free to reopen this if you still face the issue.

**Closed by FrayxRulez** 2018-10-22 19:50 UTC
Labels: enhancement

**Comment by EliasTaghavi** [comment] 2018-10-23 07:16
This issue didn't exits from Build 2.2.1862, I think
Thank you
