### ISSUE TITLE
Share target does not work from first lainch

### ISSUE THREAD

**Issue by xperiandri** [UnigramDev/Unigram#338] opened 2017-07-23 14:56 UTC
Version 0.4.521.0
When I share with Unigram first time UI looks like this
![image](https://user-images.githubusercontent.com/2365592/28500390-1d32d322-6fd0-11e7-95c9-3b3bc066893f.png)

And nothing can be shared with anyone

**Comment by FrayxRulez** [comment] 2017-07-23 14:56
Share is not implemented at all

**Comment by xperiandri** [comment] 2017-07-23 14:58
OK 🙂
Then at least this is good

**Comment by ikarago** [comment] 2017-07-24 05:12
The current share implementation is from a pretty ancient build and hasn't been updates with the rest of the app. 

I've temporarily disabled it in the newer dev-builds until we've replaced it with a newer implementation.

**Comment by ikarago** [comment] 2017-07-24 05:15
Also, dupe of #325

**Closed by ikarago** 2017-07-24 05:15 UTC
