### ISSUE TITLE
Unigram does not remember window position and size on start. 

### ISSUE THREAD

**Issue by bzarky** [UnigramDev/Unigram#2988] opened 2023-03-09 06:15 UTC
**Describe the bug**
Unigram does not remember previous window position and size on app startup. 

**To Reproduce**
Move and adjust window where you like it.
quit unigram. 
Start unigram
Window opens up in the middle of the screen at a default size. 

**Expected behavior**
Window position is saved and recalled on startup, like Telegram and Discord and every other app. 

**Version Info**
Unigram 9.4 (7974) X64 Direct
Windows 10 22H2 Home

**Additional context**
Seems to only affect Unigram. official telegram client, Discord, Firefox, all remember window positions on shutdown. Seems like something may have been overlooked?
Its frustrating having to move and resize the window to a different monitor every time I start it up. 

Thanks for taking a look.

**Comment by makisukurisu** [comment] 2023-03-09 06:30
Works for me, but you have to close the window using either Alt+F4 or the Close button.
If the window was closed unexpectedly (like if you closed it from tray) – it won't save last size and position.

Example of how you should close the window (And how you shouldn't):

https://user-images.githubusercontent.com/49622129/223939046-57517ba7-00a4-4c42-acea-922fa35f8e07.mp4

**Comment by bzarky** [comment] 2023-03-09 07:50
None of that worked for me until I Shift-Clicked on the window close button (this forces windows to save the window position), and now all of what you said is working.
 How strange!
For some reason it wasnt saving window position until I did that. I had always closed the window with the window-close button before and it hadn't worked,  But Shift-Clicking on that button seems to have fixed it, and I no longer need to shift-click for it to remember. 

Well, thanks for the help. I guess it was something strange on my end.

**Closed** 2023-03-09 07:50 UTC
Labels: bug, needs-triage

**Comment by FrayxRulez** [comment] 2023-03-09 07:52
@bzarky Window position and sizing for UWP apps is completely handed by the system, and technically I have no way to override this behavior (that is: APIs to change size and position are forbidden to UWP apps). 
If the position and size are not saved for you, the problem is either on the system side, or the app crashes immediately before closing (not giving the system a chance to store the values).
