### ISSUE TITLE
When viewing image, clicking on the image won't quit

### ISSUE THREAD

**Issue by clafiok** [UnigramDev/Unigram#1772] opened 2020-06-09 15:10 UTC
In Telegram Desktop, when opening an image for full-screen view, clicking on the image will return to the chat window. But in Unigram, this doesn't work.

**Comment by cewbdex** [comment] 2020-06-09 16:36
In Unigram it works by swiping the image up or down.

**Comment by FrayxRulez** [comment] 2020-06-09 16:39
Yeah but it isn't the best behavior using a mouse. The gallery needs some improvements.

**Comment by cewbdex** [comment] 2020-06-12 11:36
Duplicate of #995

**Closed by cewbdex** 2020-06-12 11:36 UTC
Labels: enhancement
