### ISSUE TITLE
Unigram is not mentioning person without usernames.

### ISSUE THREAD

**Issue by binamracode** [UnigramDev/Unigram#2408] opened 2021-06-10 11:11 UTC
Whenever I try to mention a person which does not have a username then it shows as a link before sending but after sending it just becomes normal text and it does not mention that person too.

For more info, you can see [here](https://user-images.githubusercontent.com/61900781/121515082-7b2e9200-ca0c-11eb-91d9-f4999728ade3.mp4).

**Version Info**
 - Unigram: 7.8 (6524)
 - Windows: Build 21390.1000

**Comment by FrayxRulez** [comment] 2021-06-15 17:31
Marking this as a duplicate of #2419. (Of course it isn't, just I already mentioned the other as fixed in a commit and this can't be changed...)

**Closed by FrayxRulez** 2021-06-15 17:31 UTC
Labels: bug, needs-triage
