### ISSUE TITLE
Bug in media search on chat/channel

### ISSUE THREAD

**Issue by athulkrishna2015** [UnigramDev/Unigram#2007] opened 2020-09-15 16:52 UTC
search bar automatically closes(?) after typing for
about 1s 
https://t.me/unigraminsiders/295443

**Comment by MarcAnt01** [comment] 2020-09-15 21:27
Thanks for reporting, but we do already have a ticket for that

**Comment by MarcAnt01** [comment] 2020-09-15 21:27
Duplicate of https://github.com/UnigramDev/Unigram/issues/1281

**Closed by MarcAnt01** 2020-09-15 21:27 UTC
