### ISSUE TITLE
Reply thumbnail doesn't show up

### ISSUE THREAD

**Issue by shenao1100** [UnigramDev/Unigram#2826] opened 2022-09-05 13:52 UTC
**Describe the bug**
perview photo doesn't show up in every reply and pinned message

**Screenshots**

![image](https://user-images.githubusercontent.com/60335957/188464651-87ceb809-1004-482f-9a87-daa1f0201211.png)

![image](https://user-images.githubusercontent.com/60335957/188464740-51eb51da-83fa-42f5-9b0b-2098cdd9ce06.png)

**Version Info**
- Unigram: [8.9 (7682) x64 direct]
- Windows: [win10 2004 (19041.1415)]

**Comment by FrayxRulez** [comment] 2022-09-05 13:55
I'm not able to reproduce this issue. Did this start to happen after a recent update? Is it your first time using te app?

**Comment by MarcAnt01** [comment] 2022-10-05 12:28
@shenao1100 I am closing this, since we received no reply in one month. If you wishto reply, feel free and the issue will be reopened.

**Closed by MarcAnt01** 2022-10-05 12:28 UTC
Labels: bug, needs-triage
