### ISSUE TITLE
problem with background

### ISSUE THREAD

**Issue by HAsadian** [UnigramDev/Unigram#674] opened 2018-09-13 11:36 UTC
1) I select a custom background
2) close and open app
3) open a chat
4) background is the default baclground
(I use v1620 and have 4 account on my unigram)
![wp_ss_20180913_0001](https://user-images.githubusercontent.com/39188028/45486389-259bfc80-b770-11e8-8348-51ec49336592.png)
![wp_ss_20180913_0002](https://user-images.githubusercontent.com/39188028/45486390-26349300-b770-11e8-8b52-158971b85e36.png)

**Comment by FrayxRulez** [comment] 2018-09-19 19:26
Duplicate of #581

**Closed by FrayxRulez** 2018-09-19 19:26 UTC
Labels: bug
