### ISSUE TITLE
BUG: Background is changed on new windows

### ISSUE THREAD

**Issue by sepsol** [UnigramDev/Unigram#2838] opened 2022-09-19 23:04 UTC
**Describe the bug**
When I open a chat thread in a new window, my default chat background is ignored until I interact with its rendering. For example I have to change the theme/color or click on the user profile from the top to fix the background.

**To Reproduce**
1. Open a chat in a new window
2. See background not being what it's supposed to be

**Expected behavior**
The background should match the main window's background.

**Screenshots**
https://user-images.githubusercontent.com/47871887/191134170-3c961196-da00-47d7-b06e-cd9b3e7faf91.mp4

**Version Info**
 - Unigram: 8.9 (7687) X64
 - Windows: Windows 11 version 21H2 (OS Build 22000.978)

**Additional context**
I tested this in night theme with black background

**Comment by FrayxRulez** [comment] 2023-06-08 12:14
Duplicate of #2917 (I know this is older, but the other ticket got more info)

**Closed by FrayxRulez** 2023-06-08 12:14 UTC
Labels: bug, needs-triage
