### ISSUE TITLE
Suggest to change Persian/Arabic font

### ISSUE THREAD

**Issue by Ahmadhosseinbor** [UnigramDev/Unigram#2739] opened 2022-05-13 12:28 UTC
Like Telegram Desktop, it is better to use Persian/َArabic fonts instead of the default Persian/Arabic font. The current Arabic font has many problems and its readability is not good. Just like Telegram Desktop and Telegram Web Z, you can use the appropriate Arabic font.
My suggestion is to use the **Estedad** Persian/Arabic font

[ٍEstead typeface](https://github.com/aminabedi68/Estedad)

**Comment by MarcAnt01** [comment] 2022-05-13 12:35
Duplicate of https://github.com/UnigramDev/Unigram/issues/1893

**Closed by MarcAnt01** 2022-05-13 12:35 UTC
Labels: needs-triage
