### ISSUE TITLE
on group info page media pane is underlined by default and not members

### ISSUE THREAD

**Issue by alighamari** [UnigramDev/Unigram#1643] opened 2020-05-24 22:56 UTC
![image](https://user-images.githubusercontent.com/24440862/82766797-22a74980-9e37-11ea-9d44-23dd9936bd6f.png)
App version 4893.0 
Windows version 1909

**Comment by MarcAnt01** [comment] 2020-05-25 07:27
Thanks for reporting, but that’s a duplicate of #1638

**Closed by MarcAnt01** 2020-05-25 07:27 UTC
