### ISSUE TITLE
Unigram crashes on start

### ISSUE THREAD

**Issue by kosmakoff** [UnigramDev/Unigram#2460] opened 2021-07-07 10:18 UTC
**Describe the bug**
App crashes on startup. When launched it briefly shows the main window without controls and Unigram logo in the center. Then it simply closes. Meanwhile notifications are popping up and I am able to respond to messages in popup.

**To Reproduce**
1. Find the Unigram launch icon in search widget or Start menu.
2. Click on Unigram icon.
3. Observe the window appearing and disappearing.

**Expected behavior**
Window opens and layout is shown as usual.

**Version Info**
 - Unigram: [e.g. 7.8.6339 x64]
 - Windows: Windows 11 Pro, update 21H2, build 22000.51

**Additional context**
Not sure if it is caused by prerelease version of Windows, but the issue may be worth looking at to prepare for the future, I guess.

It is a prerelease insider build of Windows 11. I used to use the Unigram on Windows 10 and never experienced this error. Sometimes after restarts or reinstalls of Unigram the issue goes away, but then it returns. Crash dump file is generated 
[Unigram.exe.27196.zip](https://github.com/UnigramDev/Unigram/files/6776250/Unigram.exe.27196.zip)

**Comment by FrayxRulez** [comment] 2021-07-07 10:19
Are you using a custom download location in Unigram?

**Comment by kosmakoff** [comment] 2021-07-07 10:21
No, it's installed from Windows Store and install location (which is by default) doesn't have any funky characters (no Cyrillic, or anything else).

**Comment by kosmakoff** [comment] 2021-07-07 10:28
Little update. I have just reset the app using Windows build-in tools (from App management screen). Launched it and it prompted me to log in to telegram using QR code. QR code was not shown, instead there was a Unigram logo. So I logged in using phone number instead. After the code was entered it prompted me to give permission to read my contacts, I didn't get to click anything because in a second the app crashed again. Then I again was not able to launch it from start menu.

**Comment by FrayxRulez** [comment] 2021-07-07 10:29
Could you try with the app available from t.me/unigramappx? (This is a duplicate of another ticket btw)

**Comment by kosmakoff** [comment] 2021-07-07 10:38
Still does the same thing. Installed it from the channel. Download name is Unigram_7.8.6583.0_x64.msixbundle.

New crash dump attached, just in case. [Unigram.exe.1380.zip](https://github.com/UnigramDev/Unigram/files/6776436/Unigram.exe.1380.zip)

**Comment by KeronCyst** [comment] 2021-07-09 15:27
Can confirm; ever since the update this has been happening to me too. I can't even get a quick copied-&-pasted message sent.

Unigram 7.8 (6567) X64 on Windows 10 Home 21H1 was running perfectly fine.

(6586) is now crashing every single time (and yes, it also keeps launching without the left sidebar, even after I resize to show it). I've never seen this happen before; it's now completely unusable.

**Comment by kosmakoff** [comment] 2021-07-09 15:33
@KeronCyst are you on Windows 11 too?

Today I got an update to next preview version - build 22000.65 - and suddenly I was able to install the official version from the store and it worked. It even showed the QR code during initial sign-in screen. I will keep an eye on it and if it suddenly fails to start again - I'll let you know.

**Comment by FrayxRulez** [comment] 2021-07-09 15:35
The crash dumps on 11 were completely useless, maybe you could share one from 10?

**Comment by KeronCyst** [comment] 2021-07-09 17:45
@kosmakoff I'm still on Win10 and the crashes actually seem to have resolved themselves now, mysteriously enough. I'm not sure of what happened.

**Comment by domcote** [comment] 2021-07-20 15:22
Hi folks, I'm on 22000.71 [ARM64] and Unigram still exhibits **exactly** the behavior @kosmakoff describes, despite me uninstalling, resetting etc. I'm using the current store version. Anything I can do help troubleshoot?

**Comment by FrayxRulez** [comment] 2021-08-01 12:46
@domcote ARM64 might explain it... next update will support it natively, let's see if this helps

**Comment by bstone108** [comment] 2021-08-09 19:22
For me this problem seems to happen on far more than just on start.  sometimes it crashes on start, sometimes it crashes on links posted with previews, sometimes when typing..  sometimes it just crashes for seemingly no reason.  Problem exists on arm64, x86 32 and 64.   Tested on 4 different computers.  my snapdragon laptop,  an intel i3 processor,  a 32 bit atom processor,  and an amd rizon processor.  issue exists on all 4 running latest windows 10 updates and store version of unigram as of this message.  Problem started when the last update was released I believe tail end of june,  the interface revamp release.  and has remained a problem ever since.  Resetting and reinstalling app has had no effect.

**Comment by FrayxRulez** [comment] 2021-08-09 19:25
@bstone108 I'm not sure that this two things are related honestly

**Comment by bstone108** [comment] 2021-08-09 19:28
Might not be,  but this is the closest matching existing bug I could find that described my problem.  But the problem appears to extend slightly beyond what's listed here.  Didn't see point in creating a new bug report when they are pretty close to the same and probably even caused by the same thing.  Got some instructions for getting a crash dump for review?  never tried doing it so not sure how to get one on store apps :)

**Comment by Alovchin91** [comment] 2021-09-10 23:57
> @domcote ARM64 might explain it... next update will support it natively, let's see if this helps

@FrayxRulez Do you have an estimate of when is this next update happening?

**Comment by FrayxRulez** [comment] 2021-12-01 13:13
Any update on this?

**Comment by kosmakoff** [comment] 2021-12-13 10:31
I am currently on Windows 11 stable build 22000.348 and I haven't seen this issue for a while now.

As an OP of this issue I'd close it, but maybe it's helpful for someone else?

**Comment by domcote** [comment] 2021-12-13 11:25
I'm on 22509 and also haven't seen the issue in a while. As far as I'm concerned, the issue went away.

**Closed** 2021-12-13 12:18 UTC
Labels: bug
