### ISSUE TITLE
The option "Quick login using QR" isn't working

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#1387] opened 2020-04-02 08:54 UTC
After selecting it, the app goes back to the intro

**Comment by FrayxRulez** [comment] 2020-04-29 17:28
Duplicate of #1358 and fixed in https://github.com/UnigramDev/Unigram/commit/5bc3f5a969627a33e53fd71eb507624766228ff3

**Closed by FrayxRulez** 2020-04-29 17:28 UTC
Labels: bug
