### ISSUE TITLE
Text overlap

### ISSUE THREAD

**Issue by farazfallah** [UnigramDev/Unigram#2702] opened 2022-04-03 07:28 UTC
**Describe the bug**
In some messages sent by group admins, if the admin name is Persian or Arabic, the admin text appears on the name text.

**Screenshots**
![image](https://user-images.githubusercontent.com/77985343/161416585-53db952c-d0b7-483b-b5f6-baf1cb0f2c82.png)

**Version Info**
 - Unigram: [e.g. 7.6.7317 x64]
 - Windows: [11 build 22581]

**Comment by MarcAnt01** [comment] 2022-04-03 09:24
Thanks for reporting, but this is known and doesn't depend on Unigram

**Comment by MarcAnt01** [comment] 2022-04-03 09:24
Duplicate of https://github.com/UnigramDev/Unigram/issues/1423

**Closed by MarcAnt01** 2022-04-03 09:24 UTC
Labels: bug, needs-triage
