### ISSUE TITLE
Cannot connecting to proxy since updated to Unigram X

### ISSUE THREAD

**Issue by 1448839220** [UnigramDev/Unigram#536] opened 2018-02-28 12:50 UTC
I update to Unigram X tonight. When I try to log in (with proxy configured), Unigram keeps on "Connecting to proxy" with an loading animation below phone number textbox as screenshot blow. It keeps loading loading loading with nothing appearing.
I have reseted, reinstalled and restarted my computer many times, but nothing works. I am sure that the proxy works because older version of Unigram works, and other programs are connecting through it.
![image](https://user-images.githubusercontent.com/12206788/36788394-b75d611a-1cc8-11e8-9470-ce2d604f525c.png)

btw, I'm using build 17093 64-bit. The proxy software is ShadowsocksR, with SOCKS5 support. I also tried to restarted it but it didn't make any difference.

btw again... Though I cannot login my account, I received an notification from my group in Unigram.

**Comment by 1448839220** [comment] 2018-02-28 12:52
btw, I'm using build 17093 64-bit. The proxy software is ShadowsocksR, with SOCKS5 support. I also tried to restarted it but it didn't make any difference.

**Comment by batkiz** [comment] 2018-02-28 13:06
I meet the same question. And I also have tried EnableLoopBack but it doesn't work.
Maybe you could use the offical telegram app instead temporarily.

**Comment by FrayxRulez** [comment] 2018-02-28 13:10
Can you contact me at t.me/frayxrulez?

**Comment by FrayxRulez** [comment] 2018-03-02 12:18
Marking this as a duplicate of #545

**Closed by FrayxRulez** 2018-03-02 12:18 UTC

**Comment by FrayxRulez** [comment] 2018-03-13 18:45
Working in the last Store release
