### ISSUE TITLE
a bug. Very heavy bug

### ISSUE THREAD

**Issue by FOOOX1** [UnigramDev/Unigram#1341] opened 2020-02-23 10:48 UTC
Good afternoon, I encountered such a problem. I will immediately describe the configuration and what I did, a problem on the part of the developers, but this causes a lot of problems. 
I use: 1080ti, i7-8700, ddr4 (3000HZ), m. 2 samsung 970 evo (250gb). And a Gigabit router with 6 antennas. The computer is connected directly by an Internet cable. 

The essence of the problem: I turned on the cart on my phone and computer. You get a notification on your phone and from windows
In Unigram:
1) If the window is active and expanded at the moment, the W notification is displayed on the bottom right IMMEDIATELY
2) If the Unigram application is enabled and active, but, for example, I opened any other application, that is, the focus at the moment is not on Unigram (it is minimized) - then the delay is 1-50 seconds. At the same time, the number 0 is in the notification bar, and the number 1 shows only when the notification comes after 1-50sec. 
BUT if you switch to the Unigram app (deploy) - these notifications come immediately without delay. That is, it was not, it is delayed. I expand Unigram - it immediately appears. 
3) a Temporary solution to the problem that I found: if you close Unigram, it does not appear on the taskbar or in the tray, but for some reason it works in the task Manager. And in this case, all notifications begin to arrive without delay. 
If I click on the taskbar on unigram - it opens and the same problem occurs. 

I REALLY NEED YOUR HELP. WIndows 10, clean, activated. All drivers stand, there are no network delays. Both standard and private proxies were used, and nothing has changed. I even ordered a clean install of windows - nothing has changed

**Comment by MarcAnt01** [comment] 2020-02-23 11:06
Duplicate of https://github.com/UnigramDev/Unigram/issues/1206

**Closed by MarcAnt01** 2020-02-23 11:06 UTC
