### ISSUE TITLE
Windows 10 Share function not working

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#636] opened 2018-09-08 11:21 UTC
When selecting a file from apps that support Windows 10 Share function, like Photos or Desktop, I can see the possibility to share it though Unigram, but when it opens Unigram it does nothing

**Comment by FrayxRulez** [comment] 2018-09-13 16:29
Duplicate of #440

**Closed by FrayxRulez** 2018-09-13 16:29 UTC
Labels: duplicate

**Comment by MarcAnt01** [comment] 2018-09-13 16:52
Yep, right, but it mentions just photos, while the problem happens with every type of file

**Comment by FrayxRulez** [comment] 2018-09-13 16:52
I'll refactor it to be more generic
