### ISSUE TITLE
Folders support

### ISSUE THREAD

**Issue by Sav22999** [UnigramDev/Unigram#1625] opened 2020-05-21 11:15 UTC
Telegram released folders support officially, I would like using them also on Unigram 😄

**Comment by MarcAnt01** [comment] 2020-05-21 11:16
Duplicate of https://github.com/UnigramDev/Unigram/issues/1379

**Comment by FrayxRulez** [comment] 2020-05-21 11:16
Hello! We already have a ticket about folders, that are in the making (Mostly waiting for TDLib to be ready, at the moment): #1379

**Closed** 2020-05-21 11:16 UTC
