### ISSUE TITLE
"Dark blue" theme is only set to content part of the window

### ISSUE THREAD

**Issue by revanmj** [UnigramDev/Unigram#2656] opened 2022-02-14 07:48 UTC
**Describe the bug**
"Dark blue" theme is only set to the content (with chat or settings) part of the window. Titile bar, list and sidebar are set to "black dark" theme.

**To Reproduce**
1. Set Dark blue theme
2. See that list part is black dark, while settings part is dark blue

**Expected behavior**
Dark blue theme is properly set to whole window

**Screenshots**
![Zrzut ekranu 2022-02-14 084448](https://user-images.githubusercontent.com/1777618/153821556-68cfe7c6-c519-4e82-900a-7eea00f7d5a7.jpg)

**Version Info**
 - Unigram: 8.5.6960
 - Windows: 10.0.19044.1526 x64

**Comment by MarcAnt01** [comment] 2022-02-17 10:30
This is an issue due to Mica, we discussed about it in the Insiders group and currently there's no way to set it to a background color.

**Comment by revanmj** [comment] 2022-02-17 10:34
Since Mica is not available/working on Win10 either way, couldn't you only use it on Win11 so this bug would not occur on Win10?

**Comment by FrayxRulez** [comment] 2022-02-17 10:37
> Since Mica is not available/working on Win10 either way, couldn't you only use it on Win11 so this bug would not occur on Win10?

Yeah this must be fixed on 10

**Comment by Sugaroverdose** [comment] 2022-02-17 23:51
On my win11 machine it's broken in exact the same way 
Unigram: 8.5.6982
OS Build: 22000.493

**Comment by MarcAnt01** [comment] 2022-02-18 10:56
> On my win11 machine it's broken in exact the same way Unigram: 8.5.6982 OS Build: 22000.493
> 
> Found out that it's broken when using 'slideshow' wallpaper from folder, well, this feature isn't actually production ready >.>

On Windows 11 it's intended, since Mica cannot be rendered over a solid brush

**Comment by Sugaroverdose** [comment] 2022-02-18 18:32
> On Windows 11 it's intended, since Mica cannot be rendered over a solid brush
i guess it's better to have a choice to not use it than, since it breaks not only unsupported os version but also because of usage not that exotic feature

**Comment by FrayxRulez** [comment] 2022-04-01 10:41
This is definitely blocked as at the moment Mica doesn't support a fallback value for when it is disabled...

**Comment by FrayxRulez** [comment] 2024-11-21 12:07
I'd close this as by design

**Closed by FrayxRulez** 2024-11-21 12:07 UTC
Labels: blocked
