### ISSUE TITLE
"Arabic" is always highlighted in language settings

### ISSUE THREAD

**Issue by GameSpeck** [UnigramDev/Unigram#1433] opened 2020-04-26 12:13 UTC
Arabic language is highlighted by default despite the app's language is English and cursor is not hovering above the Arabic option
![image](https://user-images.githubusercontent.com/43648146/80307250-66ca0e80-87e5-11ea-90b7-e30aac8963f0.png)
While in Telegram:
![image](https://user-images.githubusercontent.com/43648146/80307259-78131b00-87e5-11ea-8485-233b474e515f.png)

**Comment by MarcAnt01** [comment] 2020-04-26 12:16
Duplicate of https://github.com/UnigramDev/Unigram/issues/1249

**Closed by MarcAnt01** 2020-04-26 12:16 UTC
