### ISSUE TITLE
Duplicate notifications on mobile; notifications synchronization between mobile and PC does not work

### ISSUE THREAD

**Issue by penartur** [UnigramDev/Unigram#559] opened 2018-03-14 17:27 UTC
(see also: #547)

I think that it has worked for some time (although I'm not sure), but now it does not work again:

![image](https://user-images.githubusercontent.com/1332951/37419163-e6c6ee6a-27c4-11e8-81c2-fed0a901f533.png)

PC version: 1.2.1562, mobile version: 1.1.1535.

What's even weirder, there are now 3 notifications for every message (I've experienced it with replies to my messages in a muted chat):

1) I receive a notification on PC, with chat logo;
2) I receive a notification on mobile (which is mirrored on PC, so I have two notifications on PC), with chat logo;
3) Once I open Unigram on mobile, I receive a third notification there, without chat logo; this one is not mirrored to PC.

![image](https://user-images.githubusercontent.com/1332951/37419544-c58f5a42-27c5-11e8-8b95-3422456ea1f8.png)

**Comment by FrayxRulez** [comment] 2018-03-14 17:36
Why shouldn’t I mark this as a duplicate of the previous issue?

**Comment by penartur** [comment] 2018-03-14 18:19
> Why shouldn’t I mark this as a duplicate of the previous issue?

Because previous issue was closed because it is thought to be resolved; and because this new issue also covers the problem of the third notification?

**Comment by FrayxRulez** [comment] 2018-03-15 15:58
You could have just reopened the other and added details there.

**Closed by FrayxRulez** 2018-03-15 15:58 UTC

**Comment by penartur** [comment] 2018-03-15 18:40
> You could have just reopened the other

I could not; only contributors can reopen issues IIRC.

But it is sorted out now I believe :)

**Comment by topkecleon** [comment] 2018-03-23 22:44
I am still experiencing this issue as of 4am this morning.
