### ISSUE TITLE
Share files via People Bar launches desktop app

### ISSUE THREAD

**Issue by kowalski7cc** [UnigramDev/Unigram#818] opened 2018-10-12 11:38 UTC
If I drag and drop a file on a contact on the people bar, it launches the main app asking for the message recipient.
Instead it should behave like if I'd drop the file on the people messages window while open. Maybe wold be great also add a dialog before actually sending the file (Like the mail app or skype)

**Comment by kowalski7cc** [comment] 2018-10-12 11:39
Something like this:
![image](https://user-images.githubusercontent.com/5065094/46867124-36e63080-ce24-11e8-9be0-b8f500233b8f.png)

**Comment by kowalski7cc** [comment] 2018-10-12 11:43
@kowalski7cc It was hard to find a contact that used Skype, 99% use only *gram as IM

**Comment by larsschellhas** [comment] 2018-10-14 06:36
Duplicate of #744

**Closed by larsschellhas** 2018-10-14 06:36 UTC
Labels: enhancement
