### ISSUE TITLE
in send to menu buttons are not clickable under header

### ISSUE THREAD

**Issue by alighamari** [UnigramDev/Unigram#1667] opened 2020-05-29 12:39 UTC
when i want to share a post or forward send to ... menu buttons are not fully clickable because they go under header of app 
![image](https://user-images.githubusercontent.com/24440862/83260453-0efd3980-a1cf-11ea-9114-39b795be2512.png)

**Comment by MarcAnt01** [comment] 2020-05-29 12:45
Duplicate of https://github.com/UnigramDev/Unigram/issues/1425

**Closed by MarcAnt01** 2020-05-29 12:45 UTC
