### ISSUE TITLE
unigram background feature (notifications)

### ISSUE THREAD

**Issue by ScoppyTech** [UnigramDev/Unigram#2571] opened 2021-12-17 08:51 UTC
hi, i want notifications from unigram as in background. same of WhatsApp beta UWP

**Comment by ScoppyTech** [comment] 2021-12-17 08:52
sorry for my bad english, i'm italian

**Comment by MarcAnt01** [comment] 2021-12-17 09:24
Hello, this is known

**Comment by MarcAnt01** [comment] 2021-12-17 09:24
Duplicate of https://github.com/UnigramDev/Unigram/issues/2210

**Closed by MarcAnt01** 2021-12-17 09:24 UTC
Labels: needs-triage
