### ISSUE TITLE
Can't reply from notifications

### ISSUE THREAD

**Issue by shmykelsa** [UnigramDev/Unigram#533] opened 2018-02-28 11:45 UTC
In action center, there's no reply field (which is a killer feature for me, over the official Telegram client)

Windows 10 for PC IP 17604

**Comment by xperiandri** [comment] 2018-03-03 18:12
See #542

**Comment by FrayxRulez** [comment] 2018-03-19 15:43
I'm going to close this as a duplicate of #49, just to not have tons of issues all about the same stuff.

**Closed by FrayxRulez** 2018-03-19 15:43 UTC
