### ISSUE TITLE
Add typing indication on My People

### ISSUE THREAD

**Issue by HammyHavoc** [UnigramDev/Unigram#922] opened 2018-12-09 18:18 UTC
It is really irksome to not have any indication that someone is typing when using Unigram in My People. Works really well in the main Unigram app. Would love to see this added, as otherwise, the app is largely perfect! :- )

**Comment by MarcAnt01** [comment] 2018-12-09 18:30
Duplicate of https://github.com/UnigramDev/Unigram/issues/840

**Comment by MarcAnt01** [comment] 2018-12-09 18:30
I haved editet the other issue to be more generic, including online status

**Closed by MarcAnt01** 2018-12-09 18:30 UTC
