### ISSUE TITLE
Double dash in Ukrainian localization under Members tab

### ISSUE THREAD

**Issue by harvasyuk** [UnigramDev/Unigram#2203] opened 2020-12-31 20:01 UTC
![Screenshot 2020-12-31 215838](https://user-images.githubusercontent.com/17803706/103424152-6e7f5580-4bb3-11eb-97b2-61e192d04aeb.png)

**Comment by harvasyuk** [comment] 2021-01-01 15:47
There's also too big gap between group title and subscribers number (in Ukrainian localization)
![Screenshot 2021-01-01 174557](https://user-images.githubusercontent.com/17803706/103441825-45190500-4c59-11eb-8495-4feb92811254.png)

**Comment by FrayxRulez** [comment] 2021-04-08 18:33
Second issue is caused by a wrong translation here: https://translations.telegram.org/uk/android/general/Subscribers
I've already submitted a fixed one, admins have to approve it.

**Closed** 2021-04-08 18:32 UTC
