### ISSUE TITLE
The back button of the navigation bar does not work properly in some cases

### ISSUE THREAD

**Issue by MiaoLuoNa** [UnigramDev/Unigram#2704] opened 2022-04-04 12:35 UTC
When you enter a "reply Interface",the "back" icon and it's real function seems to be not match
unigram 8.6(7333) 

https://user-images.githubusercontent.com/62191675/161544508-ac90a719-ce32-40a5-a7fe-c8fdf8be5c8d.mp4

**Comment by FrayxRulez** [comment] 2022-04-04 12:38
That's not a back button, that's the chat profile picture

**Comment by CuteCatXiao** [comment] 2022-04-04 13:16
It doesn't seem right I think.
Normally,click the icon which look like "reply" will not pop up a chat profile picture.

**Comment by FrayxRulez** [comment] 2022-04-04 13:23
> It doesn't seem right I think. Normally,click the icon which look like "reply" will not pop up a chat profile picture.

Yeah the problem is that it opens up the chat profile picture, but it's not a back button either :D

**Comment by FrayxRulez** [comment] 2022-09-04 11:48
Duplicate of #2718

**Closed by FrayxRulez** 2022-09-04 11:48 UTC
Labels: bug
