### ISSUE TITLE
Spellchecker does not respect Windows 10 Typing settings

### ISSUE THREAD

**Issue by hvonw** [UnigramDev/Unigram#1234] opened 2019-11-15 14:23 UTC
I have turned off all Windows 10 Typing stuff, but stilll Unigram corrects spelling. 
Can you guys please make it compatible with global Windows settings?

//https://github.com/UnigramDev/Unigram/blob/develop/Unigram/Unigram/Views/ChatPage.xaml#L963

Thanks,

**Comment by FrayxRulez** [comment] 2020-02-25 14:54
Hello, as far as I know there's no way to check for system spellchecker settings.

**Comment by FrayxRulez** [comment] 2020-02-25 14:56
Here documentation says that Windows should handle this by itself: https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/text-controls#guidelines-for-spell-checking

**Comment by FrayxRulez** [comment] 2020-02-25 15:13
Duplicate of #1226

**Closed by FrayxRulez** 2020-02-25 15:13 UTC
Labels: bug
