### ISSUE TITLE
Xbox doesn't support secondary windows

### ISSUE THREAD

**Issue by cryptedbv** [UnigramDev/Unigram#2642] opened 2022-02-04 11:26 UTC
**Describe the bug**
Most things work, however when doing a regular call or videocall, it does not load into it. Meaning you only see the 'return to call' above the chat. There is no way to get into it. The receiver does see the video and gets audio. So it seems like a client-side issue.

Version: Unigram 8.4.70 (6853) X64
Client: Xbox Series X

**To Reproduce**
Place a call/videocall. Simple.

**Expected behavior**
Seeing the call screen.

**Screenshots**
Unable, however, simple to imagine, regular client, 'return to call' bar above the chat. That's it.

**Version Info**
 - Unigram 8.4.70 (6853) X64
 - Xbox Series X

**Additional context**
None

**Comment by cam678889** [comment] 2022-12-13 11:33
> 

>    #`@@@`
Duplicate of  

>  #@#``

**Comment by FrayxRulez** [comment] 2024-10-20 12:24
This was "fixed" at some point.

**Closed by FrayxRulez** 2024-10-20 12:24 UTC
Labels: bug, xbox
