### ISSUE TITLE
Last seen bugged for people with last seen disabled

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#661] opened 2018-09-11 07:28 UTC
Last seen sometimes has bugs, it shows last seen instead of "is writing" or "online" status. I think this bug is brought about by TidLib, because I had the same issue on Telegram X for Android, anyway from two weeks this bug seems to have disappeared

**Comment by FrayxRulez** [comment] 2018-09-12 16:37
TDLib used by Unigram has been updated more recently than 2 weeks ago, and I can't reproduce this issue

**Comment by MarcAnt01** [comment] 2018-09-12 16:40
I've found out it happens just with people who disabled last seen (is typing should be shown anyway)

**Comment by FrayxRulez** [comment] 2018-09-13 15:59
Is typing is actually shown.

**Comment by MarcAnt01** [comment] 2018-09-13 16:02
I have noticed that it misbehaves after someone stops writing and start writing once again

**Comment by FrayxRulez** [comment] 2018-09-13 16:08
Online when someone has its status hidden is actually a local feature, that TDLib doesn't have.
I actually don't like the idea to have to implement this by myself, also because it's just a "fake" status (Typing? Then mark as online for X time, even if the other user goes offline, it will still be marked as online for that amount of time)
If you think that this feature is really needed you can try to create a ticket on [TDLib's repository](https://github.com/tdlib/td/).

**Closed by FrayxRulez** 2018-09-13 16:08 UTC

**Comment by MarcAnt01** [comment] 2018-09-13 16:16
OK, will try from there, thanks anyway
