### ISSUE TITLE
Current chat stops updating eventually.

### ISSUE THREAD

**Issue by starbird64** [UnigramDev/Unigram#175] opened 2017-02-08 17:58 UTC
Sometimes, doing nothing, inside a chat, you can send messages, but you're unable to see the received ones. New messages will be visible if you go to the chats list and return to the chat.

**Comment by larsschellhas** [comment] 2017-02-26 13:45
I had a chat open on my phone and received messages both there and in TG Desktop. 
But when I answered in TG Desktop the messages were not shown on the phone in Unigram until I reopened the chat.

**Comment by ADeltaX** [comment] 2017-02-26 13:47
@larsschellhas test

**Comment by larsschellhas** [comment] 2017-02-26 13:48
@larsschellhas As soon as a new message from the chat partner is received, the chat gets updated again.

**Comment by FrayxRulez** [comment] 2017-06-25 10:25
Can I consider this a duplicate of #71?

**Closed by FrayxRulez** 2017-06-25 10:25 UTC
Labels: bug
