### ISSUE TITLE
Live Tile and Lockscreen don't work properly

### ISSUE THREAD

**Issue by GeorgHoffmeyer** [UnigramDev/Unigram#329] opened 2017-07-10 06:02 UTC
In Version 0.3.443.0 the Live Tile shows unread messages long after they have been read. Also the counter on the counter on the Lockscreen is not updating (it shows one unread message after all messages have been read)

**Comment by FrayxRulez** [comment] 2017-07-13 08:58
Duplicate of #62

**Closed by FrayxRulez** 2017-07-13 08:58 UTC
