### ISSUE TITLE
Unable to receive notifications while the window is closed

### ISSUE THREAD

**Issue by swift-lee** [UnigramDev/Unigram#2514] opened 2021-09-06 12:59 UTC
**Describe the bug**
Both of me and my friend are now in China and using telegram by proxy. By default settings both of us are unable to receive notifications form Unigram (proxy is ok, I set proxy individually for Unigram, my friend set the system proxy). I'm using Windows 11, so I changed background settings to Always, then I am able receive notifications, but sadly he's still not. 

**To Reproduce**
1. Close the window
2. Unable to receive notifications and shows notification pop-ups for most of the time

**Expected behavior**
It SHOULD shows notification pop-ups.

**Version Info**
 - Unigram: 7.8.6586 x64
 - Windows: 22000.176 & 19043.1202

**Additional context**
Not a big deal, both my PCs are now Windows 11 and able to receive notifications, and my friend will get back to Japan in a few weeks. This issue can be low prioritized.

**Comment by MarcAnt01** [comment] 2021-09-06 13:10
Thanks for your bug report, but this is already known

**Comment by MarcAnt01** [comment] 2021-09-06 13:10
Duplicate of https://github.com/UnigramDev/Unigram/issues/2210

**Closed by MarcAnt01** 2021-09-06 13:10 UTC
Labels: bug, needs-triage

**Comment by swift-lee** [comment] 2021-09-06 13:12
> Duplicate of #2210

sry, I thought it might be something related to proxy settings or China's Internet condition🤐

**Comment by MarcAnt01** [comment] 2021-09-06 13:13
Don't worry, it's fine🙂👍
