### ISSUE TITLE
Silent Broadcast Bell

### ISSUE THREAD

**Issue by rei-zero246** [UnigramDev/Unigram#2867] opened 2022-10-16 12:17 UTC
**Describe the bug**
The silent broadcast bell does not have a line through it.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open Unigram from a closed state.
2. Open a Channel with Silent Broadcast.
3. Note the state of the bell icon.
4. Hover over the icon for it to be “fixed”.

**Expected behaviour**
Any time I open a Channel with Silent Broadcast, the bell icon should have a strike through it.

**Screenshots**
![Screenshot 2022-10-11 033055](https://user-images.githubusercontent.com/66904012/196034885-1315d7e6-d628-493f-8c8b-c6cb45f26e72.png)

![Screenshot 2022-10-11 033114](https://user-images.githubusercontent.com/66904012/196034888-1d2ba6cd-e486-4afd-997d-95e58f40c446.png)

**Version Info**
 - Unigram 9.0 (7796)
 - Windows 11 22H2

**Additional context**

**Comment by FrayxRulez** [comment] 2023-06-08 12:12
Does this still persist? I can't reproduce the issue

**Comment by MarcAnt01** [comment] 2023-08-18 10:36
Closing this, since no reply has been given after months

**Closed by MarcAnt01** 2023-08-18 10:36 UTC
Labels: can't reproduce
