### ISSUE TITLE
Titlebar and menu-button corrupted in tablet mode

### ISSUE THREAD

**Issue by disablesilence** [UnigramDev/Unigram#1748] opened 2020-06-08 07:41 UTC
I have 2-in-1 device on Windows 10 and use Tablet Mode. After the release of 4.0, the tablet mode began to appear the titlebar and the menu burger is overlaid on top of it...

Can you hide the title bar in tablet mode and move down the menu button? Or alternatively, enhance it with functionality. For now this titlebar is empty and rather useless.

![image](https://user-images.githubusercontent.com/7093126/84003930-f215f280-a994-11ea-8829-b825563fa498.png)

**Comment by FrayxRulez** [comment] 2020-06-08 07:49
Looks like no one tested tablet mode. 😄 
I would prefer to always keep the title bar, as due to what it seems to be a Windows bug the metrics for it are provided too late causing the app to flicker/glitch in normal windowed mode.
Another solution would be to get rid of the custom title bar completely, and this is one of the reasons I created this ticket: https://github.com/UnigramDev/Unigram/issues/1744

**Comment by hihain** [comment] 2020-06-08 09:16
The problem is that Windows hides the title bar in Tablet Mode and only shows it on hover.
This can be fixed by reverting a part of commit 08c8da1c - `MainPage.xaml.cs`

**Comment by FrayxRulez** [comment] 2020-06-08 09:21
> The problem is that Windows hides the title bar in Tablet Mode and only shows it on hover.
> This can be fixed by reverting a part of commit [08c8da1](https://github.com/UnigramDev/Unigram/commit/08c8da1c24521ea00dcf7a555a322c9d24f5a866) - `MainPage.xaml.cs`

https://github.com/UnigramDev/Unigram/commit/08c8da1c24521ea00dcf7a555a322c9d24f5a866 commit was made on purpose and it isn't going to be reverted for the problems I explained above.

**Comment by FrayxRulez** [comment] 2020-06-08 11:10
Fixed in https://github.com/UnigramDev/Unigram/commit/6d03882241b8c75ae605952d5c820430df90348f

**Closed by FrayxRulez** 2020-06-08 11:10 UTC
Labels: bug
