### ISSUE TITLE
Unigram auto-dark mode doesnt work properly

### ISSUE THREAD

**Issue by Serarg95** [UnigramDev/Unigram#1727] opened 2020-06-06 23:01 UTC
Unigram 4.0 (5077).

1. First of all, **apparently, automatic dark theme isnt working**, at least in my case. But Im probably testing it in a wrong way, i dont know.

2. When I program the auto dark theme starting at a **time lapse between 00:00 and 00:59** (both included), the **error attached** in this ticket appears. When I try to change the hour in order to avoid the error, the change doenst apply and the error persists, so im totally stucked with this error in auto-dark mode settings.
![image](https://user-images.githubusercontent.com/66536926/83956007-60ee3100-a859-11ea-897c-139f4c842fe2.png)

**Comment by FrayxRulez** [comment] 2020-06-07 07:37
2. is fixed in https://github.com/UnigramDev/Unigram/commit/f824efafcf72d54cb3a9adb978fe49012fd435fe

**Comment by FrayxRulez** [comment] 2020-06-13 14:43
And I'm not able to reproduce 1, so I'll close this.

**Closed by FrayxRulez** 2020-06-13 14:43 UTC
Labels: bug
