### ISSUE TITLE
Scroll to bottom icon always present after opening chats

### ISSUE THREAD

**Issue by TheGuardianWolf** [UnigramDev/Unigram#1336] opened 2020-02-16 20:36 UTC
This one may be related to #1334.

The scroll arrow on the bottom right is sometimes always present on first load, requiring you to scroll up and then down to clear. Clicking it doesn't do anything.

To reproduce, the current most reliable way is to keep opening different chats, with some chats having this issue sporadically.

![Image of arrow](https://i.imgur.com/oEwm1br.png)

**Comment by beerisgood** [comment] 2020-02-17 04:23
Can confirm.
Also scrolling a little bit to top and then back solve it.

**Comment by TheGuardianWolf** [comment] 2020-02-24 14:42
Tested this now, seems to be gone

**Comment by MarcAnt01** [comment] 2020-02-24 15:15
mmm, just happened to me, will check if it happens again

**Comment by TheGuardianWolf** [comment] 2020-02-25 19:46
It must have been hidden by the fact that loading chats is fast again.

I suspect it might have something to do with animations as it was triggered by slow loading.

**Comment by MarcAnt01** [comment] 2020-02-25 21:10
> I suspect it might have something to do with animations as it was triggered by slow loading.

I don't think so, it was present either with the delay or without it.

**Comment by TheGuardianWolf** [comment] 2020-02-26 07:03
I might not be any help on this then, it just shows up for like .1 second now and disappears if the chat was recent and I was at the bottom, otherwise it's there but it works if it was not recent.

**Comment by MarcAnt01** [comment] 2020-05-16 16:25
Unluckily, this issue persists somehow

**Comment by FrayxRulez** [comment] 2020-05-27 07:03
> Unluckily, this issue persists somehow

Show me a video

**Comment by MarcAnt01** [comment] 2020-05-27 07:13
Sure, will do as soon as it happens again

**Comment by FrayxRulez** [comment] 2020-06-05 11:56
I am still unable to reproduce this issue, so as this didn't happen again in 9 days I will close it again.

**Closed by FrayxRulez** 2020-06-05 11:56 UTC
Labels: bug, chat
