### ISSUE TITLE
Tab autocompletion should insert the command into the input instead of sending it

### ISSUE THREAD

**Issue by GingerPlusPlus** [UnigramDev/Unigram#986] opened 2019-02-17 13:38 UTC

**Comment by MarcAnt01** [comment] 2019-02-17 17:16
duplicate of https://github.com/UnigramDev/Unigram/issues/977

**Comment by MarcAnt01** [comment] 2019-02-17 17:16
If you want to add further information, just edit that issue

**Comment by GingerPlusPlus** [comment] 2019-02-17 17:18
They're related, but separate. That one is about autocomplete not working, this one is about it behaving differently than TDesktop.

**Comment by FrayxRulez** [comment] 2019-02-22 09:26
Why you created 4 issues about tab not being functional

**Closed by FrayxRulez** 2019-02-22 09:26 UTC
Labels: enhancement

**Comment by GingerPlusPlus** [comment] 2019-02-22 09:39
Because they're different issues with Tab

**Comment by FrayxRulez** [comment] 2019-02-22 09:41
Issue is the same, as the code for all of this stuff is in place already
