### ISSUE TITLE
Timestamp on stickers hide the content

### ISSUE THREAD

**Issue by mmischitelli** [UnigramDev/Unigram#2465] opened 2021-07-09 15:53 UTC
Ciao,
timestamps overlay on pictures and stickers often times make it impossible to read what's written behind.
Would it be nice to have the possibility to always have it hidden and maybe reveal it upon mouse over.

Example of the "issue" as of today:
![image](https://user-images.githubusercontent.com/6545806/125105226-88f43780-e0de-11eb-818d-2b688a3decf7.png)

**Comment by makisukurisu** [comment] 2021-07-09 16:04
@MarcAnt01 , may I ask you to assign Feature Request tag?

**Comment by FrayxRulez** [comment] 2021-08-01 12:44
Hiding it on mouse over and not vice versa isn't a bad idea

**Comment by MarcAnt01** [comment] 2022-03-20 16:15
This seems to be done in Telegram Desktop, maybe we can have the same behavior in Unigram
![image](https://user-images.githubusercontent.com/43090263/159171828-cf7390c5-c403-4c54-9f62-fa0694880a58.png)

**Comment by aerotan** [comment] 2023-03-08 16:29
If nothing else, a settings option to remove timestamps from media could be helpful, or to set a transparency for the timestamp bubble, would be helpful.

**Comment by FrayxRulez** [comment] 2023-05-01 17:39
Duplicate of #3001

**Closed by FrayxRulez** 2023-05-01 17:39 UTC
Labels: enhancement
