### ISSUE TITLE
Only have Windows notificaion when I receive private chats messages

### ISSUE THREAD

**Issue by MatrixLau** [UnigramDev/Unigram#1382] opened 2020-03-31 15:24 UTC
What about groups and channels?

**Comment by MarcAnt01** [comment] 2020-03-31 15:40
You have probably muted groups and channels, you can enable their notifications from chat info or chats list with right click

**Comment by MatrixLau** [comment] 2020-03-31 15:49
> You have probably muted groups and channels, you can enable their notifications from chat info or chats list with right click

no,i had opened it 'cause while i was using Telegram Desktop, the groups/channels that i didnt muted will have Windows10 notification.

**Comment by MarcAnt01** [comment] 2020-03-31 15:50
> > You have probably muted groups and channels, you can enable their notifications from chat info or chats list with right click
> 
> no,i had opened it 'cause while i was using Telegram Desktop, the groups/channels that i didnt muted will have Windows10 notification.

Muted and unmuted chats settings are cross platform

**Comment by MatrixLau** [comment] 2020-03-31 15:51
> > > You have probably muted groups and channels, you can enable their notifications from chat info or chats list with right click
> > 
> > 
> > no,i had opened it 'cause while i was using Telegram Desktop, the groups/channels that i didnt muted will have Windows10 notification.
> 
> Muted and unmuted chats settings are cross platform

so i know, 'cause i didnt mute they in any platform

**Comment by MarcAnt01** [comment] 2020-03-31 16:21
Are you having this problem with the app open or closed?

**Comment by MatrixLau** [comment] 2020-03-31 16:23
> Are you having this problem with the app open or closed?

tried both didnt have notification either

**Comment by MatrixLau** [comment] 2020-04-01 05:46
> Are you having this problem with the app open or closed?

No notification from windows but live tilttles have new notification

**Comment by Skyline404** [comment] 2020-04-01 20:01
> > Are you having this problem with the app open or closed?
> 
> No notification from windows but live tilttles have new notification
Same, live tiles updates, but no notifications

**Comment by realKimJonUn** [comment] 2020-04-02 01:46
Yes me too 
Firstly I can only got private messages notifications, cannot receive the group messages notifications,
Then I got none of them ……
I can’t receive any notifications now,

I already turned  all the notifications on , and I can get all notifications on my iPhone , but I got nothing on Unigram 😕

I reinstalled Unigram, but still the same,

I can’t figure it out, hope the next new Version!😕

**Comment by MatrixLau** [comment] 2020-04-02 01:46
@realKimJonUn Same

**Comment by MarcAnt01** [comment] 2020-04-07 09:43
Cannot reproduce, I receive notifications both from groups and from channels

**Comment by MatrixLau** [comment] 2020-04-07 09:46
> Cannot reproduce, I receive notifications both from groups and from channels

But not just my problem....

**Comment by FrayxRulez** [comment] 2020-04-07 09:48
Did you disable groups and channels notifications from notifications settings?

**Comment by MatrixLau** [comment] 2020-04-07 09:49
> Did you disable groups and channels notifications from notifications settings?
Just a problem in Unigram not in others. I checked that before i open this.

**Comment by MarcAnt01** [comment] 2020-04-07 09:57
> > Did you disable groups and channels notifications from notifications settings?
> > Just a problem in Unigram not in others. I checked that before i open this.

You have just quoted Fela's message with empty space

**Comment by MatrixLau** [comment] 2020-04-07 10:04
> Did you disable groups and channels notifications from notifications settings?

Just a problem in Unigram not in others. I checked that before i open this.

**Comment by MarcAnt01** [comment] 2022-03-28 13:32
Is this still a thing?

**Comment by MatrixLau** [comment] 2022-03-28 15:04
> Is this still a thing?

Dont know not using it nowdays

**Comment by FrayxRulez** [comment] 2022-08-29 12:19
I'm closing this unless someone can still reproduce the issue and can send logs to me

**Closed by FrayxRulez** 2022-08-29 12:19 UTC
Labels: needs-triage
