### ISSUE TITLE
Add Defult Interface scale 

### ISSUE THREAD

**Issue by AmirHsDev** [UnigramDev/Unigram#2700] opened 2022-04-01 13:50 UTC
Hello, please add the Default Interface scale feature in the next updates, my screen is large and unigram, its dimensions are very small.

**Comment by MarcAnt01** [comment] 2022-04-01 13:53
This isn't technically possible, you may consider adjusting it from system settings. You can find down above a ticket with a more complete explanation

**Comment by MarcAnt01** [comment] 2022-04-01 13:53
Duplicate of https://github.com/UnigramDev/Unigram/issues/2548

**Closed by MarcAnt01** 2022-04-01 13:53 UTC
Labels: needs-triage
