### ISSUE TITLE
@sticker bot shows placeholders

### ISSUE THREAD

**Issue by skrachkovsky** [UnigramDev/Unigram#730] opened 2018-09-21 11:14 UTC
Sticker shows placeholder on any emoji

![applicationframehost_2018-09-21_14-00-18](https://user-images.githubusercontent.com/32353818/45877501-bee99500-bda6-11e8-805e-de27ffc2ff0e.png)

**Comment by MarcAnt01** [comment] 2018-09-26 06:31
Duplicate of https://github.com/UnigramDev/Unigram/issues/690

**Closed by MarcAnt01** 2018-09-26 06:31 UTC
