### ISSUE TITLE
Shift+Click on new message notification hides currently displayed chat content

### ISSUE THREAD

**Issue by roman380** [UnigramDev/Unigram#621] opened 2018-08-23 09:14 UTC
When I read a chat and have a notification (toast) message from another chat, and Shift+Click on that notification indeed a new popup window with the new chat. 

In the same time, however, this deselects current chat in main window and hides the content originally displayed there.

**Comment by FrayxRulez** [comment] 2018-10-02 15:13
Fixed in https://github.com/UnigramDev/Unigram/commit/2560980197859b17dc616977c566d7aa6df0067a

I want to mention that shift+click on a notification isn't an intended behavior, and it might not work in future Windows/Unigram releases

**Closed by FrayxRulez** 2018-10-02 15:13 UTC
Labels: enhancement
