### ISSUE TITLE
Can not format image caption

### ISSUE THREAD

**Issue by Jeidoz** [UnigramDev/Unigram#2182] opened 2020-12-16 11:33 UTC
In official client I could made url-text by pressing Ctrl+K. Unigram even have RMB menu, but it does not react. Shortcut do nothing too. Tested only on links formatting.

![image](https://user-images.githubusercontent.com/23425714/102343419-d2dacc00-3f9a-11eb-9044-9f3509638236.png)

EDIT: It's glitchy or just not intuitive — after pressing Send button, URL format dialog appears. As many times, as I pressed to format text into link... 

![image](https://user-images.githubusercontent.com/23425714/102343858-5f858a00-3f9b-11eb-940e-86125ce94e62.png)

And if I cancel last dialog, text would not be formatted.

![image](https://user-images.githubusercontent.com/23425714/102343880-68765b80-3f9b-11eb-9c6b-f78468d1d291.png)

**Comment by MarcAnt01** [comment] 2020-12-16 11:39
That's a WinUI limitation, since you cannot open a ContentDialog on top of another one

**Comment by Jeidoz** [comment] 2020-12-16 12:42
Well, that's sucks... I hope in MIUI or in the next features in honor of .NET 5 that release some solution of it. 
Anyway, why you should show it in separated dialog, instead i.e. displaying/opening additional input field on the bottom of existing dialog? Sound like tricky solution idea...

**Comment by FrayxRulez** [comment] 2022-04-02 14:18
Duplicate of #2626

**Closed by FrayxRulez** 2022-04-02 14:18 UTC
Labels: blocked
