### ISSUE TITLE
[Feature] "Save as" option for video download

### ISSUE THREAD

**Issue by rixtox** [UnigramDev/Unigram#1827] opened 2020-06-17 00:34 UTC
Currently video can only be downloaded to the default temp folder. Should provide an option to allow custom download destination.

**Comment by FrayxRulez** [comment] 2020-06-17 10:20
You can use "Save as..." option after having downloaded the file in the temp folder. This is the default behavior at the moment and it can't be changed, as both TDLib and UWP app containers don't support this scenario. I am marking this ticket as a duplicate of #724 for now.

**Closed by FrayxRulez** 2020-06-17 10:20 UTC

**Comment by abh-oss01** [comment] 2020-06-17 10:22
@rixtox you can navigate to the temp folder, and copy or cut the video from there, to someplace else.

**Comment by rixtox** [comment] 2020-06-17 17:51
@FrayxRulez I think this is very different than having a default path setting. The idea of having a "Save as" option is to override any default settings for a specific file download. At least official Windows client supports this feature, I'm not sure how they implement it or are they using TDLib at all.

@abh-oss01 Your "workaround" _is_ the reason why I'm asking for this feature. Navigating into the temp folder, and move the file out from there, is no where near a good user experience because of:

1. No one wants to remember the path to the temp folder.
2. If you don't know the path to the temp folder, the only way for you to navigate to it is to wait till download finishes, and use "Show in Folder" option.
3. There can be hundreds of files in the temp folder, it's hard to find your file without using "Show in Folder" option.
3. If you have multiple downloads happening at the same time, you have to go back and find each of them in your chat history and use "Show in Folder" on each file.
4. Sometimes I just can't remember from which channel I initiated a download, and would spend a lot of time just to find it.

**Comment by FrayxRulez** [comment] 2020-06-17 17:53
Official Telegram app isn't using TDLib, so they don't really have this problem.

**Comment by FrayxRulez** [comment] 2020-11-21 18:59
Implemented in https://github.com/UnigramDev/Unigram/commit/0582da784c50ffe1cdb8d8027caa5a8e24bc3ce0
