### ISSUE TITLE
When sending a file, Pressing enter when the schedule message is selected sends it immediately

### ISSUE THREAD

**Issue by sukiletxe** [UnigramDev/Unigram#2646] opened 2022-02-07 09:37 UTC
**Describe the bug**
If I send a file, then activate the more options menu and press enter on the schedule option, the message is sent immediately.

**To Reproduce**
1. Open a chat.
2. Clic on Attach Multimedia, then file.
3. Select a file, press more options, and then press enter on schedule message.
4. The message is sent immediately.

**Expected behavior**
The schedule message dialog is shown.

**Version Info**
 - Unigram: 8.5 (6926) X64 Direct
 - Windows: 21h2 (19044.1466)

**Comment by makisukurisu** [comment] 2022-02-15 13:53
When selecting "schedule message" with a keyboard you have to use Ctrl+enter. Because plain enter sends message. Afaik that's intended.

**Comment by sukiletxe** [comment] 2022-02-15 14:21
I believe the intended behaviour from a keyboard perspective would be that enter sends the message only when the edit box or the send button is pressed.

**Comment by FrayxRulez** [comment] 2022-02-15 14:26
That would be the case in the perfect world. The reality is that most users want to send messages _any time_ and unfortunately that way it becomes hard to distinguish when that's good and when it is not.

**Comment by FrayxRulez** [comment] 2022-02-15 14:26
(Maybe we could still keep this ticket open)

**Comment by FrayxRulez** [comment] 2022-04-01 10:56
This is a duplicate of #2561

**Closed by FrayxRulez** 2022-04-01 10:56 UTC
Labels: bug
