### ISSUE TITLE
Ambiguous names for audio files 

### ISSUE THREAD

**Issue by entdark** [UnigramDev/Unigram#1174] opened 2019-07-06 14:39 UTC
When you share an audio file it displays "{Artist} - {Title}" in the message.
But sometimes you send an audio file that has "Unknown Artist - Unknown Title" or similar in the message.
And after sending multiple similar files when you go to a page with sent Audio files you cannot identify which file is which.

Could you make an option to display files in messages with their actual file names instead of meta data, please?

**Comment by entdark** [comment] 2019-07-09 10:17
Some investigations: it displays actual file names on both iOS and Android official applications.

**Comment by FrayxRulez** [comment] 2019-10-30 18:46
I'm not able to reproduce this issue honestly. Could you send me a sample file at @FrayxRulez?

**Comment by FrayxRulez** [comment] 2019-11-14 13:11
I'll consider this as fixed 🤷‍♂

**Comment by entdark** [comment] 2019-11-15 12:13
> I'll consider this as fixed 🤷‍♂ feel free to reopen it

Definitely not fixed. Once I have time, I will reopen. Thanks.

**Comment by entdark** [comment] 2019-11-17 16:59
@FrayxRulez
It displays
"Oxide & Sasha Voron - Unknown title"
"Oxide & Sasha Voron - Unknown title"

And it's hard to know which file is which.

It expected to be displayed with actual file names "Oxide_Sasha_Voron_Breaks_Session_Birthday_mix_2_cd3.mp3"
"Oxide_Sasha_Voron_Breaks_Session_Birthday_mix_2_cd1.mp3"

Unigram
https://i.imgur.com/ZJpCzwK.png
Telegram on iOS:
https://i.imgur.com/sQS2qVh.png

**Comment by entdark** [comment] 2019-12-24 10:54
Could this be reopened? I cannot do that myself.

**Comment by MarcAnt01** [comment] 2019-12-24 10:56
Sure (if a collaborator or an org member closes a ticket, users can't reopen them by themselves)

**Comment by FrayxRulez** [comment] 2021-04-10 14:29
I believe that this is fixed now

**Closed by FrayxRulez** 2021-04-10 14:29 UTC
Labels: bug
