### ISSUE TITLE
Pinned people. Exception

### ISSUE THREAD

**Issue by akusmin** [UnigramDev/Unigram#422] opened 2017-10-18 18:26 UTC
W10 fall update has an option to pin people to task bar and have a chat to pinned people.

If i have unigram app open and start chat from pinned person i have following exception

![image](https://user-images.githubusercontent.com/13545868/31735515-d5a8a9d6-b44a-11e7-94bc-32864bf868e6.png)

**Comment by FrayxRulez** [comment] 2017-10-18 18:28
Duplicate of #375

**Closed by FrayxRulez** 2017-10-18 18:28 UTC
