### ISSUE TITLE
Improving displaying emojis

### ISSUE THREAD

**Issue by jp-weber** [UnigramDev/Unigram#960] opened 2019-01-21 18:51 UTC
By using the emojis system font, there is a problem that older Windows versions can no longer display newer symbols. Couldn't you embed the Windows emoji font into the app as a workaround? This way you can see all emojis, but in fact only use the symbols installed by the system.

**Comment by MarcAnt01** [comment] 2019-01-21 19:17
Duplicate of https://github.com/UnigramDev/Unigram/issues/938

**Closed by MarcAnt01** 2019-01-21 19:17 UTC

**Comment by MarcAnt01** [comment] 2019-01-21 19:32
The stuff is the same, Windows doesn't support them and definitely not Unigram-side

**Comment by jp-weber** [comment] 2019-01-21 19:36
But why isn't the workaround considered?? it looks terrible if emojis are not displayed in the text. This problem would not occur with emojione for example.

**Comment by MarcAnt01** [comment] 2019-01-21 19:38
Just update Windows 10

**Comment by FrayxRulez** [comment] 2019-01-21 19:43
I’d like to fully replace emojis font with one containing Apple-like emojis, but to create one we need a software that costs ~500$ and that I’m not really able to use anyway

**Comment by MarcAnt01** [comment] 2019-01-21 19:44
Unigram is built to be optimised with latest version of OS available and as all PCs can be updates, you can't blame the team not to bring specific stuff for old versions.
