### ISSUE TITLE
Feature request: add "Share" option to context menu for links in messages

### ISSUE THREAD

**Issue by Kenya-West** [UnigramDev/Unigram#2806] opened 2022-08-17 07:27 UTC
Not many apps support Windows' native "Share" contract, but when they do, some other apps lack of sharing feature from their end.

For example, me using PocketX app that support such contract - it appears in Share modal. Unigram, from the other hand, does not support sharing links.

Please, add Share button to context menu to enrich native experience.

**Comment by MarcAnt01** [comment] 2022-08-17 08:47
Duplicate of https://github.com/UnigramDev/Unigram/issues/1384

**Comment by FrayxRulez** [comment] 2022-08-17 08:47
I'm not sure this is a duplicate

**Closed by MarcAnt01** 2022-08-17 08:47 UTC
Labels: needs-triage

**Comment by MarcAnt01** [comment] 2022-08-17 09:10
> some other apps lack of sharing feature from their end

> Please, add Share button to context menu to enrich native experience

Definitely a duplicate to me

**Comment by FrayxRulez** [comment] 2022-08-17 09:11
He's asking to share for links specifically, you're asking to share unspecified content in general.

**Comment by MarcAnt01** [comment] 2022-08-17 09:18
> He's asking to share for links specifically, you're asking to share unspecified content in general.

Well, to support sharing links the app still needs to support share target, which is what my ticket is about. If it gets added we can discuss about which things could be shared and from where, this ticket offers a good example of one of them
