### ISSUE TITLE
Filters are not working properly on windows client after latest update

### ISSUE THREAD

**Issue by 200mpx** [UnigramDev/Unigram#1366] opened 2020-03-11 11:26 UTC
If I use filters I have now weird selection for Private Chats - I have bots in it - and Groups - I have all Channels in it and that sucks!

Here is the screenshot with Groups filter and all Channels in it:
![image](https://user-images.githubusercontent.com/10790252/76412138-23861e80-63a4-11ea-8387-fd5b456c00af.png)

**Comment by MarcAnt01** [comment] 2020-03-11 12:43
Duplicate of https://github.com/UnigramDev/Unigram/issues/1352

**Comment by FrayxRulez** [comment] 2020-05-15 17:47
Fixed 👌

**Closed by FrayxRulez** 2020-05-15 17:47 UTC
Labels: bug
