### ISSUE TITLE
drag links and text from unigram to other apps and to the message box 

### ISSUE THREAD

**Issue by Poopooracoocoo** [UnigramDev/Unigram#2148] opened 2020-11-24 09:05 UTC
a feature request. i prefer dragging and dropping as opposed to copying links. just clicking on a link can be unpredictable as you may have different windows spread over multiple virtual desktops for example.

**Comment by FrayxRulez** [comment] 2022-04-02 19:12
Duplicate of #1916

**Closed by FrayxRulez** 2022-04-02 19:12 UTC
Labels: feature request
