### ISSUE TITLE
Support poll bot links sharing

### ISSUE THREAD

**Issue by xperiandri** [UnigramDev/Unigram#706] opened 2018-09-17 12:06 UTC
Register @poll bot
Create poll
The will be a link in it to share it.

When you tap that link in web version the share dialog opens and I can choose a group to share it. But nothing happens in Unigram

**Comment by FrayxRulez** [comment] 2018-09-17 12:10
There's no bot named @poll...

**Comment by MarcAnt01** [comment] 2018-09-17 12:12
@FrayxRulez Try t.me/vote, I got an error too with it

**Comment by DarthJahus** [comment] 2018-09-17 12:12
@MarcAnt01

**Comment by MarcAnt01** [comment] 2018-09-17 12:13
@DarthJahus Reason of tag?

**Comment by alighamari** [comment] 2018-09-17 12:26
he mean links like http://t.me/PollBot?startgroup=0d11680708568e510637488238c49c19

**Comment by MarcAnt01** [comment] 2018-09-17 12:27
@alighamari Yep, common problem to all pool bots

**Comment by alighamari** [comment] 2018-09-17 12:56
can we change the title to add support for all action links 
like t.me/{0}?startgroup or tg://{0}?startgroup 
this action adds the {0} to groups send start@{0} with a token like "0d11680708568e510637488238c49c19"

**Comment by FrayxRulez** [comment] 2018-09-19 19:10
Duplicate of #574

**Closed by FrayxRulez** 2018-09-19 19:10 UTC
Labels: enhancement
