### ISSUE TITLE
Crash or freeze when typing

### ISSUE THREAD

**Issue by Jack-Works** [UnigramDev/Unigram#2895] opened 2022-11-10 04:19 UTC
**Describe the bug**
Crash or freeze when typing.

**Version Info**
 - Unigram: 9.0 (7863) x64
 - Windows: 22H2, 22622.601

**Additional context**
Happens randomly. Is there any way I can provide some kind of dump file or crash log to help investigate the problem?

**Comment by Jack-Works** [comment] 2022-11-10 04:26
```
Faulting application name: Unigram.exe, version: 1.0.0.0, time stamp: 0x63622bad
Faulting module name: Windows.UI.Xaml.dll, version: 10.0.22621.601, time stamp: 0xe9790e69
Exception code: 0xc000027b
Fault offset: 0x000000000047bfd8
Faulting process id: 0x0x2C34
Faulting application start time: 0x0x1D8F4BB2916D66D
Faulting application path: C:\Program Files\WindowsApps\38833FF26BA1D.UnigramPreview_9.0.7863.0_x64__g9c9v27vpyspw\Unigram.exe
Faulting module path: C:\Windows\System32\Windows.UI.Xaml.dll
Report Id: 81d819e8-9184-4f21-b7f7-1efc0671dcb0
Faulting package full name: 38833FF26BA1D.UnigramPreview_9.0.7863.0_x64__g9c9v27vpyspw
Faulting package-relative application ID: App
```

**Comment by Jack-Works** [comment] 2022-11-10 04:26
🤔 Xaml is crashing?

**Comment by FrayxRulez** [comment] 2022-11-10 08:38
I believe that this actually happens, some times, when the text that you're typing wraps into multiple lines, but this is really hard to reproduce and even reproducing it the issue is not obvious...

**Comment by Jack-Works** [comment] 2022-11-10 10:23
Is there a switch or something like that I can collect a detailed crash log? I can reproduce this frequently, the input text slows down and crash

**Comment by FrayxRulez** [comment] 2022-12-02 16:41
Just realized that this is a duplicate of #2630

**Closed by FrayxRulez** 2022-12-02 16:41 UTC
Labels: bug
