### ISSUE TITLE
High battery usage while running in background

### ISSUE THREAD

**Issue by dosisimone** [UnigramDev/Unigram#2625] opened 2022-01-17 00:46 UTC
During these days I often leave my laptop closed after some calls with by gf and when I go back to it after some hours it is really hot on the back and the battery decreased considerably (7-15% / hour).
Windows 11 in the last hour (when I never used the PC and it was in sleeping state) reports to me 8% battery draining with 98% caused by Unigram in the background.
I'm running Windows 11 on a Dell Xps 15 9510 (I7 11800H).

**Comment by FrayxRulez** [comment] 2022-04-01 10:48
You can disable system tray icon to improve battery life in this situations

**Comment by trs80** [comment] 2022-04-09 14:35
What situation? Everyone who has a laptop that wants to close it without the battery draining as if it was on all the time? I was trying to work out why my laptop was draining the battery when closed, `powercfg /sleepstudy` shows that it's Audio Service - TimerForAudioPlayback - 38833FF26BA1D.UnigramPreview_g9c9v27vpyspw!App.

**Comment by MarcAnt01** [comment] 2022-04-09 14:43
I used the command you suggested, but couldn't find the information about Unigram process could you be more detailed?

**Comment by trs80** [comment] 2022-04-10 15:23
Expand the Activators for a period of sleep with high power draw and you should see it:

![image](https://user-images.githubusercontent.com/111810/162626740-cb6b6d78-831c-4bb0-bde9-f6f8fb9a07ec.png)

**Comment by FrayxRulez** [comment] 2022-09-04 13:09
Marking this ticket as a duplicate of #2801 as the newer ticket is slightly more detailed.

**Closed by FrayxRulez** 2022-09-04 13:09 UTC
Labels: wontfix
