### ISSUE TITLE
Settings sidebar doesn't retract via Esc if a chat is open

### ISSUE THREAD

**Issue by KeronCyst** [UnigramDev/Unigram#2505] opened 2021-08-23 20:45 UTC
Unigram 7.8 (6586) x64 on Windows 10 Home 21H1:

1. Open any individual chat or group chat (but not a channel; those work fine, for… some reason)
2. Click the upper-left menu button (or tab over and hit Space or Enter to press it)
3. While that sidebar is open, Press Alt-Tab or Win-A or do anything else to lose focus on Unigram
4. Regain focus (press Alt-Tab again, close the Action Center with Esc, etc.)
5. Press Esc

Expected result:
The sidebar pane should close first, before anything else happens

Current result:
The chat closes, while the pane stays open and seems immune to any immediate presses of Esc

**Comment by MarcAnt01** [comment] 2021-08-23 21:00
Thanks for reporting, but there's already an old ticket about this

**Comment by MarcAnt01** [comment] 2021-08-23 21:00
Duplicate of https://github.com/UnigramDev/Unigram/issues/1099

**Closed by MarcAnt01** 2021-08-23 21:00 UTC
