### ISSUE TITLE
Minimize to tray option

### ISSUE THREAD

**Issue by BehdadEs** [UnigramDev/Unigram#1070] opened 2019-04-21 17:13 UTC
Hey 
Is there anyway to add an option to change the behavior of close button so whenever you click on it instead of closing the app, it goes to system tray?
thanks

**Comment by MarcAnt01** [comment] 2019-04-21 17:16
Duplicate of https://github.com/UnigramDev/Unigram/issues/1009

**Closed by MarcAnt01** 2019-04-21 17:16 UTC
