### ISSUE TITLE
Quite so often unread message markers freeze and fail to reset

### ISSUE THREAD

**Issue by roman380** [UnigramDev/Unigram#616] opened 2018-07-24 09:10 UTC
This tends to be more frequent in recent 1594 build on Windows 10, even though the problem was earlier too. Once in a while the app works about right, but unread posts keep being marked regardless of their presentation. Typically the app gets into such state, esp. in complicated scenarios e.g. when PC went to sleep then woke up, and I can read the chats freely, switch between them, scroll up and down including clicking on the arrow to scroll to newest - and the unread message count is not affected in every chat. I need to close the app and restart it, and the counters start working as expected.

UPD. I just had this state. I closed the app using the [x] in the top right corner and started it immediately again. Apparently it started into the same state, however unread counter was working well from there.

**Comment by FrayxRulez** [comment] 2018-09-19 19:07
Seems that when launching debug builds this doesnt' happen.
The only condition where messages aren't marked as read is when the window isn't focused, so I'm wondering what should I do to get this value in a more reliable value :(

**Comment by roman380** [comment] 2018-09-19 19:28
I see but it does happen from time to time, I have it perhaps once every a couple of days and last time it was today.

**Comment by FrayxRulez** [comment] 2018-09-19 19:32
I noticed this as well in certain conditions, haven't been able yet to reproduce this programmatically.
The only way to determine if the window is active is by tracking `Window.Activated` event. I don't know what to do more than this.

**Comment by FrayxRulez** [comment] 2018-09-19 19:39
All the login is here:
https://github.com/UnigramDev/Unigram/blob/c2c18bbc24a4045980ef79d713d34c7ac22aba3e/Unigram/Unigram/Common/WindowContext.cs#L48
https://github.com/UnigramDev/Unigram/blob/c2c18bbc24a4045980ef79d713d34c7ac22aba3e/Unigram/Unigram/Common/WindowContext.cs#L170
https://github.com/UnigramDev/Unigram/blob/c2c18bbc24a4045980ef79d713d34c7ac22aba3e/Unigram/Unigram/Views/ChatPage.Bubbles.xaml.cs#L118

**Comment by FrayxRulez** [comment] 2018-09-19 19:42
Would be useful if you can tell me if when messages aren't marked as read gifs are still being autoplayed or not

**Comment by roman380** [comment] 2018-09-19 19:46
It might be hard to tell since I don't have many of them but I will have a look. 

Another thing I thought of was I cannot tell you whether it's just messages not marked or in the same time they also stop getting updated - I will check this as well. I can open web version side by side and check when I have any new messages and if they get to Unigram.

**Comment by FrayxRulez** [comment] 2018-09-19 19:47
They are still updated, no worries about this.
Next time it happens just open a chat and send a gif there, this would be useful to determine where the problem is.

**Comment by roman380** [comment] 2018-09-19 19:58
OK, I just had it stuck out of the blue. So one of the chats keeps the most recent message unread. Switching chats and going back does not reset the state. Scrolling down does not reset the state.

Right there in the chat window I sent https://media.giphy.com/media/Z8pzh8afGbZle/giphy.gif link. Recipient received it immediately (on his device). 

I see it like this:
![image](https://user-images.githubusercontent.com/11475832/45777739-593ec100-bc5f-11e8-908b-06e6eb7d3f89.png)

Clicking on GIF marker loads and plays the animation.

I have Autoplay GIF setting set to ON under settings.

**Comment by roman380** [comment] 2018-09-19 20:00
Also, when I returned back from settings to chat window, the read state was reset and GIF started automatic playback without my clicking it.

**Comment by FrayxRulez** [comment] 2018-09-24 22:13
Closing as this is fixed :)

**Closed by FrayxRulez** 2018-09-24 22:13 UTC
Labels: blocked, bug
