### ISSUE TITLE
Show list of People Who reacted to a message in a group

### ISSUE THREAD

**Issue by EryX0** [UnigramDev/Unigram#2871] opened 2022-10-17 20:56 UTC
so, basically the title, the ability to  look list of users who have reacted to certain message in a group is super necessary.
this feature is available on Telegram both desktop and mobile, on Telegram desktop it can be done by right clicking on or next to the message and then choosing the option to see the list of users who have reacted with their reactions.

expected behavior :

![image](https://user-images.githubusercontent.com/80907690/196283436-3a43a50c-3207-4500-9e75-a6e1da91422c.png)

**Comment by FrayxRulez** [comment] 2022-10-25 19:52
Duplicate of #2637

**Closed by FrayxRulez** 2022-10-25 19:52 UTC
Labels: needs-triage
