### ISSUE TITLE
Decrease minimum thickness of ink

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#2397] opened 2021-05-31 09:53 UTC
The maximum thickness in the photo editor is too thick compared for example to OneNote for example
Unigram
![image](https://user-images.githubusercontent.com/43090263/120219021-dc9b7780-c23a-11eb-9467-aec5f209c282.png)
OneNote
![image](https://user-images.githubusercontent.com/43090263/120219086-f63cbf00-c23a-11eb-917a-9d4f3b16e0d8.png)

**Comment by amirmahdifard0** [comment] 2021-05-31 10:17
@MarcAnt01 Please report the problems correctly. You have two parts to write text when reporting a problem. One as the problem and another description. You just complete the title field and do not complete the description. Please observe this. thanks.

**Comment by makisukurisu** [comment] 2021-05-31 10:18
Lel. What do you imagine name to be, then?

**Comment by MarcAnt01** [comment] 2021-05-31 11:13
> @MarcAnt01 Please report the problems correctly. You have two parts to write text when reporting a problem. One as the problem and another description. You just complete the title field and do not complete the description. Please observe this. thanks.

Not sure if you realized that you're telling the repo moderator what to do

**Comment by FrayxRulez** [comment] 2022-09-04 14:28
Duplicate of #1633
Please move any additional info to that ticket

**Closed by FrayxRulez** 2022-09-04 14:28 UTC
Labels: enhancement

**Comment by MarcAnt01** [comment] 2022-09-04 18:32
congrats to myself, I managed to create once again a duplicate of my own ticket 🤡
