### ISSUE TITLE
photo previews are not displayed in the gallery

### ISSUE THREAD

**Issue by ost4k** [UnigramDev/Unigram#2794] opened 2022-07-26 11:06 UTC
**Describe the bug**
When you go to the gallery chat only video materials are visible, photo previews are not displayed

**To Reproduce**
1. open any dialogue
2. click on the person's profile
3. scroll down to see the gallery
4. only videos are shown, no images

**Expected behavior**
When you go to the chat gallery, you can see both photos and videos

**Screenshots**
![image](https://user-images.githubusercontent.com/75425378/180991259-e94f813a-a2bd-446a-a2af-1d601f403416.png)

**Version Info**
 - Unigram: 8.9 (7454)
 - Windows: 11 22h2

**Comment by makisukurisu** [comment] 2022-08-01 18:41
Have you changed downloads location? If you did change download location - please, update the issue to include this info (preferably in the title and in additional info)

**Comment by ost4k** [comment] 2022-08-01 18:54
yes, if you reset the download location then everything is ok. but this solution sucks

**Comment by FrayxRulez** [comment] 2022-09-04 16:46
Duplicate of #2180

**Closed by FrayxRulez** 2022-09-04 16:46 UTC
Labels: bug, prio:low
