### ISSUE TITLE
Unhandled Exception after change left panel size

### ISSUE THREAD

**Issue by DefiCzech** [UnigramDev/Unigram#1136] opened 2019-05-29 17:41 UTC
This error appear after change left panel size (Unigram version 3.9.2468)
![image](https://user-images.githubusercontent.com/2785663/58578634-8a897b00-8249-11e9-9e1f-5ee4372139cb.png)

**Comment by MarcAnt01** [comment] 2019-05-29 17:45
Duplicate of https://github.com/UnigramDev/Unigram/issues/1121

**Closed by MarcAnt01** 2019-05-29 17:45 UTC
