### ISSUE TITLE
Clicking handles in stickers popup should close the sticker popup

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#2888] opened 2022-11-08 16:14 UTC
After clicking on the handle, Unigram should close the popup, otherwise the user would have to do it.

To reproduce https://t.me/addstickers/FluentEmoji1

**Comment by FrayxRulez** [comment] 2023-06-09 11:47
Duplicate of #1526

**Closed by FrayxRulez** 2023-06-09 11:47 UTC
Labels: enhancement
