### ISSUE TITLE
Multiple photos in a chat may show a download icon when it's not neccessary

### ISSUE THREAD

**Issue by XeZrunner** [UnigramDev/Unigram#1378] opened 2020-03-27 16:05 UTC
[Screenshot of the issue](https://imgur.com/a/I787ihy)

When I receive 2 or more photos, the first picture shows a download button that shouldn't appear. The image did download, and clicking on the download symbol previews the image. I can also switch to it from other pictures during previewing.

The download symbol does not disappear upon clicking on it.

Data saver-related options are not enabled & storage settings do not prevent images from downloading automatically.

Unigram version 3.14.2691 from the Microsoft Store
Windows 10 1909 _build 18363.3.752_

**Comment by MarcAnt01** [comment] 2020-03-27 18:05
Duplicate of https://github.com/UnigramDev/Unigram/issues/1156

**Closed by MarcAnt01** 2020-03-27 18:05 UTC
