### ISSUE TITLE
Upgrade to TDLib?

### ISSUE THREAD

**Issue by superusercode** [UnigramDev/Unigram#526] opened 2018-02-01 09:05 UTC
See the posts Telegram has made [here](https://core.telegram.org/tdlib) and [there](https://telegram.org/blog/tdlib) regarding the advantages and how it was used to make [Telegram X](https://play.google.com/store/apps/details?id=org.thunderdog.challegram&hl=en).

**Comment by FrayxRulez** [comment] 2018-02-01 09:05
Duplicate of #525

**Closed by FrayxRulez** 2018-02-01 09:05 UTC
