### ISSUE TITLE
Opening contact from People app does not select it in Unigram

### ISSUE THREAD

**Issue by xperiandri** [UnigramDev/Unigram#302] opened 2017-06-16 14:41 UTC
1. Open contact in People app
2. Click on Unigram icon or Send message item
3. Unigram opens but contact is not being selected

**Comment by FrayxRulez** [comment] 2017-06-16 14:42
Duplicate of #297

**Closed by FrayxRulez** 2017-06-16 14:42 UTC

**Comment by xperiandri** [comment] 2017-06-16 15:16
But when I do this no exception message appear. Is it swallowed?

**Comment by FrayxRulez** [comment] 2017-06-16 15:38
It's the same issue, with error message or not, this ticket might be more generic, but I keep the other one as older
