### ISSUE TITLE
BubbleMessage UI glitch: text hiding other text

### ISSUE THREAD

**Issue by hihain** [UnigramDev/Unigram#1573] opened 2020-05-11 22:34 UTC
Left: original desktop App; right: Unigram.
The text below the quiz should be displayed in both cases the same (like on the left).
![photo_2020-05-12_00-31-50](https://user-images.githubusercontent.com/1473059/81618613-02639d80-93e8-11ea-852e-51826e6f4505.jpg)

**Comment by FrayxRulez** [comment] 2020-05-12 06:50
That’s not easy at all as they’re completely different UI components. 
I’m not sure this is worth fixing.

**Comment by MarcAnt01** [comment] 2020-05-12 07:04
Duplicate of #1315

**Closed** 2020-05-12 07:04 UTC
