### ISSUE TITLE
"Message" placeholder superimposed on the Show formatting bar when recording a voice message

### ISSUE THREAD

**Issue by jvlianodorneles** [UnigramDev/Unigram#1999] opened 2020-09-13 19:41 UTC
### Steps to reproduce
1. Start to record a voice message, with **Show formatting** bar active.

### Expected behaviour
Hide "Message" placeholder when recording a voice message.

### Actual behaviour
The "Message" placeholder is superimposed on the **Show formatting** bar.

### Configuration
**Operating system:** Windows 10 Home compilation 19041.264.

**Version of Unigram:** 7.0 (5309).

**Used theme**: Default.

![Message](https://i.imgur.com/Hrx4Lfq.png)

**Comment by FrayxRulez** [comment] 2021-04-10 18:14
Duplicate of ##1840

**Closed by FrayxRulez** 2021-04-10 18:14 UTC
Labels: visual
