### ISSUE TITLE
Timestamps for video and audio

### ISSUE THREAD

**Issue by mikekosulin** [UnigramDev/Unigram#2239] opened 2021-02-11 17:47 UTC
Add possibility to add a timestamp to a video caption or reply(voice message, video-message, video), which will link to that exact moment in the footage
https://twitter.com/telegram/status/1161329992652845056?lang=en

**Comment by cewbdex** [comment] 2021-03-15 06:43
Duplicate of #1747

**Closed by cewbdex** 2021-03-15 06:43 UTC
Labels: missing feature
