### ISSUE TITLE
ability to search in (send menu)

### ISSUE THREAD

**Issue by samij263** [UnigramDev/Unigram#642] opened 2018-09-09 11:49 UTC
In send (forward) menu, "search" doesn't work

**Comment by MarcAnt01** [comment] 2018-09-09 12:01
It should have been fixed in this commit https://github.com/UnigramDev/Unigram/commit/ae83f39280995a10afd2278f8763a52b8c68aa5c

**Comment by amirso94** [comment] 2018-09-09 12:10
no it's not. i still have this issue on mobile & PC

**Comment by MarcAnt01** [comment] 2018-09-09 12:12
Yep, bro, I was wrong, in fact I have deleted comment not to create confusion

**Comment by amirali013** [comment] 2018-09-10 06:32
@samij263 😍

**Comment by FrayxRulez** [comment] 2018-09-13 13:15
Duplicate of #339

**Closed by FrayxRulez** 2018-09-13 13:15 UTC
Labels: duplicate
