### ISSUE TITLE
When sharing an image to Unigram, one cannot share to currently selected chat

### ISSUE THREAD

**Issue by roman380** [UnigramDev/Unigram#614] opened 2018-07-18 08:54 UTC
If I try to share an image from external application to Unigram, I have Unigram brought into foreground in whatever its current state is. Nothing happens until I select a new item in Chats. Then I have a prompt to share. This gives a few confusions:

1.  I cannot share to currently selected chat. Sharing prompt pops up only when I reselect another chat
2. If I am in settings or alike I might need to continue working with the app and it might take a few click before I reach Chats and select a new entry. It might so happen that I already forgot about image sharing (thinking it does not work), then reselecting chat suddenly pending image share pops up.

(1594 build on Windows 10)

**Comment by FrayxRulez** [comment] 2018-09-13 16:28
Duplicate of #440

**Closed by FrayxRulez** 2018-09-13 16:28 UTC
Labels: duplicate
